### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by gabrielcalderon** [leon-ai/leon#1]
Is there plans to do Docker builds of Leon? As in provide an official image for it.

**Comment by louistiti** [comment]
Hello @gabrielcalderon,

There is actually a [Docker image](https://github.com/leon-ai/leon-ci-image) dedicated to CI purposes. It allows to get the prerequisites installed.

But there is indeed not yet a complete Docker image. I added it to the [roadmap](https://trello.com/c/VOhSdIC4/215-%E2%9C%A8-docker-image).

Is that something you would like to work on?

**Comment by gabrielcalderon** [comment]
@louistiti Sure, I can work on it.

**Comment by louistiti** [comment]
Great, then feel free to create a PR and I will move the [Trello card](https://trello.com/c/VOhSdIC4/215-%E2%9C%A8-docker-image) to "In Progress" once you started.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Docker image](https://trello.com/c/VOhSdIC4/215-%E2%9C%A8-docker-image)

**Comment by darvin** [comment]
done https://github.com/leon-ai/leon/pull/13

**Comment by louistiti** [comment]
Done in https://github.com/leon-ai/leon/pull/9.
