### ISSUE TITLE
Why "Leon"?

### ISSUE THREAD

**Issue by leondealmeida** [leon-ai/leon#10]
Such an amazing name, what's the story behind the choice?

**Comment by louistiti** [comment]
Hello @leondealmeida,

Thanks for your issue and for that very fair question. I'm gonna write-up about my story about Leon soonly, stay tuned 😉

**Comment by leye0** [comment]
Thanks.

- Leon

**Comment by louistiti** [comment]
Hey @leondealmeida @leye0,

I just published the [write-up](https://blog.getleon.ai/the-story-behind-leon/), happy reading 😉

**Comment by louistiti** [comment]
I close this issue as an answer has been provided.
