### ISSUE TITLE
me：“hello” Leon：“ Sorry, you should teach me this request. You can teach me by creating a pull request.” me：“what？” Leon："Sorry, you should teach me this request. You can teach me by creating a pull request."

### ISSUE THREAD

**Issue by ChangYunLei** [leon-ai/leon#100]
### Question
me：“hello”
Leon：“ Sorry, you should teach me this request. You can teach me by creating a pull request.”
me：“what？”
Leon："Sorry, you should teach me this request. You can teach me by creating a pull request."

**Comment by louistiti** [comment]
Hello @ChangYunLei,

Thanks for opening this issue. Please paste the whole result of the `npm run check` command.

**Comment by ChangYunLei** [comment]
> 你好@ChangYunLei，
> 
> 谢谢你打开这个问题。请粘贴`npm run check`命令的整个结果。

$ npm run check

> leon@1.0.0-beta.2 check D:\装机应用\智能语音\leon\leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

✖ Error: Command failed: C:\Windows\system32\cmd.exe /q /s /c "pipenv --version"
'pipenv' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by louistiti** [comment]
It seems you did not setup Pipenv, so you need to install it. Please see the [prerequisites](https://docs.getleon.ai/#prerequisites).

**Comment by ChangYunLei** [comment]
> It seems you did not setup Pipenv, so you need to install it. Please see the [prerequisites](https://docs.getleon.ai/#prerequisites).

ok ~~  Thank you very much for your positive response.

**Comment by louistiti** [comment]
不客气朋友 ~

I'll close this issue, feel free to reopen it if you need to.
