### ISSUE TITLE
docker: Error response from daemon: pull access denied for leon, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by Sathiyarajan** [leon-ai/leon#101]
### Specs

- Leon version: latest
- OS (or browser) version: Ubuntu 18.10
- Node.js version: 
- Complete "npm run check" output: 
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Expected Behavior
docker image should be up and running
### Actual Behavior
docker: Error response from daemon: pull access denied for leon, repository does not exist or may require 'docker login'. 
docker run --rm -it -p 1337:1337 leon npm run check
Unable to find image 'leon:latest' locally
docker: Error response from daemon: pull access denied for leon, repository does not exist or may require 'docker login'.
See 'docker run --help'.

### How Do We Reproduce?
docker run --rm -it -p 1337:1337 leon npm run check 
### Extra (like a sample repo to reproduce the issue, etc.)
Urgent help is needed so that I can contribute further?

**Comment by louistiti** [comment]
Hello @Sathiyarajan,

Thanks for opening this issue. Did you make sure you built the image at first before executing the run command?

```bash
npm run docker:build
npm run docker:run
# Go to http://localhost:1337
```

**Comment by louistiti** [comment]
I'm gonna close this issue as there is no answer.
