### ISSUE TITLE
Testing a package

### ISSUE THREAD

**Issue by Imperator26** [leon-ai/leon#105]
### Specs

- Leon version: 1.0.0-beta.3
- OS (or browser) version: Firefox
- Node.js version: 10.16.0
- Complete "npm run check" output: Hooray! Leon can run correctly
- (if using Docker) Complete "npm run docker:check" output: nope
- (optional) Leon package version:

### Expected Behavior
I've written this package but leon is able to recognize only the first expression set even if I ask him something different that should match other expression sets. So I tried to momentarly remove the first expression set and see what would happen. This is the result, but it's not very informative to me.

### Actual Behavior
```
.: NER :.

➡ Searching for entities...
(node:69002) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'entities' of undefined
    at Promise (/Users/federico/Dropbox/GitHub/leon/server/dist/core/ner.js:57:49)
    at new Promise (<anonymous>)
    at Ner.extractActionEntities (/Users/federico/Dropbox/GitHub/leon/server/dist/core/ner.js:37:12)
    at Nlu.process (/Users/federico/Dropbox/GitHub/leon/server/dist/core/nlu.js:159:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:69002) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

### How Do We Reproduce?
You might need the package...

**Comment by louistiti** [comment]
Hello @Imperator26,

Thanks for opening that issue and for creating a new package if I understood correctly.

Could you please give more context? What's the package for? What are you doing exactly (commands, etc.) to get this error?

**Comment by Imperator26** [comment]
Yes I'm working on a simplier weather package myself. You can check it out at [my fork](https://github.com/Imperator26/leon)

**Comment by louistiti** [comment]
![Peek 2019-06-09 08-27](https://user-images.githubusercontent.com/1731544/59153624-6c651b80-8a90-11e9-844a-4f09ad568d98.gif)

Well done! I've tried your fork and it's working pretty well.

Now regarding your concern, could you please provide me the expressions file that is causing that error and also tell me what sentences are you giving to Leon?

**Comment by Imperator26** [comment]
@louistiti If you try to ask him "When is the sun going to rise in London?" it doesn't work. He answers like I asked "What's the weather like in London?". I tried `npm run train expressions`multiple times, but that did't work. So I tried to momentarely remove the expression "What's the weather like in", but I get the error above.

**Comment by louistiti** [comment]
![Peek 2019-06-09 15-52](https://user-images.githubusercontent.com/1731544/59156475-b4a32e80-8ace-11e9-9e5d-6fca9c3141a5.gif)

It looks good here :thinking: 

I'm on [this commit](https://github.com/Imperator26/leon/tree/41cd3b9e4dd004421dffee693bc9f91428e8f58a).

**Comment by Imperator26** [comment]
> ![Peek 2019-06-09 15-52](https://user-images.githubusercontent.com/1731544/59156475-b4a32e80-8ace-11e9-9e5d-6fca9c3141a5.gif)
> 
> It looks good here 🤔
> 
> I'm on [this commit](https://github.com/Imperator26/leon/tree/41cd3b9e4dd004421dffee693bc9f91428e8f58a).
> 
> Maybe try to `git pull` and reinstall the project, several changes have been made since your fork.

Interesting... I'll try that

**Comment by Imperator26** [comment]
It works I'll make a PR

**Comment by Imperator26** [comment]
PR #108
