### ISSUE TITLE
utils.info()

### ISSUE THREAD

**Issue by gnouf1** [leon-ai/leon#106]
### Specs

- Leon version: 1.0.3
- OS (or browser) version: Windows 10 but Leon is under WSL ubuntu 
- Node.js version: 11

### Expected Behavior
Return the info with utils.info()

### Actual Behavior
Crash when i use my module (weather) :
```
✖ Traceback (most recent call last):
  File "bridges/python/main.py", line 20, in <module>
    main()
  File "bridges/python/main.py", line 17, in main
    return getattr(m, queryobj['action'])(queryobj['query'], queryobj['entities'])
  File "./packages/leonweather/weather.py", line 29, in weather
    language = utils.info()
  File "/home/theo/leon-dev/bridges/python/utils.py", line 102, in info
    return { 'lang': lang, 'package': package, 'module': module }
NameError: name 'lang' is not defined
```

### How Do We Reproduce?
Juste add ``` language = utils.info()```

**Comment by louistiti** [comment]
Hello @gnouf1,

I'm glad to see that you are digging into Leon, thanks for reporting.

Just for a try, in the `bridges/python/utils.py` file, could you please replace:

```python
def info():
  """Get information from the current query"""

  return { 'lang': lang, 'package': package, 'module': module }
```

With:
```python
def info():
  """Get information from the current query"""

  return { 'lang': queryobj['lang'], 'package': queryobj['package'], 'module': queryobj['module'] }
```

And retry.

**Comment by gnouf1** [comment]
It's work ! :)

**Comment by louistiti** [comment]
Alright, tomorrow I'll change that.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.3] utils.info() return query object data](https://trello.com/c/NBnagR6B/290-%F0%9F%90%9E-100-beta3-utilsinfo-return-query-object-data)

**Comment by louistiti** [comment]
Done.

I've deleted `utils.info()` in favor of `utils.getqueryobj()` as you can see in [the docs](https://docs.getleon.ai/packages-modules.html#getqueryobj).

Does it help?

**Comment by louistiti** [comment]
I suppose it should be alright now, I'll close the issue.
