### ISSUE TITLE
Checker fails with capital letters in url

### ISSUE THREAD

**Issue by ClayMav** [leon-ai/leon#11]
### Specs

- Leon version:
- OS (or browser) version: MacOS 10.14.3
- Node.js version: 11.6.0
- Complete "npm run check" output:

: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.6.0

➡ /bin/sh -c npm --version
✔ 6.5.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /Users/maverick/git-local/Personal/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✖
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 74, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✖ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✖ Please fix the errors above

- (optional) Leon package version:

### Expected Behavior
Everything works mostly correct, I get proper output using the Checker, and I expect when giving the command
```Is GitHub.com up?```
to get back
```I am now requesting Github.
Github is running correctly.```

### Actual Behavior
```
Is GitHub.com up?

I'm trying to reach Ub.
Ub is up.
```

### How Do We Reproduce?
Type the commands as above

### Extra (like a sample repo to reproduce the issue, etc.)

**Comment by ClayMav** [comment]
`npm run check` reported almost complete failure, but everything is working with leon. Not sure why that is.

**Comment by kesslerdev** [comment]
yes the regex from utils doesn't allow capital letter on domain check [here](https://pythex.org/?regex=%5Ba-z0-9%5C-%5D%7B%2C63%7D%5C.%5Ba-z0-9%5C-%5C.%5D%7B2%2C191%7D&test_string=Twitter.com%20est%20down%20%3F%0A&ignorecase=0&multiline=0&dotall=0&verbose=0)

**Comment by Devilmoon** [comment]
Might want to check Django's URL validator, it could be lifted from their code without having to add the whole package as a dependecy.
Available [here](https://github.com/django/django/blob/master/django/core/validators.py)

**Comment by louistiti** [comment]
Hello @ClayMav,

It seems you do not have Python `3.6.x` install.

I merged the https://github.com/leon-ai/leon/pull/20 PR.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.1] Checker Package - Allow capital letters in the Is It Down module URLs](https://trello.com/c/xGzkOypW/229-%F0%9F%90%9E-100-beta1-checker-package-allow-capital-letters-in-the-is-it-down-module-urls)
