### ISSUE TITLE
type error model stt

### ISSUE THREAD

**Issue by astrowalker2013** [leon-ai/leon#111]
### Specs

- Leon version: 1.3.0 beta / developpement branch

- (if using Docker) Complete "npm run docker:check" output:
`➡ Encoding WebM file to WAVE file...
✔ Encoding done
➡ Parsing WAVE file...
/app/server/dist/stt/deepspeech/parser.js:155
    const string = model.stt(buffer.slice(0, buffer.length / 2), 16000);
                         ^

TypeError: model.stt is not a function
    at Object.parser.parse (/app/server/dist/stt/deepspeech/parser.js:155:26)
    at Stt.parse (/app/server/dist/stt/stt.js:99:27)
    at FfmpegCommand.ffmpeg.addInput.on.on (/app/server/dist/core/asr.js:74:17)
    at FfmpegCommand.emit (events.js:198:13)
    at emitEnd (/app/node_modules/fluent-ffmpeg/lib/processor.js:426:16)
    at endCB (/app/node_modules/fluent-ffmpeg/lib/processor.js:587:15)
    at handleExit (/app/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:184:11)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-09T15_45_09_475Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 docker:run: `docker run -e TZ=`cat /etc/timezone` -p 1337:1337 -it leonai/leon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.3 docker:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/florian/.npm/_logs/2019-06-09T15_45_09_757Z-debug.lo`

- (optional) Leon package version:

### Expected Behavior
When I click  on the mic and speek , the mesage must be display in the interface,
### Actual Behavior
The message doesn't display, and the docker stop with error.
show the log upper .

### How Do We Reproduce?

my env file : 
for Speach To Text : 
`# Enable/disable Leon's speech-to-text
LEON_STT=true
# Speech-to-text provider
LEON_STT_PROVIDER=deepspeech
`
click on the mic the mic is green I began to speak and just after the docker stop

**Comment by louistiti** [comment]
Hello @astrowalker2013,

Sorry for the late reply, I'm currently taking some holidays.

Please provide the complete report output via: `npm run docker:check`

**Comment by astrowalker2013** [comment]
`
[florian@leon leon]$ npm run docker:check

> leon@1.0.0-beta.3 docker:check /home/florian/leon
> docker run --rm -it -p 1337:1337 leonai/leon npm run check


> leon@1.0.0-beta.3 check /app
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.3

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /app/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.8

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 92, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
[florian@leon leon]$
`
it's the result 
my .env file is true for STT and TTS  and i execute your last comment with #104 

Best

**Comment by louistiti** [comment]
This is normal, you did not setup any STT provider. See [the docs](https://docs.getleon.ai/configuration.html#voice) to know more.

**Comment by astrowalker2013** [comment]
ok how ever when i execute 

> 
[florian@leon setup-offline]$ npm run setup:offline

> leon@1.0.0-beta.3 setup:offline /home/florian/leon
> babel-node scripts/setup-offline/setup-offline.js

➡ Checking OS environment...
✔ You are running Linux
➡ Checking tools...
✔ "tar" found
✔ "make" found
✖ The following command has failed: "apt-get --version". "apt-get" is maybe missing. To continue this setup, please install the required tool. More details about the failure: Error: spawn apt-get ENOENT
✖ Error: spawn apt-get ENOENT
[florian@leon setup-offline]$

> 

I am in arch linux  and apt-get doesn't existe .
or this command need to execute in the docker ? 
Thanks for your Help

Best

**Comment by aorizondo** [comment]
I have the same problem with the STT, everything is according with the docs. Im using debian 10

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
