### ISSUE TITLE
Get today's trending projects from github

### ISSUE THREAD

**Issue by ZhigangPu** [leon-ai/leon#113]
### Feature Use Case
- show me today's trending projects?
- what's today's trending projects?

### Feature Proposal
Get trending projects' structural information from github.
![image](https://user-images.githubusercontent.com/24690469/59193310-d9bf9c00-8bb7-11e9-9653-5125530bdb3e.png)

**Comment by gnouf1** [comment]
The trend package already do that no ?

**Comment by ZhigangPu** [comment]
Sorry, I didn't pay attention to the trend package. emmm.....

**Comment by louistiti** [comment]
Hello @ZhigangPu,

It's alright. Feel to suggest and/or contribute 😉
