### ISSUE TITLE
deepspecch

### ISSUE THREAD

**Issue by Karthik-MA** [leon-ai/leon#117]
### Question
when i am trying to get the program installed i get this error"Failed at the leon@1.0.0-beta.2 preinstall script" is there anyway to fix it ?
npm@6.9.0
node@v10.16.0
python 3.7.3
pipenv version 2018-11-26
[2019-06-18T13_55_58_310Z-debug.log](https://github.com/leon-ai/leon/files/3301888/2019-06-18T13_55_58_310Z-debug.log)

**Comment by louistiti** [comment]
Hello @Karthik-MA,

Thanks for opening this issue.

It seems you are using Windows, as DeepSpeech is not available on this OS for Leon, then it will remove DeepSpeech from the tree dependencies before installing.

Please try those two things:

1. Install Python 3.6 and execute `npm install`
2. If 1. does not work, open the `package.json` file; remove the line `"deepspeech": "^0.4.1",` and execute `npm install`

I recently updated the docs to accept any kind of Python version 3 and not only Python 3.6. As it seems DeepSpeech is requiring Python 3.6, the problem might come from here. If so, I will update the docs.

Let me know how is it going.

**Comment by Karthik-MA** [comment]
trying it rn its installing FFmpeg rn

**Comment by Karthik-MA** [comment]
it worked after doing the step 2 thanks for the quick reply

**Comment by louistiti** [comment]
Alright, do not hesitate to open an issue if necessary.
