### ISSUE TITLE
Where is the .env file usually stored? 

### ISSUE THREAD

**Issue by JonathanChiang** [leon-ai/leon#12]
### Question
I would like to set some env variables where is this file typically stored? after build is successful?

**Comment by louistiti** [comment]
Hello @JonathanChiang,

Thanks for your issue. After the `npm install` command (which runs `npm run postinstall`), your `.env` file is generated at the root of the project from the `.env.sample` one.

**Comment by louistiti** [comment]
I will close this issue as the answer has been provided. Feel free to open it if you still have questions regarding that specific topic.
