### ISSUE TITLE
Cannot find module 'follow-redirects'

### ISSUE THREAD

**Issue by Karthik-MA** [leon-ai/leon#120]
### Question
i get `cannot find module 'follow--redirects'` is there any way to fix it?

**Comment by Karthik-MA** [comment]
https://pastebin.com/UtwKJKkV pastebin of error 
[2019-06-26T14_12_52_299Z-debug.log](https://github.com/leon-ai/leon/files/3330431/2019-06-26T14_12_52_299Z-debug.log)

**Comment by louistiti** [comment]
Hello @Karthik-MA,

I'm currently taking holidays, that explains my late answer. It seems your setup was not complete.
