### ISSUE TITLE
Another language

### ISSUE THREAD

**Issue by ahmadrezash** [leon-ai/leon#123]
Hi,
I love your project and I love NLP.
Can I translate leon packages to another language like Persian?
I love contributing to this project.
Are you merge that?

Ahmad

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Hello @ahmadrezash,

Thanks for willing to contribute! For the moment I do not merge translations but French and English. However, I added you to the list of translators, so once we'll focus on more languages support then we can translate Leon to Persian language.

What do you think?

**Comment by ahmadrezash** [comment]
Hi,
I can't understand what you mean.
My native language is Persian and I can translate "answer" and "question"
and ... file very well to Persian.
I can start now and finish that soon.
It is in your priority?
I will be so happy for doing that, as the start of contribute :)


Ahmadreza Sharifianzade, computer science student @ SBU

**Comment by louistiti** [comment]
We will focus on translations later but not now 😉

**Comment by ahmadrezash** [comment]
Ok
That's fine.
But now.
I'm python developer, assign me a task in Leon development, please.
New feature for old packages or new package or...
Tnx

Ahmadreza Sharifianzade, computer science student @ SBU

**Comment by louistiti** [comment]
Alright! Feel free to pick up a Leon module that is in the backlog of the [roadmap](https://roadmap.getleon.ai).
