### ISSUE TITLE
ℹ️ Going part time and focusing on another project for a while

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#125]
Hey everyone 👋,

I'm opening this issue to say that I'm **going part time with my day job** so now I'll have more time to focus on my own projects. Which means Leon will speed up in the future!

However, I'm **currently focusing on another project** called "**2aud.io**", basically it is a service that will allow you to **convert web links, files and texts to audio**. You can [**subscribe here**](https://www.producthunt.com/upcoming/2aud-io) to be part of the first ones.

Once I'm done with the first version of this project, I'll **focus again on Leon**. It'll be promising, stay tuned!

**Comment by louistiti** [comment]
Hello all 👋,

Quick update here. I'm still working on 2aud.io now and it'll still take some time.

However, I'm creating enough generic code for 2aud.io that will be very useful for Leon in the future, stay tuned!

**Comment by Peppuz** [comment]
I just find you out, I really like the project, looks a bit at a starting point, but i saw Trello, and there are tons of ideas to make real. Great job on the whole platform, I'll wait you to come back as full-time here!

**Comment by louistiti** [comment]
Thanks!

I'm very looking forward to come back to it too.

**Comment by louistiti** [comment]
Hello all,

Another quick update here for the ones who don't follow the emails I'm sending.

I'm still focusing on my other projects for the moment. Once I'll be done with them, I'll focus on Leon again, I've never thought about giving up our dear Leon. Please be a little bit more patient 😀

Just want to try some other adventures here and there first before to fully come back on track!

**Comment by Vincz** [comment]
Hey @louistiti :-) I was looking for an open source assistant and yours seems really promising. But it seems that it hasn't been updated in almost 18 months. Do you know when you'll have time to focus on Leon again? Really don't want to push anything, it's just to help make a decision. Thanks!

**Comment by louistiti** [comment]
Hello @Vincz,

Thanks for your message. I'm currently in a position where I'm questioning my career path. I haven't decided yet when I'm going to focus on Leon again as this depends of the questioning outcomes.
In the meantime, I continue to take notes and get new ideas for Leon for the future.

**Comment by Vincz** [comment]
Thanks for you reply @louistiti ! I bookmarked you repository and I'll check ! 
Have a great day!

**Comment by louistiti** [comment]
Hello everyone 👋,

I know it has been a while... Like really a long time. I'm finally slowly coming back to our dear Leon now. 

Feel free to join the [Discord server](https://discord.gg/MNQqqKg) as it'll be an important place to discuss about Leon.

I'm very excited to come back on track. I'll write up a blog post later to provide more details about what happened and where Leon is going to. In the meantime, feel free to take a look at the [updated roadmap](https://roadmap.getleon.ai).

Cheers! 🍹

**Comment by Vincz** [comment]
Awesome! Glad that you're back. I will follow closely! Welcome back!
