### ISSUE TITLE
Fresh install Crash

### ISSUE THREAD

**Issue by japita-se** [leon-ai/leon#127]
After installing offline DeepSpeech:

```
.: LEON :.

➡ Talking...

---

.: LEON :.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn bin/flite/flite ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/giuseppe/.npm/_logs/2019-07-18T19_43_08_823Z-debug.log
(leon)  giuseppe  (e) leon  ~  Software  leon   
```

**Comment by louistiti** [comment]
Hello @japita-se,

Thanks for opening this issue.

It seems that your text-to-speech [option](https://docs.getleon.ai/configuration.html#environment-variables) is enabled and with the `flite` offline provider. However, you did not install that one, so when Leon tries to speak, he cannot use this offline voice.

So:

1. Either disable the TTS for now via the `.env` file.
2. Either you download Flite as specified in [the docs](https://docs.getleon.ai/offline.html#flite-tts).

You can use the `npm run check` to check how your Leon is configured.

Please let me know if that helps.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
