### ISSUE TITLE
How is Leon trained

### ISSUE THREAD

**Issue by Outstep** [leon-ai/leon#128]
I am researching virtual assistants for possible use in a project as the base to build from. Some of these project are Almond (Stanford University), Rasa, Myfroft (for web interface), and Leon.

The base of the project is a virtual assistant AI knowledge base that can perform additional tasks.

Could you please tell me know about how Leon is trained to gather more skill sets as I ran the Docker version, but it did not seem to have much of a knowledge base by default and I did not know how to extend it, or perhaps make Internet calls to other websites to draw knowledge from which is why I am asking the question?

Thanks,

**Comment by louistiti** [comment]
Hello @Outstep,

Glad to see that you are doing such researches.

Have you take a look at [the architecture](https://docs.getleon.ai/architecture.html)? On the top of that, by reading [this section](https://docs.getleon.ai/packages-modules.html) and/or by creating a new module of Leon, you'll be able to answer to all of your questions.

If you have further or more specific questions, I'll be happy to chat [via Discord](https://discord.gg/MNQqqKg).

**Comment by louistiti** [comment]
Got it, do not hesitate to ask in case you have any questions.

I'm gonna close it, feel free to reopen it if you find it's necessary.
