### ISSUE TITLE
Create a new language

### ISSUE THREAD

**Issue by ostenieverson** [leon-ai/leon#132]
How to create a new language?

**Comment by gnouf1** [comment]
You mean how to add an translate ?

**Comment by louistiti** [comment]
Hello @ostenieverson,

Please see [this issue](https://github.com/leon-ai/leon/issues/123).

What language would you like to add?

**Comment by ostenieverson** [comment]
Português Brasil

Em qui, 15 de ago de 2019 21:58, Louis Grenard <notifications@github.com>
escreveu:

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Alright, I've linked this issue to the language support card on [the roadmap](https://trello.com/c/PqiIElyx/217-✨-languages-support). So when we'll be supporting more languages, I'll let you know.

Thanks.
