### ISSUE TITLE
How to display a plot.ly chart in the leon answer module.

### ISSUE THREAD

**Issue by soomro30** [leon-ai/leon#135]
I am developing a custom package where it will leon will answer project status update.

I have installed and added the plot.ly library.

How do we display a plotly chart in the leon frontend chatbox?

**Comment by louistiti** [comment]
Hello @soomro30,

I plan to create a widget system in the future as mentioned [in the roadmap](https://trello.com/c/LIDwVtfF/136-%E2%9C%A8-chatbot-aspect) where every module could have a dedicated component output on the client.

For the instance, you can try to put your HTML in the answers of your module and create/import your CSS and JavaScript [in the client](https://github.com/leon-ai/leon/tree/develop/app).

**Comment by soomro30** [comment]
I tried to add a div with an id in the answer and add the css and Javascript in the index.html but it is not working. Anyways thanks for the answer. 

Also I asked one question that how can i modify the hotword "Leon". I want to use another word

**Comment by louistiti** [comment]
You can take a look at [this](https://snowboy.kitt.ai/) to generate your model. Then put your model in [this folder](https://github.com/leon-ai/leon/tree/develop/hotword/models). And edit the `.pmdl` filename [here](https://github.com/leon-ai/leon/blob/develop/hotword/index.js#L36) if necessary.

Feel free to open a new issue regarding that topic.

**Comment by F0x1fy** [comment]
Hello, came here from #133. The website you provided is no longer reachable. Do you by chance have another resource we can use? In fact, I don't understand much about the intricacies of how the hotword works internally, so is there something stopping it from using the TTS to watch for the hotword? I feel that would be a better option over generating a personal model, and would be much more easily configurable.

**Comment by louistiti** [comment]
> Hello, came here from #133. The website you provided is no longer reachable. Do you by chance have another resource we can use? In fact, I don't understand much about the intricacies of how the hotword works internally, so is there something stopping it from using the TTS to watch for the hotword? I feel that would be a better option over generating a personal model, and would be much more easily configurable.

Hello, yes indeed, Snowboy has stopped their service a while ago. I plan to find an alternative in the future.
