### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by Gadgetroch** [leon-ai/leon#138]
Good morning,

When i launch npm install, i get that :
`✖ Error: Command failed: /bin/sh -c pipenv install --skip-lock
Warning: Python 3.6 was not found on your system...
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
`

I am on raspberry 1, raspbian 10

**Comment by gnouf1** [comment]
When you just type "python" in terminal what's the version ? 
Check if it's not 2.7 or other 

Also Leon might not work on RP.

**Comment by Gadgetroch** [comment]
So i can't use it on raspberry ? :(
I'm on python 2.7, but i can install python 3 but i have python 3.7.

**Comment by Imperator26** [comment]
Please follow these [instructions](https://docs.getleon.ai/how-to/#how-to-install-python)

**Comment by Gadgetroch** [comment]
Already made

**Comment by gnouf1** [comment]
change python alias for python3.

But for RP I'm not sure it's work :/

**Comment by Gadgetroch** [comment]
I have python 3.7. I try ?

**Comment by gnouf1** [comment]
Yup

**Comment by jonlie1107** [comment]
I'm running into the same problem. Did anyone find a way to get past this?

**Comment by jonlie1107** [comment]
Was able to resolve it. Pyenv worked out for me

**Comment by Simvolick** [comment]
Pyenv Solved

**Comment by louistiti** [comment]
https://github.com/leon-ai/leon/issues/37 ; https://github.com/leon-ai/leon/issues/28

**Comment by JeanLoupCaillet** [comment]
Someone know why python 3.6 and not 3.7 ?
In readme only python >=3 is written.

I'm currently on Kali for personal reasons and all packages 3.6 have been removed :) --'

**Comment by lapchun** [comment]
I also met this problem and I solved it successfully by modifying three files, **bridges/python/Pipfile** **bridges/python/Pipfile.lock** **scripts/check.js**.

- **bridges/python/Pipfile**: find "python_version", replace 3.6 with 3.7

- **bridges/python/Pipfile.lock**: find "python_version", replace 3.6 with 3.7

- **scripts/check.js**: find "pythonRequiredVersion", replace 3.6 with 3.7

I am on Win10 and my python version is 3.7.

**Comment by JeanLoupCaillet** [comment]
Thanks for your answer I will test it :)

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
