### ISSUE TITLE
Fedora & apt-get

### ISSUE THREAD

**Issue by Lp-Francois** [leon-ai/leon#141]
### Specs

- Leon version: latest
- OS (or browser) version: Fedora 30
- Node.js version: 10.16.3
- Complete "npm run check" output: 

```
➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text
✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
```

- (if using Docker) Complete "npm run docker:check" output: _
- (optional) Leon package version: _

### Expected Behavior

Run without errors the `npm run setup-offline`.

### Actual Behavior

Throw this error after `npm run setup-offline` :

```
The following command has failed: "apt-get --version". "apt-get" is maybe missing. To continue this setup, please install the required tool. More details about the failure: Error: spawn apt-get ENOENT
✖ Error: spawn apt-get ENOENT
```

### How Do We Reproduce?

Use Fedora OS, follow the Readme (clone, npm install, etc.)
run `npm run check` and try to install missing parts (Offline text-to-speech & Offline speech-to-text as you can see in the complete output) with commands such `npm run setup:offline`.

### Extra (like a sample repo to reproduce the issue, etc.)

`scripts/check-os.js`does not make nay difference between different linux distributions and use `apt-get` by default. I think adding `dnf` support should correct the error.

I will try to fix it soon and to PR the fix.

Regards

_

**Comment by AsterYujano** [comment]
After adding `dnf` support, it seems like _sox libsox-fmt-all_ are not available on dnf/rpm but only with apt-get.

**Comment by louistiti** [comment]
Hello @AsterYujano,

Thanks for reporting. It was indeed a choice to not make difference between different Linux distributions, the reason is to keep it simple at first.

However, if you can get a fully workable installation process with Fedora, I'll be happy to work with you to support it 😃

**Comment by Divlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0] Compatibility with ARM architectures and test on Pis](https://trello.com/c/CxRNbLHQ/256-%F0%9F%94%A7-100-compatibility-with-arm-architectures-and-test-on-pis)

**Comment by b-bhupendra** [comment]
Hey ,Is this issue still open ? Can I contribute?

**Comment by louistiti** [comment]
> Hey ,Is this issue still open ? Can I contribute?

Thanks for willing to contribute. I do not recommend new contributions now as the whole core of Leon is being rewritten and such issue will no longer be valid.

**Comment by Lp-Francois** [comment]
Probably out-dated
