### ISSUE TITLE
Leon on windows10, npm failing to load or build

### ISSUE THREAD

**Issue by sprinteroz** [leon-ai/leon#147]
## Question
Hi all, I can not get the Leon AI to install on my laptop windows 10. I have the error log attached if anyone could help that be great thanks.

Also I when using windows visual studio with c++ support, as I found out in the error logs is there anything else I have to install?

PS C:\Users\Alienwarei7\leon> npm run check

⠋ leon@1.0.0-beta.2 check C:\Users\Alienwarei7\leon
---abel-node scripts/run-check.js

.: CHECKING :.

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "node --version"
✔ v12.13.1

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "npm --version"
✔ 6.12.1

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv --version"
✔ pipenv, version 2018.11.26

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv --where"
✔ C:\Users\Alienwarei7\leon

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv run python --version"
✖ TypeError: Invalid Version: 3.7.6rc1
    at new SemVer (C:\Users\Alienwarei7\leon\node_modules\semver\semver.js:312:11)
    at Range.test (C:\Users\Alienwarei7\leon\node_modules\semver\semver.js:1137:15)
    at Function.satisfies (C:\Users\Alienwarei7\leon\node_modules\semver\semver.js:1189:16)
    at C:/Users/Alienwarei7/leon/scripts/check.js:70:17
    at Array.forEach (<anonymous>)
    at C:/Users/Alienwarei7/leon/scripts/check.js:66:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[2019-12-15T08_22_12_908Z-debug.log](https://github.com/leon-ai/leon/files/3964731/2019-12-15T08_22_12_908Z-debug.log)

**Comment by sprinteroz** [comment]
Hi all, I see in the npm check, it says  pipenv run python --version Invalid Version: 3.7.6rc1, what version should I have installed to run Leon

**Comment by NateNoob** [comment]
i'm having exactly the same issue. I don't understand it. 

I have pyenv-win to manage python versions maybe that causes the issue. Do you have it too?

**Comment by pupperr** [comment]
Hello! It looks like it could be all of the outdated packages. But it works just fine through vmware on Ubuntu Desktop which is weird

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
