### ISSUE TITLE
Is it possible to write packages in NodeJs?

### ISSUE THREAD

**Issue by molotsnk** [leon-ai/leon#148]

**Comment by louistiti** [comment]
Hi,

Thanks for asking. No, it is not possible for the moment. I plan to implement it later, you can take a look at [this issue](https://github.com/leon-ai/leon/issues/48) and [this card](https://trello.com/c/z9lNNYKY/241-%E2%9C%A8-100-beta4-new-bridges).

Let me know if you have any questions.
