### ISSUE TITLE
Leon spanish supported?

### ISSUE THREAD

**Issue by johnfelipe** [leon-ai/leon#150]
Leon spanish supported?

**Comment by louistiti** [comment]
Hello @johnfelipe,

Thanks for asking. No, it is not yet supported as the focus is not set there for the moment. However, I may consider to add it in the future.

In the future, will you be interested to help with the translations?

**Comment by johnfelipe** [comment]
Count with me
Pls ensure to notify me

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Awesome, thanks!
