### ISSUE TITLE
Cant install Leon on lubuntu 18.04

### ISSUE THREAD

**Issue by AshrafAkon** [leon-ai/leon#151]
- Leon version: 1.0.0-beta.2
- OS (or browser) version: lubuntu 18.04
- Node.js version: v12.14.1
- Npm version : 6.13.4
Full npm check install log is added as file. kindly take a look at it. cant submit it in the text. its too long
[npm_check_install.log](https://github.com/leon-ai/leon/files/4038797/npm_check_install.log)

I installed npm, node according to the how to guide. But then when I try to use "npm install" on leons directory it fails to install. How can I solve this?

**Comment by menporulporiayalan** [comment]
@AshrafAkon  Can you please post the log here?

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
