### ISSUE TITLE
Errors during instalation, strange output

### ISSUE THREAD

**Issue by StraykerPL** [leon-ai/leon#152]
### Specs

- Leon version: the newest, downloaded with `git clone` command,
- OS (or browser) version: Windows Server 2019 Datacenter x64 with Google Chrome 79,
- Node.js version: 12.14.1
- Complete "npm run check" output: [here](https://github.com/leon-ai/leon/files/4049953/output.check.txt)
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Expected Behavior

There should be some information about instalation, right? But I don't see them in output.
`npm start` also don't work.

### Actual Behavior

This is what gives me `npm install` command: [output](https://github.com/leon-ai/leon/files/4049960/output.txt)

### How Do We Reproduce?

I just run `npm install` but after reconfiguration of Python from version 3.8 to 3.6 for satisfying `npm run check`, installation command gave two NPM logs.

### Extra (like a sample repo to reproduce the issue, etc.)

NPM logs:
[2020-01-11T23_18_18_620Z-debug.log](https://github.com/leon-ai/leon/files/4049969/2020-01-11T23_18_18_620Z-debug.log)
[2020-01-11T23_18_18_430Z-debug.log](https://github.com/leon-ai/leon/files/4049970/2020-01-11T23_18_18_430Z-debug.log)

**Comment by Umair0l** [comment]
I am also having this same problem

**Comment by Redone0001** [comment]
Same issue
[2020-02-16T22_00_41_472Z-debug.log](https://github.com/leon-ai/leon/files/4211019/2020-02-16T22_00_41_472Z-debug.log)
[2020-02-16T22_00_41_130Z-debug.log](https://github.com/leon-ai/leon/files/4211020/2020-02-16T22_00_41_130Z-debug.log)

Leon : last version
OS : Windows 10 up to date
node.js version : 13.8
npm run check : in attach

**Comment by MrDondoT** [comment]
same issue after `npm install`
Leon : last version
OS : Windows 10 pro
node.js version : 13.8
npm run check : in attach
[2020-02-17T16_10_08_371Z-debug.log](https://github.com/leon-ai/leon/files/4214801/2020-02-17T16_10_08_371Z-debug.log)

**Comment by TheLokj** [comment]
I had the same problem and I corrected it like that :

1. Firstly, clean your directory with `npm cache clean --force` and remove the _node_modules_ folder in you have one.
2. Secondly, make sure that the cmd is in administrator mode (launch the cmd directly by research, and write `cd <pathofleon>`).
3. Check the presence of the programs necessary to run leon : python 3 with `python --version` and pipenv with `pipenv --version`. Make sure that those programs could be used directly in the command prompt.
4. Finally, for me, the problem came from the Git's absence of my computer, install it from [here](https://git-scm.com/downloads).

**Comment by StraykerPL** [comment]
> For the error ELIFECYCLE on Windows 10, I had a similar problem and I corrected it like that :
> 
> 1. Firstly, clean your directory with `npm cache clean --force` and remove the _node_modules_ folder in you have one.
> 2. Secondly, make sure that the cmd is in administrator mode (launch the cmd directly by research, and write `cd <pathofleon>`).
> 3. Check the presence of the programs necessary to run leon : python 3 with `python --version` and pipenv with `pipenv --version`. Make sure that those programs could be used directly in the command prompt.
> 4. Finally, for me, the problem came from the Git's absence of my computer, install it from [here](https://git-scm.com/downloads).
> 
> I don't know if it can solve your problem, but I think it is useful to say it.

Hello @TheLokj !
Thank you for your help. When I tried out your instructions, installation still not working, but the output has changed a little. When I tried to search the output from console I found:

> npm ERR! code 1
> npm ERR! Command failed: git submodule update -q --init --recursive
> npm ERR! C:/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found

But when I enter the given path through the file explorer, I see that this given file exists. "git-sh-setup" is in the given folder, with "git-submodule" EXE. Maybe it's problem of calling this file, cos it's shell script, not application?

Cheers!

**Comment by NateNoob** [comment]
i'm having the same problem. 

Python 3.6.0
node v12.16.0
pipenv 2018.11.26
npm 6.13.4

[2020-04-13T23_27_32_505Z-debug.log](https://github.com/leon-ai/leon/files/4472371/2020-04-13T23_27_32_505Z-debug.log)

 I hope someone ll find the solution!

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
