### ISSUE TITLE
Other coding language version

### ISSUE THREAD

**Issue by DGCarramona** [leon-ai/leon#156]
### Question

Hello, I would like to examinate leon sources to implement very similar behaviours on other coding language (for example kotlin), allowing its use in other cases.
Willing to be fair, I prefer check if there is no problem in doing so.
Thanks

**Comment by louistiti** [comment]
Hi, there is no problem at all doing so. Open source is awesome 😄

**Comment by DGCarramona** [comment]
Thank you. My reimplementation would be, indeed, open source. Matter of fact, I've yet started a project of personal assistant (no publicity here, just sharing as saying) https://github.com/DGCarramona/KJarvis.
