### ISSUE TITLE
Error with "npm run check"

### ISSUE THREAD

**Issue by Gregoire-perso** [leon-ai/leon#157]
### Specs

- Leon version: the lastest version of the develop branch
- OS (or browser) version: Ubuntu 19.10
- Node.js version: 12.16.0
- Complete "npm run check" output: [here](https://github.com/leon-ai/leon/files/4211036/output.txt)

### Expected Behavior
It should be ok and I don't understand why it's not (I've already installed the module `tinydb` with `pip3 install tinydb` )

### Actual Behavior
`npm run check` is failling into running the module named `tinydb` even though that module is installed...

Thanks for your help

**Comment by louistiti** [comment]
Hello @Gregoire-perso,

Thanks for opening this issue.

You can take a look at [this issue](https://github.com/leon-ai/leon/issues/98) and also at [this one](https://github.com/leon-ai/leon/issues/7).

Let me know if that helps.

**Comment by Gregoire-perso** [comment]
Thanks a lot, it worked ! I haven't seen that issue before (maybe I didn't look very well...)
