### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by ZaptoInc** [leon-ai/leon#158]
### Question
Hello! Is there an API for Leon? i want to use it in my app but i can't find a doc for it on the docs.
Thanks!

**Comment by louistiti** [comment]
Hello @ZaptoInc,

Thanks for opening this issue. I have many ideas for what's next, and APIs are on the list, but not today yet.

Stay tuned!

**Comment by louistiti** [comment]
I close this issue as the answer has been provided.
