### ISSUE TITLE
Raspberry Pi 3B Bug

### ISSUE THREAD

**Issue by ebanDev** [leon-ai/leon#159]
Bonjour, étant intéressé par votre projet, j'ai tenté de l'installer sur mon raspberry pi 3B. J'ai les dernières versions de toutes les dépendances... Quand je lance sudo npm install, j'obtient, après un certain temps l'erreur suivante :
[https://pastebin.com/GsyHD6ma](url)

**Comment by louistiti** [comment]
Hello @ebanDev,

Thanks for opening this issue.

There is currently no support on it I believe. But I'll work on it in the future, please see the following issues: https://github.com/leon-ai/leon/issues/37 ; https://github.com/leon-ai/leon/issues/28.

**Comment by ebanDev** [comment]
All right, thanks for taking the time to answer.

**Comment by louistiti** [comment]
It looks like Leon works on Raspberry Pi 3B+ as per [this comment](https://github.com/leon-ai/leon/issues/37#issuecomment-803709534).
