### ISSUE TITLE
66 Vulnerabilities found in npm dependencies

### ISSUE THREAD

**Issue by abhisheksoni27** [leon-ai/leon#16]
### Specs

- Leon version: 1.0.0-beta.0
- OS (or browser) version: Chrome 71 | MacOS
- Node.js version:10.15.0
- Complete "npm run check" output: N/A

### Actual Behavior

After running `npm install`, I got the following output:

```
added 1554 packages from 828 contributors and audited 31148 packages in 141.769s
found 66 vulnerabilities (65 low, 1 high)
```

If you'd like, I can paste the output of the command `npm audit`. Do you have any plans to update the dependencies using something like greenkeeper?

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⬆️ [1.0.0-beta.1] Update jest-extended once they updated brace](https://trello.com/c/e7x8XqqY/220-%E2%AC%86%EF%B8%8F-100-beta1-update-jest-extended-once-they-updated-brace)

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Implement a tool such as Greenkeeper](https://trello.com/c/SdWlOyw3/221-%E2%9C%A8-implement-a-tool-such-as-greenkeeper)

**Comment by louistiti** [comment]
Hello @abhisheksoni27,

Thanks for reporting. Since yesterday, it seems that is caused by [braces](https://www.npmjs.com/advisories/786) which is used by the jest-extended package. There is an issue [over there](https://github.com/jest-community/jest-extended/pull/198).

I will consider using Greenkeeper. I attributed a [roadmap card](https://trello.com/c/SdWlOyw3/221-%E2%9C%A8-implement-a-tool-such-as-greenkeeper) for that.
And I created another [roadmap card](https://trello.com/c/e7x8XqqY/220-%E2%AC%86%EF%B8%8F-100-beta1-update-jest-extended-once-they-update-brace) regarding jest-extended itself.

**Comment by abhisheksoni27** [comment]
@louistiti Thanks! I'm really excited about what you have made and would love to contribute. Keep hustling!

**Comment by louistiti** [comment]
Thanks for your support!

I'm looking forward for your contribution then 👍

**Comment by louistiti** [comment]
I upgraded Jest to the latest (`24.1.0`), which decrease the vulnerabilities to `3 low severity vulnerabilities` https://github.com/leon-ai/leon/commit/5474b6eccc59cf4d59f303a5dfc8870013233799.

For the reminding vulns:

- It seems an update to Babel 7+ will be necessary: https://github.com/babel/babel/pull/9550.
- Still waiting for the merge: https://github.com/jest-community/jest-extended/pull/198.
- Waiting for the merge: https://github.com/BrowserSync/browser-sync/pull/1659.

**Comment by louistiti** [comment]
Browsersync has [been upgraded](https://github.com/leon-ai/leon/commit/0d70387ba3a99a9b40605feed56e513ff1e80618). Now `2 low severity vulnerabilities` left.

- It seems an update to Babel 7+ will be necessary: https://github.com/babel/babel/pull/9550.
- Still waiting for the merge: https://github.com/jest-community/jest-extended/pull/198.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.3] Remove minor dependencies vulns: back to 0 vuln](https://trello.com/c/OJ5HF0sr/287-%F0%9F%94%A7-100-beta3-remove-minor-dependencies-vulns-back-to-0-vuln)

**Comment by louistiti** [comment]
Good news, I've:

- Made the upgrade to Babel 7+.
- Created [a fork](https://github.com/leon-ai/jest-extended) of the `jest-extended` package to get away from the vulnerability.

I'll close this issue now as we came back to 0 npm dependencies vulnerabilities. Feel free to create a new one if you spot a new one.
