### ISSUE TITLE
[Docker] Unable to run any module

### ISSUE THREAD

**Issue by mattjcj** [leon-ai/leon#160]
### Specs

- Leon version: 1.0.0-beta.2
- OS (or browser) version: Windows 10 / Any (but I guess this is reproductible on any OS)
- Node.js version: v10.19.0
- Complete "npm run check" output: Run from inside the container, after command ` docker exec -ti [container_name] /bin/sh`
```
/app # npm run check

> leon@1.0.0-beta.2 check /app
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.19.0

➡ /bin/sh -c npm --version
✔ 6.13.4

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

✖ Error: Command failed: /bin/sh -c pipenv run python --version
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```
- (if using Docker) Complete "npm run docker:check" output: not working 

### Expected Behavior
Basically that it works out of the box. `npm run check` should return no error inside of a docker container.
Maybe the dockerfile needs specific packages versions.

Running the command `pipenv run python --version` manually inside the container returns `Python 3.8.1`

### Actual Behavior
Leon starts successfully, but entering commands "hello" or "Who are you ?" in the web interface returns that the modules are broken. `npm run check` inside the container returns errors, that Python 3.6 was not found.

### How Do We Reproduce?
- Download Leon source or clone it's repo (I downloaded it from the releases page)
- Run `npm run docker:build`
- Run `docker run -e TZ=UTC -p 1337:1337 -it leonai/leon`
- Access to http://localhost:1337/
- Enter any known command (Hello, Who are you...)

### Extra (like a sample repo to reproduce the issue, etc.)

PS : thanks for this gem can't wait to try it ! (unfortunately I don't have enough time to fiddle around and deal with dependencies problems, which is why I went for the Docker version)

**Comment by louistiti** [comment]
Hello @mattjcj,

Thanks for opening this issue.

> Leon starts successfully, but entering commands "hello" or "Who are you ?" in the web interface returns that the modules are broken. npm run check inside the container returns errors, that Python 2.6 was not found.

- According to your output, it shows `Python 3.6 was not found on your system`, but here you are mentioning about Python 2.6. Could you please clarify?
- Could you please try to pull Leon from the latest commit of the `develop` branch and retry with it?

**Comment by mattjcj** [comment]
Hello,

- Yes sorry, that's a typo I meant Python 3.6. I edited the original comment.
- It worked from the develop branch, so I searched a bit further and found #6 

Maybe the little `1.0.0-beta.1+` tag in the [documentation](https://docs.getleon.ai/#docker-installation) needs to be updated ?

So I'm closing it, thanks !

**Comment by louistiti** [comment]
Happy that you don't have any problem anymore!
