### ISSUE TITLE
bug report for the installation on Windows 10

### ISSUE THREAD

**Issue by jeremieclv** [leon-ai/leon#161]
### Specs

- Leon version: actual
- OS (or browser) version: Windows10
- Node.js version:  v12.16.0.

```
c:\Users\jeremie\Documents\GitHub\leon>npm --version
6.13.4

c:\Users\jeremie\Documents\GitHub\leon>pipenv --version
pipenv, version 2018.11.26

c:\Users\jeremie\Documents\GitHub\leon>python --version
Python 3.7.6

c:\Users\jeremie\Documents\GitHub\leon>node --version
v12.16.0
```

- Complete "npm run check" output: 

> leon@1.0.0-beta.3 check C:\Users\jeremie\Documents\Projet1\leon-develop2
> babel-node scripts/run-check.js

```

'babel-node' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 check: `babel-node scripts/run-check.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jeremie\AppData\Roaming\npm-cache\_logs\2020-02-19T16_32_57_470Z-debug.log

```
Bonjour Louis,
J'ai découvert ton projet via le youtubeur Micode. Je trouve ton projet très prometteur. Je souhaiterai le tester et contribuer. J'ai quelques idées notamment sur l'alimentation de Leon en "expressions" et en "answers".

Je rencontre un problème lors de l'installation :
j'ai désinstallé npm et réinstallé. J'ai recréé le projet et j'ai réessayé plusieurs fois mais je tombe toujours sur la même erreur.

Merci d'avance,
Bonne journée,
Jérémie

### Extra (like a sample repo to reproduce the issue, etc.)
[2020-02-19T16_13_39_213Z-debug.log](https://github.com/leon-ai/leon/files/4226100/2020-02-19T16_13_39_213Z-debug.log)
[log-terminal.txt](https://github.com/leon-ai/leon/files/4226101/log-terminal.txt)

**Comment by louistiti** [comment]
Hello @jeremieclv,

Thanks for opening this issue.

Can you please go to the `package.json` file and:
1. Remove [this line](https://github.com/leon-ai/leon/blob/develop/package.json#L60) and also [this one](https://github.com/leon-ai/leon/blob/develop/package.json#L32).
2. Delete the `package-lock.json` file.
3. Delete the `node_modules` folder.
4. Run `npm cache clean --force `
5. Then run `npm install`

Please let me know the result.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
