### ISSUE TITLE
Have I been Pwned api v2 is discontinued

### ISSUE THREAD

**Issue by gustafholst** [leon-ai/leon#162]
### Expected Behavior
Should tell me whether or not I have been pwned
### Actual Behavior
"This version of the API has been discontinued, please use V3: https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/"
### Proposal
Use v3 of the API

**Comment by louistiti** [comment]
Hello @gustafholst,

Thanks for opening this issue. I will take a look at it once I'll be back.

**Comment by louistiti** [comment]
Hi @gustafholst :wave:,

I know it has been a while. I'm finally coming back on track for Leon!

Leon now supports the API v3. Commit: https://github.com/leon-ai/leon/commit/0ca89fe32d51c80cec5f9446acf14990390a5917.

Feel free to reopen this issue if you see any trouble.

**Comment by gustafholst** [comment]
hi @louistiti!
great, thanks for the heads up!
