### ISSUE TITLE
fail to check 

### ISSUE THREAD

**Issue by vinedu18** [leon-ai/leon#165]
npm run check

> leon@1.0.0-beta.2 check /root/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.19.0

➡ /bin/sh -c npm --version
✔ 6.13.4

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /root/leon

➡ /bin/sh -c pipenv run python --version
✔ Python 3.5.3

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/root/leon/bridges/python/utils.py", line 10, in <module>
    from tinydb import TinyDB, Query, operations
ImportError: No module named 'tinydb'

➡ Classifier state
✖ Classifier not found or broken. Try to generate a new one: "npm run train expressions"

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/amazon.json'

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/google-cloud.json'

➡ Watson TTS
❗ Watson TTS is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/watson-tts.json'

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/watson-stt.json'
➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✖ Please fix the errors above

**Comment by louistiti** [comment]
Hello @vinedu18,

Thanks for opening this issue.

Please take a look at the following ones: https://github.com/leon-ai/leon/issues/7 and https://github.com/leon-ai/leon/issues/98.
