### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by CodexXAE** [leon-ai/leon#166]
Error when I write "Hello"
In Leon (http://localhost:1337/) "Sorry, I've got an error with the Greeting module of my Leon package!
Sorry, the Greeting module of my Leon package is brok"
In terminal ".: LEON :.

➡ Talking...
✖ Failed to delete query object file: Error: ENOENT: no such file or directory, unlink '/mnt/c/Users/User/Desktop/leon/server/dist/core/../tmp/1582804820581-2s5x.json'

---

.: LEON :.

---

.: LEON PACKAGE :.

➡
✖ Failed to delete query object file: Error: ENOENT: no such file or directory, unlink '/mnt/c/Users/User/Desktop/leon/server/dist/core/../tmp/1582804820581-2s5x.json'"

**Comment by louistiti** [comment]
Hello @Izox-github,

Please follow the [template](https://github.com/leon-ai/leon/issues/new?labels=bug&template=BUG.md) to report a bug.

**Comment by Divlo** [comment]
Thanks for your report!
Please reopen if it is still the case, also next time please follow the template! :smile:
