### ISSUE TITLE
Leon stuck on the loading screen

### ISSUE THREAD

**Issue by xrths** [leon-ai/leon#168]
### Specs

- Leon version: Last
- OS (or browser) version: Browser: Chrome | Host: Debian 10 Buster 
- Node.js version: v12.16.1
- Complete "npm run check" output: https://prnt.sc/rc8cuc
- (if using Docker) Complete "npm run docker:check" output: No Docker
- (optional) Leon package version: /

### Expected Behavior
Careful start of the Web UI

### Actual Behavior
Blocked on the load 
https://prnt.sc/rc89nc

### How Do We Reproduce?
Honestly, I don't know!

**Comment by od2** [comment]
`sudo apt install sqlite3-devel libsqlite3-dev pysqlite`

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
