### ISSUE TITLE
Stuck on Leon's web loading screen

### ISSUE THREAD

**Issue by Metal-Mighty** [leon-ai/leon#17]
### Specs

- Leon version: leon@1.0.0-beta.0
- OS (or browser) version: Debian 9.8
- Node.js version: v10.15.1
- Complete "npm run check" output:
```
> leon@1.0.0-beta.0 check /home/metal-mighty/github-repos/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.1

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/metal-mighty/github-repos/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.8

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 90, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
```

- (optional) Leon package version:

### Expected Behavior
Display Leon's web interaction interface as shown on the demo

### Actual Behavior
Stuck on the interface's loading screen (gray and loading animation). No error in the logs

### How Do We Reproduce?
-

### Extra (like a sample repo to reproduce the issue, etc.)
Server is hosted at home behind a router/ISP box. Ports 1337 and 4242 (great ports btw ;)) have been opened in the server's firewall and added to the NAT rules in the router in case some communication with the outside world was necessary.

Console log when accessing Leon's page:
```---
.: REQUESTING :.
➡ GET /
---
.: REQUESTING :.
➡ GET /css/style.css
---
.: REQUESTING :.
➡ GET /vendor/socket.io/2.0.3/socket.io.js
---
.: REQUESTING :.
➡ GET /js/main.js
---
.: REQUESTING :.
➡ GET /img/mic.svg
---
.: REQUESTING :.
➡ GET /img/logo.svg
---
.: REQUESTING :.
➡ GET /img/favicon.png
```

**Comment by ctombumila37** [comment]
This might be due to it expecting the API to be at ``localhost``.

Did you adjust the environment variables ``LEON_SERVER_HOST`` and ``LEON_WEBAPP_HOST`` according to the [docs](https://docs.getleon.ai/configuration.html#environment-variables)?

What does the js console say?

**Comment by Metal-Mighty** [comment]
I did adjust the environment variables in the .env file but somehow it still considers it as running on localhost.
![image](https://user-images.githubusercontent.com/5247527/52906497-43a0e800-324d-11e9-8d59-7f38bc2d046d.png)

I just tried with a SSH tunnel and it does work when using localhost.

**Comment by ctombumila37** [comment]
The only spot where ``localhost`` is hardcoded is here (web app):

https://github.com/leon-ai/leon/blob/360d1020c4bd8bf1df3764645c635c64e0364702/app/js/main.es6.js#L11-L17

Try to change that and rebuild with ``npm run build:app``.

If that's the issue, changing this file to use ``LEON_SERVER_HOST`` might be appropriate.

**Comment by Metal-Mighty** [comment]
That was the issue indeed! Works fine after changing it and rebuilding.
I'm a complete noob in JS/Node though so I wouldn't know how to make a clean correction to that.

**Comment by louistiti** [comment]
Hello @Metal-Mighty @ctombumila37,,

Thanks for your issue and for helping.

The `config.server_host` value is hard coded in this file because it is a file belonging to the web app. You cannot explicitly give a environment variable such as `LEON_SERVER_HOST` here. It could work if we transform that variable in a build phase tho.

**Comment by louistiti** [comment]
I close this issue as it has been fixed.

**Comment by Metal-Mighty** [comment]
The "official" solution is to change the config in the webapp then?

**Comment by Zauberfisch** [comment]
Do we really need to hardcode localhost anyway?

Is this intended to be a security measure?

**Comment by louistiti** [comment]
> Do we really need to hardcode localhost anyway?

Not anymore soonly: https://github.com/leon-ai/leon/pull/29 😉 

> Is this intended to be a security measure?

Not really.

**Comment by Zauberfisch** [comment]
Why can't we do a dynamic host?

Might I suggest either not specify a host at all and let the browser figure it out or use javascript to detect what hostname was used dynamically per request?
