### ISSUE TITLE
Unable to resolve path to module 

### ISSUE THREAD

**Issue by voknelim** [leon-ai/leon#170]
Hello,

I cannot install leon, this error prevents me.

I followed the procedure to the letter, but it does not work.

Thank in advance for your help.

Best regards

### Specs

- Leon version:  leon@1.0.0-beta.2
- OS (or browser) version: Windows 10
- Complete "npm run check" output:
 C:\WINDOWS\system32\cmd.exe /q /s /c "node --version"
✔ v12.16.1

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "npm --version"
✔ 6.13.4

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv --version"
✔ pipenv, version 2018.11.26

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv --where"
✔ C:\Users\voknelim\Documents\PDG-THOT\leon\bridges\python

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv run python --version"
✔ Python 3.6.0

➡ C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv run python bridges/python/main.py scripts/assets/query-object.json"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 71, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
- (optional) Leon package version:

### Check is OK but build not work !!!

npm run build
> npm run lint && npm run build:app && npm run build:server

> leon@1.0.0-beta.2 lint C:\Users\voknelim\Documents\PDG-THOT\leon
> babel-node scripts/lint.js

➡ Linting...
✖ Does not look great: 
C:\Users\voknelim\Documents\PDG-THOT\leon\server\src\stt\google-cloud-stt\parser.js
  3:17  error  Unable to resolve path to module '@google-cloud/speech'  import/no-unresolved
  3:17  error  Missing file extension for "@google-cloud/speech"        import/extensions

C:\Users\voknelim\Documents\PDG-THOT\leon\server\src\tts\google-cloud-tts\synthesizer.js
  3:17  error  Unable to resolve path to module '@google-cloud/text-to-speech'  import/no-unresolved
  3:17  error  Missing file extension for "@google-cloud/text-to-speech"        import/extensions

✖ 4 problems (4 errors, 0 warnings)

npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 lint: `babel-node scripts/lint.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\voknelim\AppData\Roaming\npm-cache\_logs\2020-03-14T12_49_27_029Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 build: `npm run lint && npm run build:app && npm run build:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\voknelim\AppData\Roaming\npm-cache\_logs\2020-03-14T12_49_27_073Z-debug.log

**Comment by louistiti** [comment]
Hello @voknelim,

Thanks for opening this issue.

Can you try to install Leon from the `develop` branch? So you should get the `1.0.0-beta.3` version.

If that does not work, try the following:

Can you please go to the `package.json` file and:
1. Remove [this line](https://github.com/leon-ai/leon/blob/develop/package.json#L60) and also [this one](https://github.com/leon-ai/leon/blob/develop/package.json#L32).
2. Delete the `package-lock.json` file.
3. Delete the `node_modules` folder.
4. Run `npm cache clean --force `
5. Then run `npm install`

Please let me know the result.

**Comment by voknelim** [comment]
Hello Luis,

Thanks a lot for your help.

It worked with the trick of deleting the lines and running npm cache clean --force.

Best regards

**Comment by louistiti** [comment]
Happy to see that it helped!

I'll let this issue opened to take a look at it once I'll be back.

**Comment by louistiti** [comment]
Should work with the current `develop` branch. Closing this as it'll be part of the next release.
