### ISSUE TITLE
Error installing pipenv on Ubuntu 18.04

### ISSUE THREAD

**Issue by auxsophia** [leon-ai/leon#173]
### Specs

- Leon version: 1.0.0-beta.3
- OS (or browser) version: Ubuntu 18.04
- Node.js version: v13.11.0
- Complete "npm run check" output: only missing TTS and STT
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Expected Behavior
Installing pipenv through pip.

### Actual Behavior
Installing pipenv through pip does not install. It downloads but --version check fails.

### How Do We Reproduce?
Follow installation procedures on Ubuntu 18.04.

### Extra (like a sample repo to reproduce the issue, etc.)
I was able to solve the issue and get Leon running with this: https://gist.github.com/kogcyc/07c3e5d1f427c9fa6b99044d81f8ee82

I believe this issue was similar to https://github.com/leon-ai/leon/issues/36 but solved differently.

**Comment by tdevilleduc** [comment]
Same behaviour on Win10

**Comment by dasco69** [comment]
hi,
you can testing this.
Open your terminal and write: 
`$ python3 -m site --user-base`
He return:
`/home/NAME/.local/bin`
After write:
`$ (vi, vim, atom, OR vscode) ~/.bashrc`
Add this line at the end of file:
`export PATH=$PATH:/home/NAME/.local/bin`
Close your terminal and re open, ad testing Pipenv.
for it worked.
**For windows normaly:**
`python -m site --user-site`
`C:\Users\NAME\AppData\Roaming\Python\Python36\site-packages`
Good luck

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
