### ISSUE TITLE
about error：Failed at the deepspeech@0.4.1 install script.

### ISSUE THREAD

**Issue by youxiaodao** [leon-ai/leon#175]
when i run npm install，i got this！what can i do  for this to repair it？
####
44461 verbose pkgid deepspeech@0.4.1
44462 verbose cwd /server/tools/leon
44463 verbose Linux 3.10.0-1062.1.1.el7.x86_64
44464 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
44465 verbose node v12.16.1
44466 verbose npm  v6.13.4
44467 error code ELIFECYCLE
44468 error errno 1
44469 error deepspeech@0.4.1 install: `node-pre-gyp install --fallback-to-build`
44469 error Exit status 1
44470 error Failed at the deepspeech@0.4.1 install script.
44470 error This is probably not a problem with npm. There is likely additional logging output above.
44471 verbose exit [ 1, true ]

**Comment by Divlo** [comment]
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
