### ISSUE TITLE
[#bug] Error when running "npm run build"

### ISSUE THREAD

**Issue by FloksyYT** [leon-ai/leon#178]
When I run the command "npm run build", I got some errors.
I'm running Ubuntu 18.04.4 LTS inside VirtualBox.
Here is my terminal output :

virtualbox@VirtualBox-Ubuntu:~/Git/leon$ npm run build
\> leon@1.0.0-beta.2 build /home/virtualbox/Git/leon
\> npm run lint && npm run build:app && npm run build:server
\> leon@1.0.0-beta.2 lint /home/virtualbox/Git/leon
\> babel-node scripts/lint.js

➡ Linting...
✖ Does not look great: 
/home/virtualbox/Git/leon/server/src/stt/google-cloud-stt/parser.js
  3:17  error  Unable to resolve path to module '@google-cloud/speech'  import/no-unresolved
  3:17  error  Missing file extension for "@google-cloud/speech"        import/extensions
/home/virtualbox/Git/leon/server/src/tts/google-cloud-tts/synthesizer.js
  3:17  error  Unable to resolve path to module '@google-cloud/text-to-speech'  import/no-unresolved
  3:17  error  Missing file extension for "@google-cloud/text-to-speech"        import/extensions
✖ 4 problems (4 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 lint: `babel-node scripts/lint.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/virtualbox/.npm/_logs/2020-04-17T21_54_00_852Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 build: `npm run lint && npm run build:app && npm run build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/virtualbox/.npm/_logs/2020-04-17T21_54_00_865Z-debug.log

**Comment by FloksyYT** [comment]
I've forgot to say that is make the command "npm start" fail too.
Here is the execution of this one :

virtualbox@VirtualBox-Ubuntu:~/Git/leon$ npm start
\> leon@1.0.0-beta.2 start /home/virtualbox/Git/leon
\> cross-env LEON_NODE_ENV=production node ./server/dist/index.js

internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '/home/virtualbox/Git/leon/server/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/virtualbox/.npm/_logs/2020-04-17T21_55_38_485Z-debug.log

**Comment by FloksyYT** [comment]
### Specs

- Leon version: **Copied from Git, 2 days ago**
- OS (or browser) version: **Ubuntu 18.04.4 LTS** & **Firefox 75.0**
- Node.js version: **13.13.0**
- Complete "npm run check" output: **Last green message : "✔ Hooray! Leon can run correctly"**

**Comment by FSIPower** [comment]
Hi,
Had the same issue, tried a npm update and then run again npm install and npm run build.
It is now working well.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
