### ISSUE TITLE
Missing python module

### ISSUE THREAD

**Issue by ThatDamGuy** [leon-ai/leon#179]
- Leon version: 1.0.0
- OS (or browser) version: Debian 10
- Node.js version: 10.15.2
- Complete "npm run check" output:
> leon@1.0.0-beta.2 check /home/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.2

➡ /bin/sh -c npm --version
✔ 5.8.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.10

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/home/leon/bridges/python/utils.py", line 10, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'

➡ Classifier state
✖ Classifier not found or broken. Try to generate a new one: "npm run train expressions"

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✖ Please fix the errors above
###
I just tried an rpm run check, but it seems I miss some python module called "tinydb". However I couldn't find any reference to this module in the installation guide, and installing it using pip doesn't change anything.

**Comment by louistiti** [comment]
Hello @ThatDamGuy,

Thanks for opening this issue.

Please take a look at the following ones: https://github.com/leon-ai/leon/issues/7 and https://github.com/leon-ai/leon/issues/98.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
