### ISSUE TITLE
Leon prompting that python on pipenv is not version 3.6.x when running 'npm run check' but it is!

### ISSUE THREAD

**Issue by machadorafa** [leon-ai/leon#180]
### Specs

- Leon version: v1.0.0-beta.2
- OS (or browser) version: Ubuntu 19.10
- Node.js version: v10.15.2
- Complete "npm run check" output:

➜ npm run check              
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> leon@1.0.0-beta.2 check /home/rmachado/Projects/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.2

➡ /bin/sh -c npm --version
✔ 5.8.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/rmachado/Projects/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✖ 
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 82, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✖ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✖ Please fix the errors above

### Expected Behavior

npm run check is prompting that pipenv python version is not 3.6.x, but
when running `pipenv run python -V`
I get the following:

> Loading .env environment variables…
> Python 3.6.10 :: Anaconda, Inc.

Even downgraded the system python3 to version 3.6.10 as mentioned on #179 
`python3 -V` prompts:

> Python 3.6.10 :: Anaconda, Inc.

but it gets the same error

### Actual Behavior

Leon prompting that python on pipenv is not version 3.6.x but it is!

**Comment by machadorafa** [comment]
I ran `npm run build` and `npm run start` and everything went correctly. The bug must be happening only on `npm run check` prompting wrongly.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
