### ISSUE TITLE
npm WARN package.json@1.0.0 No repository field.       and       missing script: start

### ISSUE THREAD

**Issue by Bolobos** [leon-ai/leon#182]
Hello,
I'm new to programming and wanted to know why when I enter `npm install` I find `npm WARN package.json@1.0.0 No repository field.` when I checked that there is a repository in package.json that it is there.
Then when I `npm start`, I get the answer `npm ERR! missing script: start` when start is specified in package.json. It's the same error message when I enter `npm run check` -> I find  `npm ERR! missing script: check` ...
Thank you in advance.

**Comment by TheFehr** [comment]
Are you sure you are executing those command in the correct directory? What os are you on? You can checj with `ls` (`dir` for windows) if you can actually see the package.json in the current directory.

**Comment by Bolobos** [comment]
Thank you but I have find an answer to my question. I hadn't installed it properly.
