### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by hzllo1** [leon-ai/leon#184]
### Question
when i do npm install this is what i get, what should i do?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 preinstall: `node scripts/setup/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pable\AppData\Roaming\npm-cache\_logs\2020-05-06T15_40_07_028Z-debug.log

**Comment by Bolobos** [comment]
https://github.com/leon-ai/leon/issues/171#issuecomment-602085631 
For me, it's work.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
