### ISSUE TITLE
SOS Help me

### ISSUE THREAD

**Issue by Marucss** [leon-ai/leon#186]
![leon](https://user-images.githubusercontent.com/39643902/82571237-31a9a580-9b72-11ea-93c3-1360ae2f9678.png)

And  here is the log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle leon@1.0.0-beta.3~prestart: leon@1.0.0-beta.3
6 info lifecycle leon@1.0.0-beta.3~start: leon@1.0.0-beta.3
7 verbose lifecycle leon@1.0.0-beta.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle leon@1.0.0-beta.3~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/badboy17/leon/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/root/.local/bin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle leon@1.0.0-beta.3~start: CWD: /home/badboy17/leon
10 silly lifecycle leon@1.0.0-beta.3~start: Args: [ '-c',
10 silly lifecycle   'cross-env LEON_NODE_ENV=production node ./server/dist/index.js' ]
11 silly lifecycle leon@1.0.0-beta.3~start: Returned: code: 1  signal: null
12 info lifecycle leon@1.0.0-beta.3~start: Failed to exec start script
13 verbose stack Error: leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid leon@1.0.0-beta.3
15 verbose cwd /home/badboy17/leon
16 verbose Linux 5.5.0-1parrot1-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
22 error Exit status 1
23 error Failed at the leon@1.0.0-beta.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Tetsujinfr** [comment]
can you rather copy the lines like those in your screenshot but make sure to include  a bit more lines, I suspect the first error appears earlier in the install process (please do not copy everything neither, just from a few lines before you spot the first red error message). That may help debug your issue. I do not find the log particularly useful (I have issues to install this too and the log gives less details than the outputs from the install process).

**Comment by jottenwa** [comment]
I am having this same issue and it is so frustrating. Spent over 8 hours trying to reinstall and rebuild everything.  Please help.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
