### ISSUE TITLE
Close Pls

### ISSUE THREAD

**Issue by tope951** [leon-ai/leon#188]
i have installed Pythons 3.8, Nodejs 14, Pipenv and Npm but i can't npm run check & npm install

![lvWXyDzmTN2srTRnnffLzQ](https://user-images.githubusercontent.com/51678715/85930910-77b7fe80-b8c0-11ea-922d-736b7b298ca9.png)

**Comment by OoLunar** [comment]
Update your Python, that'll probably help

**Comment by tope951** [comment]
i have pythons 3.8 this is the problemes ?

**Comment by facorazza** [comment]
> i have pythons 3.8 this is the problemes ?

What do you think?

**Comment by OoLunar** [comment]
Seeing as how the error says to downgrade your Python version, yea I'd think so.

**Comment by facorazza** [comment]
I am hardly able to read the error

**Comment by tope951** [comment]
Pythons 3.6 is good ?

**Comment by facorazza** [comment]
I think we can close this

**Comment by louistiti** [comment]
Hello @tope951,

Please try to pull Leon from the `develop` branch and retry.

Let us know if that helps.

**Comment by tope951** [comment]
i have new error https://prnt.sc/t9at05

**Comment by tope951** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/51678715/86245133-58172380-bba9-11ea-8b7e-893e58260768.png)

**Comment by Paul-Michaud** [comment]
You need to install tinydb module for python : 
```bash
pip3 install tinydb
```

**Comment by tope951** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/51678715/86254304-e98c9280-bbb5-11ea-8e74-decaa7638cb3.png)
nop

**Comment by tope951** [comment]
??

**Comment by facorazza** [comment]
Google is your friend

**Comment by tope951** [comment]
Wtf man

![Screenshot_1](https://user-images.githubusercontent.com/51678715/86387801-04cdcf80-bc94-11ea-8d76-f8224078de52.png)

**Comment by HarshRangwala** [comment]
@tope951 Hey, let me know how did you solve this error?!!

**Comment by tope951** [comment]
I still haven't resolved them ....

**Comment by OoLunar** [comment]
Have you checked if you have virtualenv installed?

**Comment by HarshRangwala** [comment]
Hey, By the way it worked for me. What I did was just downloaded Python 3.6 because it wasnt working with the 3.7+ versions. I hope this helps.
But for some reason the voice input/output does not seem to work. I gave all the permissions necessary but still it wont work. Anyone noticed that?

**Comment by pupperr** [comment]
same voice input/output doesnt work either still looking into why

**Comment by tope951** [comment]
Close pls
