### ISSUE TITLE
Offline Hotword npm command typo and how to manually install deepspeech

### ISSUE THREAD

**Issue by gr01d** [leon-ai/leon#19]
### Documentation Is:
- [x] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Explanation
https://docs.getleon.ai/offline.html#hotword
typo in: npm **install** setup:offline-hotword
must be: npm **run** setup:offline-hotword
### Proposal
Also, how to manually install deepspeech. I cannot let npm download 1.8GB file and just fail because of slow internet connection, I need to download the 1.8GB file using aria2c/wget -c and unpack it to where?
My bandwidth is expensive.

Another question, I have installed python3.7.2 from source (cannot remove it using make uninstall) but leon requires only 3.6.X, so I installed 3.6.8 from source again but pipenv is using 3.7.
I am using Debian, and this broke apt-get, is there any way to make pipenv select 3.6 not 3.7?

**Comment by louistiti** [comment]
Hello @gr01d,

Awesome, thanks for spotting it, this is now fixed https://github.com/leon-ai/docs.getleon.ai/commit/4a5656440d59b054cd7634b8c51c8a32d28c42ac.

Now to reply to your questions:

> How to manually install deepspeech. I cannot let npm download 1.8GB file and just fail because of slow internet connection, I need to download the 1.8GB file using aria2c/wget -c and unpack it to where?

You can take a look on [`scripts/setup-offline/setup-stt.js`](https://github.com/leon-ai/leon/blob/develop/scripts/setup-offline/setup-stt.js). It should be clear enough to understand where and how DeepSpeech is downloaded and installed.

> I have installed python3.7.2 from source (cannot remove it using make uninstall) but leon requires only 3.6.X, so I installed 3.6.8 from source again but pipenv is using 3.7.
> I am using Debian, and this broke apt-get, is there any way to make pipenv select 3.6 not 3.7?

You can check [over here](https://pipenv.readthedocs.io/en/latest/basics/#specifying-versions-of-python). But I guess for that it'll be better you [ask them](https://github.com/pypa/pipenv/issues) directly.

**Comment by louistiti** [comment]
I'll close this issue. Feel free to open it again if you think it's necessary.
