### ISSUE TITLE
modifier .env et module ?

### ISSUE THREAD

**Issue by flint006** [leon-ai/leon#191]
Bonjour, 

Nouveau sur leon et sur l'utilisation d'un assistant personnel , j'ai réussi a tout installer et a le faire marchés en US 

Je recherche la fonction pour modifier le fichier .env pour modifier la langue vers FR ? Ainsi que les autres fonctions du .env 

Je souhaiterais savoir aussi si l'on peut modifier un module d’expression FR en changeant ou en ajoutant du texte dedans ?

Sinon existe-t-il un tuto pour créer un module de langage FR pour le faire discuter avec nos propres mots ? 

Je vous remercie par avance pour le temps passé et l'aide apporté

**Comment by Divlo** [comment]
Bonjour @flint006,

Il est préférable de parler en Anglais dans les issues GitHub.
> Je recherche la fonction pour modifier le fichier .env pour modifier la langue vers FR ? Ainsi que les autres fonctions du .env

Au moment d'installer Leon, il faut copier le contenu du fichier `.env.sample` dans un fichier `.env` et c'est dans ce nouveau fichier que vous allez pouvoir modifier les variables d'environnements, notamment la langue.
Pour modifier la langue de Leon, vous pouvez chercher la variable `LEON_LANG` et la mettre à `fr-FR`, par défaut la variable est comme ça : `LEON_LANG=en-US`.

> Je souhaiterais savoir aussi si l'on peut modifier un module d’expression FR en changeant ou en ajoutant du texte dedans ?

Oui, vous pouvez voir les traductions, dans les fichiers `data/answers/fr.json` et  `data/expressions/fr.json`  de chaque module/package.

> Sinon existe-t-il un tuto pour créer un module de langage FR pour le faire discuter avec nos propres mots ?

La documentation est faîte pour ça! https://docs.getleon.ai/

> Je vous remercie par avance pour le temps passé et l'aide apporté

Merci pour votre intérêt pour Leon, en espérant avoir répondu à vos questions.
Je ferme l'issue, mais n'hésitez pas à réouvrir (cette fois-çi en Anglais :laughing:), si vous avez d'autres questions!
