### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by pupperr** [leon-ai/leon#194]
### Specs

- Leon version: Latest
- OS (or browser) version: Windows
- Node.js version: v14
- Complete "npm run check" output: normal
- (if using Docker) Complete "npm run docker:check" output: usual
- (optional) Leon package version: latest

### Expected Behavior
should work on windows usually

### Actual Behavior
does not load on windows could be due to so many outdated node modules

### How Do We Reproduce?

I think maybe update all of the modules, I can try to do it later maybe

### Extra (like a sample repo to reproduce the issue, etc.)

probs will help update the modules though, just try to run on the latest version of windows with node v14 and the latest version of npm and all of them

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
