### ISSUE TITLE
Improve NLU for more detailed queries

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#2]
Be able to subtract a type of entity from a query. Such as date, number, location, etc.

If it uses a tiers but Node.js, it should operate from the core and send the result object to modules via the child process parameters.
Otherwise, it should fully be implemented in the core itself.

I noted some following leads in [this Trello card](https://trello.com/c/xrofGezn/150-%F0%9F%94%A7-improve-nlu-for-more-detailed-queries).

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 Improve NLU for more detailed queries](https://trello.com/c/xrofGezn/150-%F0%9F%94%A7-improve-nlu-for-more-detailed-queries)

**Comment by Immortalin** [comment]
Rasa integration?

**Comment by louistiti** [comment]
Hello @Immortalin,

I do not plan to have a Rasa integration yet. But it does not mean I will not in the future.

**Comment by Immortalin** [comment]
If will make slot filling etc. easier as you can just delegate everything

**Comment by ftyers** [comment]
In any case if you do decide to use Rasa, please make it modular, it seems that Rasa does not have any serious support for non-trivial morphology.

**Comment by Immortalin** [comment]
Snips-NLU perhaps?

**Comment by ftyers** [comment]
@Immortalin looks like snips [doesn't support languages](https://snips-nlu.readthedocs.io/en/latest/languages.html) with substantial morphology and morphophonology either.

**Comment by louistiti** [comment]
Quick update for this topic:

I'm working under the [nlu-improvement branch](https://github.com/leon-ai/leon/tree/nlu-improvement).

Leon is able to find several entities from a query thanks to [node-nlp](https://github.com/axa-group/nlp.js).

The Is It Down module is now using these entities instead of a custom regex to find the domain names (related to https://github.com/leon-ai/leon/issues/51).

I'll be working on the [Trends package](https://github.com/leon-ai/leon/issues/3) now to validate the feature, but I'll also need to dig into other topics regarding that improvement (such as locations and slot filling).

I'm note sure that will be in the `1.0.0-beta.2` release, but still, here is what may plan:
- [📝 Take a look at how to implement location entities with slot filling or for other purposes such as "add X in Y list"](https://trello.com/c/K2Y6r1VU/238-%F0%9F%93%9D-100-beta2-take-a-look-at-how-to-implement-location-entities-with-slot-filling-or-for-other-purposes-such-as-add-x-in-y-list)
- [✨ Dedicated modules flow](https://trello.com/c/iRTlyUB5/231-%E2%9C%A8-dedicated-modules-flow)

**Comment by louistiti** [comment]
I finished this improvement. It'll be released in the `1.0.0-beta.2` version (cf. https://github.com/leon-ai/leon/commit/82ebbee568d1b8ccfacbe2a74e50afb01e9d9577).

**Comment by louistiti** [comment]
The docs according to those changes has been published. Most of the essentials information can be found in [this part](https://docs.getleon.ai/packages-modules.html#query-object-entities).

**Comment by Becker-Asano** [comment]
@louistiti , the "this part" link in the previous post resolves to a 404 here. Could you fix this please? Thank you!

**Comment by louistiti** [comment]
> @louistiti , the "this part" link in the previous post resolves to a 404 here. Could you fix this please? Thank you!

Hi, sure, here you are: https://docs.getleon.ai/packages-modules#entities.
