### ISSUE TITLE
Multiple issues with arch linux

### ISSUE THREAD

**Issue by pshobowale** [leon-ai/leon#200]
First of all thank you for this interesting project (: 

There are some issues if you want to test this on arch:
1) the arch version of node is 14+, which breaks deepspeech
2) the hotword setup is dependend on apt-get, while arch uses pacman
3) LC_ALL doesnt work with C.UTF8

Workarrounds:
1) use nvm to downgrade node to 12.x   https://wiki.archlinux.org/index.php/Node.js#Alternate_installations
2) use "pacman -S fmt sox"
    comment out "await.checkos()" and "await.setupHotword" from script/setup_offline/setup_offline.js
    use npm run setup:offline to install hotwords and offline stt/tts
    don't forget to change the conf in .env (LEON_STT=true and LEON_TTS=true)
3) use LC_ALL=en_US.UTF-8 in .env
           LANG=en_US.UTF-8

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
