### ISSUE TITLE
Leon not loading

### ISSUE THREAD

**Issue by marzar325** [leon-ai/leon#205]
I am using Leon on windows
I have fixed the issue with the .env file

Leon is not fully loading I just get suck with the buffering screen.

**Comment by pupperr** [comment]
it seems that leon is currently broken on Windows, i may try to see if i can find a fix. if i do, ill open a pull request and reply back to you.

**Comment by pupperr** [comment]
Have you configured the .env file?

**Comment by Divlo** [comment]
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
