### ISSUE TITLE
Deepspeech Parser Not Found

### ISSUE THREAD

**Issue by jottenwa** [leon-ai/leon#207]
Hi All, not sure if this is active, but I have had this problem for a long time:

When I run npm run check - I get no errors and I get the "Leon can run correctly"

When I run npm run start - this is the error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-05T04_54_26_517Z-debug.log

and here is the full log report:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle leon@1.0.0-beta.3~prestart: leon@1.0.0-beta.3
6 info lifecycle leon@1.0.0-beta.3~start: leon@1.0.0-beta.3
7 verbose lifecycle leon@1.0.0-beta.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle leon@1.0.0-beta.3~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/Smart/leon/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle leon@1.0.0-beta.3~start: CWD: /Smart/leon
10 silly lifecycle leon@1.0.0-beta.3~start: Args: [ '-c',
10 silly lifecycle   'cross-env LEON_NODE_ENV=production node ./server/dist/index.js' ]
11 silly lifecycle leon@1.0.0-beta.3~start: Returned: code: 1  signal: null
12 info lifecycle leon@1.0.0-beta.3~start: Failed to exec start script
13 verbose stack Error: leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid leon@1.0.0-beta.3
15 verbose cwd /Smart/leon
16 verbose Linux 5.4.0-52-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
22 error Exit status 1
23 error Failed at the leon@1.0.0-beta.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~

I have uninstalled and reinstalled both the GPU and the CPU versions of Deepspeech and am still getting this error
Please help :( I have been trying to do this for 2 months and over 20 hours building and failing....

**Comment by nealdotpy** [comment]
**Arch Linux**

After tooling around in the Issues and in my system, I ran an offline install as per #200, then installed `python36` from the AUR. Then did some sym-linking (instead of adding random dir's to my PATH) to get the pipenv working with the project. Then, nothing was installed via `pipenv` using the Pipfile, so I had to do that manually as well--all while ensuring checks are passed. Then, after the checks said all good, the build fails because of the linter. 

I skip linting all-together since it errors out on the two commented out lines specified in #200 and the google modules I'm not using.

So I build :server/:app and finally it say's everything is ready to go!

I send my first message. Then, bam!

```
✖ No DeepSpeech library found:
GPU: Error: Cannot find module 'deepspeech-gpu'
Require stack:
- /home/neal/usr/proj/leon/server/dist/stt/deepspeech/parser.js
- /home/neal/usr/proj/leon/server/dist/stt/stt.js
- /home/neal/usr/proj/leon/server/dist/core/server.js
- /home/neal/usr/proj/leon/server/dist/index.js
CPU: Error: Cannot find module '/home/neal/usr/proj/leon/node_modules/deepspeech/lib/binding/v0.4.1/linux-x64/node-v72/deepspeech.node'
Require stack:
- /home/neal/usr/proj/leon/node_modules/deepspeech/index.js
- /home/neal/usr/proj/leon/server/dist/stt/deepspeech/parser.js
- /home/neal/usr/proj/leon/server/dist/stt/stt.js
- /home/neal/usr/proj/leon/server/dist/core/server.js
- /home/neal/usr/proj/leon/server/dist/index.js
➡ Loading model from file bin/deepspeech/output_graph.pb...
(node:1874848) UnhandledPromiseRejectionWarning: TypeError: DeepSpeech.Model is not a constructor
    at Object.parser.init (/home/neal/usr/proj/leon/server/dist/stt/deepspeech/parser.js:107:13)
    at Stt.init (/home/neal/usr/proj/leon/server/dist/stt/stt.js:55:27)
    at Socket.<anonymous> (/home/neal/usr/proj/leon/server/dist/core/server.js:193:17)
    at Socket.emit (events.js:314:20)
    at /home/neal/usr/proj/leon/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:1874848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1874848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
