### ISSUE TITLE
Build fail  

### ISSUE THREAD

**Issue by nto4** [leon-ai/leon#21]
npm-debug.log and  terminal std err output why  cant build this and how can ı fix ?

https://pastebin.com/JwAkidhG

https://pastebin.com/raw/Uz4HcV63

**Comment by louistiti** [comment]
Hello @nto4,

Thanks for your issue. It seems you are using npm `3.5.2`, please try with a version up or equal to 5 as mentioned in the prerequisites.

**Comment by nto4** [comment]
how can ı activate speaking mode on local host ?

**Comment by louistiti** [comment]
You are welcome.

It is explained [here](https://docs.getleon.ai/configuration.html#voice).

I'll close it as the original issue has been replied.
