### ISSUE TITLE
TTS and STT not working although I set them both to true

### ISSUE THREAD

**Issue by Architsakri** [leon-ai/leon#212]
When I run it runs smoothly but then it says:

.: INITIALIZATION:

✔ STT disabled
✔ TTS disabled

I enabled this in the .env file yet it is still not working. How do we fix this?

**Comment by louistiti** [comment]
Hello @Architsakri,

Please provide more information via the `npm run check` command, as per requested in the issue template.

**Comment by louistiti** [comment]
I close this as no answer has been provided. Feel free to reopen.
