### ISSUE TITLE
Leon hotword not working

### ISSUE THREAD

**Issue by Architsakri** [leon-ai/leon#213]
I am not able to use the Leon hot word at all so I cannot say "Leon" to do something I manually have to press the button

**Comment by louistiti** [comment]
Hello @Architsakri 👋,

Thanks for opening this issue. Could you please try with the `develop` branch instead and let us know about the result?

Also, please provide more details as per requested in the issue template.

**Comment by louistiti** [comment]
I close this as no answer has been provided. Feel free to reopen.

**Comment by htomi** [comment]
I also had this problem. Using the button everything is ok. Saying "Leon" nothing happens.
I am on the dev branch.

Hotword console log:
> _Connected to the server
> Waiting for hotword..._

Leon server log:
> _Connected
> Type: hotword-node
> Socket id: F3-ojBZYyocdvQ6fAAAd_

The web browser shows only 1 socket connection (webapp). Should I see another socket connection for hotword?
