### ISSUE TITLE
Have I been pwned not working

### ISSUE THREAD

**Issue by piyush14298** [leon-ai/leon#214]
### Specs

Everything is up to date at the time of reporting

### Expected Behavior

Should return if the given email id has been pwned or not

### Actual Behavior

Since the v2 of the API for have I been pwned has been discontinued, support for v3 needs to be added which requires an additional key in the header.

### How Do We Reproduce?

Check for an email ID which has been pwned.

**Comment by louistiti** [comment]
Hi @piyush14298 :wave:,

I know it has been a while. I'm finally coming back on track for Leon!

Leon now supports the API v3. Commit: https://github.com/leon-ai/leon/commit/0ca89fe32d51c80cec5f9446acf14990390a5917.

Feel free to reopen this issue if you see any trouble.
