### ISSUE TITLE
Python version bug and a few more...

### ISSUE THREAD

**Issue by Diakoreftis** [leon-ai/leon#215]
### Specs

- Leon version:
- OS (or browser) version:
- Node.js version:
- Complete "npm run check" output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Expected Behavior

Hey people Merry Christmas and happy new year!!!
As i dont find any solution to this issue from other posts i will reply this again because i think im kinda lost to this as im working days on it while i am not expert to fixing linux problems...(i dont know how to give more orders for auto repair)
As you see in the report i change the version to python and set the basic to 3.6 but without any result the problem persist and i need a few step by step commands if you dont mind...it will really help....thanks.

### Actual Behavior

 leon@1.0.0-beta.2 check /home/imaster/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v15.3.0

➡ /bin/sh -c npm --version
✔ 6.14.8

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2020.11.4

➡ /bin/sh -c pipenv --where
✔ /home/imaster/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✖ Python 3.8.6
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads                                                     

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json                                                    
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json                             
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)  
Warning: Your Pipfile requires python_version 3.6, but you are using 3.8.6 (/home/i/leon/b/python/.venv/bin/python).                      
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.                                                             
  $ pipenv check will surely fail.                                   
Traceback (most recent call last):                                   
  File "bridges/python/main.py", line 4, in <module>                 
    import utils                                                     
  File "/home/imaster/leon/bridges/python/utils.py", line 10, in <module>                                                                 
    from tinydb import TinyDB, Query, operations                     
ModuleNotFoundError: No module named 'tinydb'                        

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
✔ Found DeepSpeech language model at bin/deepspeech/lm.binary

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✖ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
✔ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
✔ Offline speech-to-text

✖ Please fix the errors above

**Comment by rtteamjiri** [comment]
Hi,
I think more people share this problem. I look forward to your reply.

**Comment by louistiti** [comment]
Hello @Diakoreftis 👋,

Thanks for opening this issue. Could you please try with the develop branch instead and let us know about the result?

**Comment by louistiti** [comment]
I close this as no answer has been provided. Feel free to reopen.
