### ISSUE TITLE
does not ompile/build at all

### ISSUE THREAD

**Issue by targor** [leon-ai/leon#217]
### Specs

- Leon version: latest
- OS (or browser) version: windows 10 pro
- Node.js version: 14.15.5
- Complete "npm run check" output: no use, becuase before i can check, npm install should run trough wich does not
- (optional) Leon package version: ? downloaded lates repo master

### Expected Behavior
should build with npm install

### Actual Behavior

does not

### How Do We Reproduce?
install all dependencies, open a commandline, go to the leon repo folder and type npm install

### Extra (like a sample repo to reproduce the issue, etc.)

here is my cmd output:

E:\leon\leon>npm install
npm ERR! code 1
npm ERR! path E:\leon\leon\node_modules\deepspeech
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\leon\leon\node_modules\deepspeech\lib\binding\v0.4.1\win32-ia32\node-v83\deepspeech.node --module_name=deepspeech --module_path=E:\leon\leon\node_modules\deepspeech\lib\binding\v0.4.1\win32-ia32\node-v83 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.12.0
npm ERR! node-pre-gyp info using node@14.15.5 | win32 | ia32
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "E:\leon\leon\node_modules\deepspeech\lib\binding\v0.4.1\win32-ia32\node-v83\deepspeech.node" (not found)
npm ERR! node-pre-gyp http GET https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.v1.0.0-warpctc.arm/artifacts/public/v0.4.1/Release/deepspeech-v0.4.1-node-v83-win32-ia32.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for deepspeech@0.4.1 and node@14.15.5 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND index.taskcluster.net
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.5 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.5 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\Python39\python.exe"
npm ERR! gyp info find VS using VS2019 (16.8.31005.135) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\jc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'E:\\leon\\leon\\node_modules\\deepspeech\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\jc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\jc\\AppData\\Local\\node-gyp\\Cache\\14.15.5\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jc\\AppData\\Local\\node-gyp\\Cache\\14.15.5',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.5\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=E:\\leon\\leon\\node_modules\\deepspeech',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'E:\\leon\\leon\\node_modules\\deepspeech\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: E:\leon\leon\node_modules\deepspeech) while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\jc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\leon\\leon\\node_modules\\deepspeech\\lib\\binding\\v0.4.1\\win32-ia32\\node-v83\\deepspeech.node" "--module_name=deepspeech" "--module_path=E:\\leon\\leon\\node_modules\\deepspeech\\lib\\binding\\v0.4.1\\win32-ia32\\node-v83" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
npm ERR! gyp ERR! cwd E:\leon\leon\node_modules\deepspeech
npm ERR! gyp ERR! node -v v14.15.5
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\leon\leon\node_modules\deepspeech\lib\binding\v0.4.1\win32-ia32\node-v83\deepspeech.node --module_name=deepspeech --module_path=E:\leon\leon\node_modules\deepspeech\lib\binding\v0.4.1\win32-ia32\node-v83 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\leon\leon\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\leon\\leon\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd E:\leon\leon\node_modules\deepspeech
npm ERR! node-pre-gyp ERR! node -v v14.15.5
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.12.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jc\AppData\Local\npm-cache\_logs\2021-02-11T20_53_33_888Z-debug.log

E:\leon\leon>

**Comment by liangjihua** [comment]
I had the same error on ArchLinux.
node v12.21.0 
npm 7.6.1
python 3.9.2
pipenv 2020.11.15

**Comment by booleans-oss** [comment]
You need node-gyp in order to be able to install the dependencies (c.f.: [https://github.com/nodejs/node-gyp#installation](https://github.com/nodejs/node-gyp#installation))

**Comment by louistiti** [comment]
Hello @targor 👋,

Thanks for opening this issue. Sorry for the late reply, I'm coming back to Leon recently.

Could you please try with the `develop` branch instead and let us know about the result?

**Comment by louistiti** [comment]
Please try with the `develop` branch. Feel free to reopen it.

**Comment by liangjihua** [comment]
Hello @louistiti 

I have tried the `develop` branch, still not work.
I encountered a series of dependency problems, a lot of ` Cannot find module 'xxx'`, such as `babel-node`.  And After I installed `babel`, other problems appeared again...
I'm not familiar with `JS` and `node`, basically I followed the official documentation to install, on a clean ArchLinux.   Is there some inexplicit requirements that `leon` needs?

**Comment by louistiti** [comment]
Hello @liangjihua :wave:,

Thanks for saying. Please open a new issue by specifying the version that is `package.json` and by sharing your `npm run check` output.

**Comment by liangjihua** [comment]
I found the real cause was `OOM`, `npm install` failed actually. Increase the virtual machine memory to 4GB and it works.

Thanks @louistiti

**Comment by louistiti** [comment]
Happy to see that you made it working! And thanks for sharing your solution :+1:
