### ISSUE TITLE
DeepSpeech model should be v0.4.1

### ISSUE THREAD

**Issue by lissyx** [leon-ai/leon#22]
Please switch to DeepSpeech v0.4.1 models, the released v0.4.0 was a bogus one: https://github.com/mozilla/DeepSpeech/releases/tag/v0.4.1

**Comment by louistiti** [comment]
Hello @lissyx,

Thanks for your issue. However, I do not plan to upgrade DeepSpeech now. I prefer to wait for a while until they release a higher version.

**Comment by lissyx** [comment]
@louistiti Please, this is not "for fun", 0.4.0 was a **broken** model.

**Comment by lissyx** [comment]
@louistiti As you can see on https://github.com/mozilla/DeepSpeech/releases/tag/v0.4.0:
```
The incorrect model was uploaded this will be fixed in 0.4.1
```

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⬆️ [1.0.0-beta.1] DeepSpeech >= 0.4.1](https://trello.com/c/VKpm1c01/222-%E2%AC%86%EF%B8%8F-100-beta1-deepspeech-041)

**Comment by louistiti** [comment]
Oh, nice spot! Thanks for saying.

It'll be fixed for the next release.

**Comment by lissyx** [comment]
Looks like you should also change those values: https://github.com/leon-ai/leon/blob/develop/server/src/stt/deepspeech/parser.js#L37-L45 check here https://github.com/mozilla/DeepSpeech/blob/master/native_client/javascript/client.js#L17-L21

**Comment by louistiti** [comment]
Alright, I updated DeepSpeech from the `0.4.0` version to the `0.4.1`.

https://github.com/leon-ai/leon/commit/194abd64d7cd4e3fb0f279eef8423ff7a300a41b

**Comment by kdavis-mozilla** [comment]
PS: Deep Speech 0.6.1 is out!
