### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rtteamjiri** [leon-ai/leon#225]
Greetings to the community and thank you for a great OS project.

Can someone please advise me how to start translating Leon? I want to translate Leon into Czech and unfortunately I don't know where to start. Thank you for any advice.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Hello @rtteamjiri,

Thanks for opening this issue.

Today to support another language we need to:
1. Translate every `expression` and `answer` of each module.
2. Add a voice to each of the `synthesizer` found in their respective folder inside [server/src/tts](https://github.com/leon-ai/leon/tree/develop/server/src/tts).
3. Ensure the language is supported for each `parser` found in their respective folder in [server/src/stt](https://github.com/leon-ai/leon/tree/develop/server/src/stt).

However, I don't recommend working on it for the moment as I plan to try a way to support multiple languages in a more scalable way. Please see [this card from the roadmap](https://trello.com/c/cFEwGXuw/327-%E2%9C%A8-100-beta6-languages-scaling) for more details.

**Comment by louistiti** [comment]
Closing this issue. Feel free to open it if needed.
