### ISSUE TITLE
While running npm run build i am getting error ... Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet 

### ISSUE THREAD

**Issue by keinagae** [leon-ai/leon#226]
When i try to build leon to run it build server successfully but for app i am getting forllowing exception 

UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: vite --config app/vite.config.js build
error during build:
Error: Transform failed with 9 errors:
assets/vendor.519a11cb.js:3997:6: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/vendor.519a11cb.js:4172:6: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/vendor.519a11cb.js:4187:22: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is 
not supported yet
assets/vendor.519a11cb.js:4281:6: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
assets/vendor.519a11cb.js:5121:6: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet

### Specs

- Leon version: leon@1.0.0-beta.4
- OS (or browser) version: Windows 
- Node.js version: v14.15.3
- Complete "npm run check" output:
- (if using Docker) Complete "npm run docker:check" output: ✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
- (optional) Leon package version:

**Comment by louistiti** [comment]
Hello @keinagae 👋,

Thanks for opening this issue.

Please provide the **complete output** of the `npm run check` (or `npm run docker:check`) command as specified in the issue template.

**Comment by keinagae** [comment]
> leon@1.0.0-beta.4 check D:\work\javascript\leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ node --version
✔ v14.15.3

➡ npm --version
✔ 6.14.9

➡ pipenv --version        
✔ pipenv, version 2020.6.2

➡ pipenv --where
✔ D:\work\javascript\leon\bridges\python

➡ pipenv run python --version
✔ Python 3.9.0

➡ pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 62, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
✔ Configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured



this is full output of npm run check

I ran npm run dev for app and server it worked but then on each command it was say package broken

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.4] Hunt cross OSes setup bugs](https://trello.com/c/eFuM9mvQ/334-%F0%9F%90%9E-100-beta4-hunt-cross-oses-setup-bugs)

**Comment by louistiti** [comment]
Thanks for sharing.

As I started to work recently again on Leon, I plan to hunt the different bugs across OSes, Windows included. I added your case to the roadmap.

**Comment by keinagae** [comment]
So right know i cant test it? and when more thing in dev mode it only says hi or time to sleep or module broken any idea?

**Comment by louistiti** [comment]
I just tried a complete new Windows virtual machine as you can see in the screenshot, and everything worked smoothly here. Also tried with your Node.js `14.15.3` version.

To move further, could you please:

1. Run `npm cache clean`
2. Delete your `node_modules` folder
3. Run `npm install`
4. Run `npm run build`
5. Then let us know how it goes

If the steps above don't work, please:
- Share your terminal output when it says that the module is broken

![Screen Capture_20210319165720](https://user-images.githubusercontent.com/1731544/111755773-6f7f7380-88d4-11eb-9b10-ec04dfe7c7be.png)

**Comment by louistiti** [comment]
I close this issue as no answer has been provided. Feel free to reopen it.
