### ISSUE TITLE
i have no clue what to do this goes every time i try to install npm :error leon@1.0.0-beta.2 preinstall:

### ISSUE THREAD

**Issue by Fish1rs** [leon-ai/leon#228]
i'm not the smartest or know how to code so all i keep getting is this error i'm using windows
23 error code ELIFECYCLE
24 error errno 1
25 error leon@1.0.0-beta.2 preinstall: `node scripts/setup/preinstall.js`
25 error Exit status 1
26 error Failed at the leon@1.0.0-beta.2 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by louistiti** [comment]
Hello @Fish1rs :wave:,

Thanks for opening this issue. Could you please try with the `develop` branch instead and let us know about the result?

**Comment by louistiti** [comment]
I close this as no answer has been provided. Feel free to reopen.
