### ISSUE TITLE
Lock node version and pipfile version?

### ISSUE THREAD

**Issue by arlyxiao** [leon-ai/leon#229]
### Feature Use Case
node version: v15.3.0
when run node install and npm run setup:offline
These files would be conflict.
```
modified:   package-lock.json
modified:   scripts/setup-offline/setup-hotword.js
modified:   scripts/setup/setup-python-packages.js
```

**Comment by louistiti** [comment]
Hello @arlyxiao :wave:,

Thanks for suggesting this feature! This is actually a tricky one as I believe it'd be better to not restrict Leon to one single Node.js and Python version.
Also, the future CLI will help here as it'll not `git clone` the repo, and maybe it'll always grab the latest LTS Node.js version for you, let's see.

However, you made me think that before today, there were no way to directly stop the install if the minimum Node.js requirements were not respected. So I just made the changes, thanks! See more here: https://github.com/leon-ai/leon/commit/05a6c6620561ecace03cab6d3354c56c41967044.

Please feel free to tell me more about your thoughts regarding this feature request.

**Comment by arlyxiao** [comment]
The solution is nice. @louistiti
