### ISSUE TITLE
One core to rule them all

### ISSUE THREAD

**Issue by Xavier-Brinon** [leon-ai/leon#23]
### Documentation Is:
- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [X] Not Sure?

### Explanation

In the readme we can read the below: 
2. With this generic structure, everyone can create his own modules and share them with others. Therefore there is only one core (to govern all of them).

### Proposal

The lord of the cores would require this to be written as proposed: 
2. With this generic structure, everyone can create his own modules and share them with others. Therefore there is only one core (to rule them all).

**Comment by louistiti** [comment]
Hello @Xavier-Brinon,

Thanks, I love it! I changed it in the readme and the documentation:

- https://github.com/leon-ai/leon/commit/c74dda4cb9acc78de143ae01fdc6b4ef0a5ec3ef
- https://github.com/leon-ai/docs.getleon.ai/commit/11b0aa5e4aa0c932361344357fe72391c0c782fb
