### ISSUE TITLE
Catched greeting module error on this.process.stderr always

### ISSUE THREAD

**Issue by arlyxiao** [leon-ai/leon#230]
### Specs

- Leon version: latest develop
- OS (or browser) version: mac os mojave / chrome
- Node.js version: v14.16.0
- Complete "npm run check" output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### npm run check 
```
.: CHECKING :.

➡ node --version
✔ v14.16.0

➡ npm --version
✔ 6.14.11

➡ pipenv --version
✔ pipenv, version 2020.6.2

➡ pipenv --where
✔ /Users/arlyxiao/dev/leon/bridges/python

➡ pipenv run python --version
✔ Python 3.8.3

➡ pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 33, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
✔ Configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
✔ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
```

### Actual Behavior

Sorry, I've got an error with the "Greeting" module of my "Leon" package!
Sorry, I've got an error with the "Greeting" module of my "Leon" package!

### How Do We Reproduce?
Input 'hi' and it will return the error above.

### Extra (like a sample repo to reproduce the issue, etc.)
I tried to comment/remove the code below and let program can be executed on next this.process.stdout.on('end', () => { xxx })
```
this.process.stderr.on('data', (data) => {
  this.talk(`${this.wernicke('random_package_module_errors', '',
    { '%module_name%': moduleName, '%package_name%': packageName })}!`)
  Brain.deleteQueryObjFile(queryObjectPath)
  this.socket.emit('is-typing', false)

  log.title(packageName)
  reject({ type: 'error', obj: new Error(data) })
})
```

the output data is:
```
{"package": "leon", "module": "greeting", "action": "run", "lang": "en", "input": "Hi", "entities": [], "output": {"type": "end", "codes": ["afternoon"], "speech": "Good afternoon!", "options": {}}}
```

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.4] Hunt cross OSes setup bugs](https://trello.com/c/eFuM9mvQ/334-%F0%9F%90%9E-100-beta4-hunt-cross-oses-setup-bugs)

**Comment by louistiti** [comment]
Hello @arlyxiao :wave:,

Thanks for reporting this issue. I'm going to take a look at it before releasing the new version. It'll be part of the cross-platform checking that is in the roadmap.

**Comment by arlyxiao** [comment]
I tried to run the script manually in shell
```
pipenv run python bridges/python/main.py server/src/tmp/1616991215892-09r8.json
```
It would output 
```
{'id': '1616991215892-09r8', 'lang': 'en', 'package': 'leon', 'module': 'greeting', 'action': 'run', 'query': 'Hi', 'entities': []}
```

According to the result, greeting.py has been executed.
However I'm not sure why this.process (brain.js) will catch the error

**Comment by arlyxiao** [comment]
pipenv version is too old.
Fixed this issue by upgrade pipenv with version 2020.11.15
If brew install may be outdated.
Please use pip3 install pipenv
