### ISSUE TITLE
Problems Operation timed out download file from www.festvox.org

### ISSUE THREAD

**Issue by byeblogs** [leon-ai/leon#239]
### FYI
If you have a problem about downloading files **flite-2.1-release.tar.bz2**

you can using this link [https://sources.voidlinux.org/flite-2.1/](https://sources.voidlinux.org/flite-2.1/flite-2.1-release.tar.bz2) instead of http://www.festvox.org/flite/packed/flite-2.1/flite-2.1-release.tar.bz2

**Comment by louistiti** [comment]
Hello @byeblogs :wave:,

Thanks for mentioning that. For the moment it seems the uptime of the festvox.org URL is quite good. A mirror could be added to it. Do you think you can create a PR to fallback to this mirror in case?
