### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by ftyers** [leon-ai/leon#24]
It seems that Leon currently only speaks English (?)

It would be great if the software could support other languages. And do it in a way that is more extensible/linguistically informed than Mycroft.

**Comment by louistiti** [comment]
Hello @ftyers,

Thanks for opening this issue.

Leon supports English but also French. I plan to support other languages in the future, but that's not the priority for now. I let you read [this other issue](https://github.com/leon-ai/leon/issues/8) for your reference.

**Comment by ftyers** [comment]
That's cool, but please when you're designing the system take into account languages with more variation than just English or French, or it will be very hard to change later. e.g. the way Mycroft works with template filling is not extensible to the majority of the languages in the world. So either they just don't support those languages or they have to rewrite the entire software.

**Comment by louistiti** [comment]
Thanks for your suggestions.

I will close this issue as the answer to the original question as been provided.

**Comment by louistiti** [comment]
Thanks for your suggestion.

I will close that issue as the answer has been provided to the original topic.
