### ISSUE TITLE
Problem with the package during postinstall 

### ISSUE THREAD

**Issue by Neyzn** [leon-ai/leon#241]
**Hi, I have a problem, I did the postinstall but I have this error:** 

`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path A:\Lexa\Lexa-Test\leon_copie\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'A:\Lexa\Lexa-Test\leon_copie\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maelo\AppData\Roaming\npm-cache\_logs\2021-04-30T03_25_06_332Z-debug.log`

**log:** 
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose stack Error: ENOENT: no such file or directory, open 'A:\Lexa\Lexa-Test\leon_copie\package.json'
5 verbose cwd A:\Lexa\Lexa-Test\leon_copie
6 verbose Windows_NT 10.0.19042
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
8 verbose node v14.16.1
9 verbose npm  v6.14.12
10 error code ENOENT
11 error syscall open
12 error path A:\Lexa\Lexa-Test\leon_copie\package.json
13 error errno -4058
14 error enoent ENOENT: no such file or directory, open 'A:\Lexa\Lexa-Test\leon_copie\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]
`

**and if I create a package with npm init I get this error:**

`npm ERR! missing script: postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maelo\AppData\Roaming\npm-cache\_logs\2021-04-30T03_32_25_340Z-debug.log`

**log:** 
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'postinstall'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose stack Error: missing script: postinstall
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:382:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd A:\Lexa\Lexa-Test\leon_copie
6 verbose Windows_NT 10.0.19042
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
8 verbose node v14.16.1
9 verbose npm  v6.14.12
10 error missing script: postinstall
11 verbose exit [ 1, true ]
`

**Can you help me?**

**Comment by Neyzn** [comment]
And when I don't do the postinstall and do `npm run check` I get this error: 

```
✖ Error: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "pipenv run python bridges/python/main.py scripts/assets/query-object.json"
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "A:\Lexa\Lexa-Test\leon_copie\bridges\python\utils.py", line 10, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'
```

**Comment by louistiti** [comment]
Hello @Neyzn :wave:,

Thanks for opening this issue. To move forward, please:

- Share the result of the following commands:
```sh
node --version
npm --version
pip --version
pipenv --version
```
- Share the version of your Windows.

**Comment by Neyzn** [comment]
![version](https://user-images.githubusercontent.com/66250607/116714936-88506e00-a9d6-11eb-9236-65b939073570.png)

version of Windows: 20H2
And i don't have package.json

**Comment by louistiti** [comment]
You must have a `package.json` file at the root of the Leon's project that you cloned by doing your `git clone ...` command.

**Comment by Neyzn** [comment]
Oh yes, sorry, I didn't see that.
Version: 1.0.0-beta.2

**Comment by louistiti** [comment]
Please clone with the `develop` branch and let us know how it goes.

**Comment by Neyzn** [comment]
I installed it and when I did an npm run check I got this error: 

`✖ Error: Command failed with exit code 1: pipenv run python bridges/python/main.py scripts/assets/query-object.json
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "A:\Lexa\test\leon\bridges\python\utils.py", line 10, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'`

Don't you have a discord to communicate more easily ?
If yes, here is my discord: Neyzn#0586

**Comment by louistiti** [comment]
There is a pretty new Discord that you can find in the README. You can [join here](https://discord.gg/MNQqqKg).

**Comment by louistiti** [comment]
Solved via Discord. His Leon version was outdated, and he did not run the `npm install` for the second part of the issue.
