### ISSUE TITLE
Send query through HTTP request

### ISSUE THREAD

**Issue by mario-baptista** [leon-ai/leon#244]
Hi!
I was jus wondering if there was any way to interact with leon with a simple HTTP request.
Thanks in advance.

**Comment by louistiti** [comment]
Hi @mario-baptista :wave:,

Thanks for asking. Can you please elaborate your thoughts by explaining the use case you'd like to fulfill? What parts would you like to expose over HTTP?

**Comment by mario-baptista** [comment]
I would like to explore new ways to interact with leon.
My idea was to build a facebook messeger bot (or discord) that would receive my text messages and send a HTTP request to leon so he could process the query.

**Comment by louistiti** [comment]
Today you can try to plug it over a WebSocket which at the end works with a TCP socket same as HTTP does, just WebSocket is a persistent one. You can take a look at the [web app](https://github.com/leon-ai/leon/tree/develop/app) to see how you can achieve that from your server to Leon.

I planned anyway to expose Leon over HTTP for other use cases, and external clients are part of it. I will make it appear on the roadmap.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.6] Review architecture to consider mobile app and desktop app clients](https://trello.com/c/7z4zu2V0/303-%F0%9F%94%A7-100-beta6-review-architecture-to-consider-mobile-app-and-desktop-app-clients)

**Comment by mario-baptista** [comment]
Ok Thanks!

**Comment by louistiti** [comment]
Will be available for the next version https://github.com/leon-ai/leon/issues/244.
