### ISSUE TITLE
Offline Personal Assistant - I want to use this on Jetson nano, will it work?

### ISSUE THREAD

**Issue by kunalait** [leon-ai/leon#250]

**Comment by louistiti** [comment]
Hi @kunalait :wave:,

Thanks for asking. I do not see why it could not work. Do you have such hardware with you? If yes, please try and let us know!

**Comment by kunalait** [comment]
Thank you so much for your update. I will work on my hardware device and will you know the update.

**Comment by louistiti** [comment]
Awesome! Looking forward to the follow-up :+1:

**Comment by louistiti** [comment]
Hi @kunalait, did you successfully move forward on this topic? 😃

**Comment by louistiti** [comment]
I close this as no answer has been provided.
