### ISSUE TITLE
Show the weather 

### ISSUE THREAD

**Issue by QJoly** [leon-ai/leon#251]
Hi :) 
I've just installed Leon on Docker to try it, and i'm surprised that there is no weather module

### Feature Use Case
- Leon, What is the weather forecast for tomorrow
- Tomorrow it will rain
### Feature Proposal

Use the API of OpenWeatherMap (Free, And reliable) to show the weather

**Comment by louistiti** [comment]
Hi @QJoly :wave:,

Thanks for suggesting. That is indeed on the roadmap. New modules will come later once the core will be more powerful.

I close this as there is an ongoing issue here: https://github.com/leon-ai/leon/issues/43. Also, a PR has been opened regarding this topic: https://github.com/leon-ai/leon/pull/108.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Forecast Package](https://trello.com/c/xv2XLWBZ/236-%E2%9C%A8-forecast-package)
