### ISSUE TITLE
✖ listen EACCES: permission denied 0.0.0.0:1337

### ISSUE THREAD

**Issue by lightvortex01** [leon-ai/leon#262]
Hi i have a problem with the INITIALIZATION. 
i did all the previouse steps but it show me this message :✖ listen EACCES: permission denied 0.0.0.0:1337
can you help me to fix that please ?

**Comment by louistiti** [comment]
Hi @lightvortex01 :wave:,

Thanks for opening this issue. Can you please try to change the `PORT` to another one via the `.env` file and retry?

**Comment by lightvortex01** [comment]
ok thx it work perfectly!
