### ISSUE TITLE
The docs are really confusing

### ISSUE THREAD

**Issue by someones-alt** [leon-ai/leon#295]
### Documentation Is:
- [x] Missing
- [ ] Needed
- [] Confusing
- [ ] Not Sure?

### Explanation
I really like this idea and I wanted to try it out on my debian-based linux distro,
I got a lot of errors and I have no clue of how to solve them

### Proposal
A section for common errors really would be appreciated

### The errors I got
When running npm start and then typing something I get this:
Failed to delete query object file: Error: ENOENT: no such file or directory,

And Leon says this:
Sorry, I've got an error with the "Greeting" module of my "Leon" package!
and:
Sorry, I have an issue with the "Greeting" module of my "Leon" package!

**Comment by louistiti** [comment]
Hi 👋,

A place like you mention might take place in the future. In the meantime, you can take a look at the issues on GitHub by doing [a simple research](https://github.com/leon-ai/leon/issues?q=Sorry%2C+I%27ve+got+an+error+with+the+).

Then, if you want to solve this problem, please start by sharing the output of the `npm run check` command.
