### ISSUE TITLE
Trends Package

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#3]
One module for each platform.

# Modules

## Product Hunt module
```
Leon, what's trending on Product Hunt?
```

## GitHub module
```
Leon, what's trending on GitHub?
```

Might be related to a [another package](https://trello.com/c/t2AGpoqk/138-%E2%9C%A8-github-package).

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Trends Package](https://trello.com/c/UPGaO0gb/177-%E2%9C%A8-trends-package)

**Comment by molamk** [comment]
@louistiti Can I work on this feature?

**Comment by louistiti** [comment]
Hello @molamk,

Thanks for that. However regarding this package/module, I prefer to handle it myself to confirm that the NLU improvement is complete enough for such modules.

It's still a WIP, but I committed yesterday about that topic https://github.com/leon-ai/leon/commit/6585db718ccae1d750a35783075cf61cc8fe84f1.

Feel free to pick up a package from the [roadmap](https://roadmap.getleon.ai) backlog and open an issue for that. As you can see, there are a plenty of things incoming 😄

**Comment by molamk** [comment]
Roger that @louistiti ! I'll take a look at the roadmap and pick up card from there.
Keep up the good work!

**Comment by louistiti** [comment]
Cool! I'm looking forward to see your contribution 👍

**Comment by louistiti** [comment]
I'm working under [that branch](https://github.com/leon-ai/leon/tree/trend-package) for that feature.

**Comment by louistiti** [comment]
The GitHub module of the Trend package is nearly done, we can use it as following:

```
(en-US) "What's trending on GitHub?"
(en-US) "Give me the 4 GitHub trends of this week for the JavaScript language"
(en-US) "What's the three GitHub trends of this month?"
...
```

**Comment by louistiti** [comment]
The GitHub module is done and [merged](https://github.com/leon-ai/leon/commit/6db9eb1e70eb7f5353ed7c11c5f7a9939adb92b1) into [develop](https://github.com/leon-ai/leon/tree/develop).

**Comment by louistiti** [comment]
The Product Hunt module is done and [merged](https://github.com/leon-ai/leon/commit/99b4d838e4560f76d824e14eeddcb183562d19b6) into [develop](https://github.com/leon-ai/leon/tree/develop).
