### ISSUE TITLE
How exactly is Leon…..

### ISSUE THREAD

**Issue by Nimolas** [leon-ai/leon#307]
How exactly is Leon an ai.

if I’m not mistaken ai stands for artificial intelligence which is something that can think for itself but with Leon it tells you to fork it or whatever on GitHub please explain it to me if it’s possible.

**Comment by Mcboy13** [comment]
@louistiti

**Comment by louistiti** [comment]
Hi @Nimolas :wave:,

Leon uses several AI concepts such as NLP, STT, TTS and more in the future. I believe you are referring to the case when Leon does not understand your query. The whole point of the machine learning isn't there for Leon, put mostly in the way he understands your query (NLU).
In the future, if Leon does not understand your query, I may add a fallback to a language model output such as GPT-* or BERT.

I'll close this issue, feel free to reopen it if necessary.
