### ISSUE TITLE
Use Docker to simplify install?

### ISSUE THREAD

**Issue by 1c7** [leon-ai/leon#31]
### Intro
having issue `npm install` on macOS
![image](https://user-images.githubusercontent.com/1804755/53071207-7c2a1580-351c-11e9-83e8-6b15c436e16a.png)
```
✖ Failed to install the Python packages: Error: Command failed: /bin/sh -c pipenv install
Warning: Python 3.6 was not found on your system...
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```
## Question
Would you guys build a Docker Image to simplify local dev & production running process?

just write a `Dockerfile` would be enough(I think). or both `Dockerfile` & `docker-compose.yml`
it's not difficult at all.

then it can be easily run without all these install process, that would be really helpful

Any thought?  Thanks

**Comment by louistiti** [comment]
Hello @1c7,

Thanks for opening this issue.

Yes, there is already a plan for that:

- https://github.com/leon-ai/leon-ci-image/pull/1
- https://github.com/leon-ai/leon/pull/9
- https://github.com/leon-ai/leon/pull/13
- https://github.com/leon-ai/leon/issues/1

**Comment by 1c7** [comment]
@louistiti oh, Ha, I didn't saw these. 
let me close this issue now
