### ISSUE TITLE
How can Leon make rest API requests to a local server?

### ISSUE THREAD

**Issue by gabrielcolon32** [leon-ai/leon#318]
### Question
Hi,

Is there a file that explains if and how Leon can communicate with another server locally?

Thanks in advance.

**Comment by louistiti** [comment]
Hi @gabrielcolon32 :wave:,

Thanks for opening this issue. I'm starting to work again on the core of Leon. [This part of the docs](https://docs.getleon.ai/packages-modules#httpmethod-url-headers--none) may answer your question.

I'm closing this issue, feel free to reopen it if necessary.
