### ISSUE TITLE
Does Leon have the ability to understand domain specific knowledge?

### ISSUE THREAD

**Issue by gabrielcolon32** [leon-ai/leon#320]
Hi! Does Leon have the ability to understand domain specific knowledge and commands? More specifically: could you train Leon and optimize it  to only understand commands related to let's say, setting up a timer or ordering a pizza?

**Comment by louistiti** [comment]
Hello @gabrielcolon32 :wave:,

Thanks for your question. Late reply I know, I'm coming back to work on the core of Leon!

Yes, Leon has the ability to understand domains. Leon packages are actual domains. I just added more precisions [in the docs](https://docs.getleon.ai/glossary#packages).

> Alternatively, packages are what we call "domains" in the NLP (Natural Language Processing) field. Domain classification is a way to structure/label data for a better scalability. It helps Leon to make decisions on what to understand and improve his accuracy. 

Hope that helps!

**Comment by louistiti** [comment]
Closing this as the answer has been provided.
