### ISSUE TITLE
No reaction from mic. Typing works.

### ISSUE THREAD

**Issue by DeviousSiddy** [leon-ai/leon#323]
### Specs

- Leon version: v1.0.0-beta.4
- OS (or browser) version: Chrome browser on Win11 Version 95.0.4638.69 (Official Build) (64-bit)
- Node.js version: v17.0.1
- Complete "npm run check" output:
➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured 
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Expected Behavior
Listen to microphone
### Actual Behavior
No reaction from microphone. Button also does nothing.
Typing prompts does work.
### How Do We Reproduce?
Try it.

**Comment by NXture** [comment]
hey @DeviousSiddy, that's because you have added only tts (text-to-speech) provider ( i.e., Amazon Polly). In order for the mic to work, you should add stt (speech-to-text) provider like Watson or google.
