### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by yeetus-maximus** [leon-ai/leon#326]
### Question

`g0pn1k-laptop:leon-develop Admin$ npm build
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help
g0pn1k-laptop:leon-develop Admin$ npm start

> leon@1.0.0-beta.5+dev start
> cross-env LEON_NODE_ENV=production node ./server/dist/index.js

---

.: INITIALIZATION :.

✔ The current env is production
✔ The current version is 1.0.0-beta.5+dev
✔ The current language is en-US
✔ The current time zone is Singapore
✔ Collaborative logger enabled
✔ Server is available at http://localhost:1337

---

.: CLIENT :.

✔ Connected
➡ Type: webapp
➡ Socket id: RhBf4Td3N721oPsLAAAB

---

.: BRAIN :.

✔ New instance

---

.: NER :.

✔ New instance

---

.: NLU :.

✔ New instance

---

.: ASR :.

✔ New instance

---

.: INITIALIZATION :.

✔ STT disabled
✔ TTS disabled

---

.: NLU :.

✔ NLP model loaded

---

.: REQUESTING :.

➡ GET /

---

.: REQUESTING :.

➡ GET /assets/index.77f1e308.css

---

.: REQUESTING :.

➡ GET /assets/index.d5093598.js

---

.: REQUESTING :.

➡ GET /assets/vendor.8374a2ad.js

---

.: REQUESTING :.

➡ GET /assets/logo.0679f287.svg

---

.: REQUESTING :.

➡ GET /assets/mic.d8267246.svg

---

.: REQUESTING :.

➡ GET /v1/info

---

.: GET /INFO :.

✔ Information pulled.

---

.: REQUESTING :.

➡ GET /assets/favicon.e9708100.png

---

.: CLIENT :.

✔ Connected
➡ Type: webapp
➡ Socket id: 1yEdb01rQK4oJyR7AAAD

---

.: BRAIN :.

✔ New instance

---

.: NER :.

✔ New instance

---

.: NLU :.

✔ New instance

---

.: ASR :.

✔ New instance

---

.: INITIALIZATION :.

✔ STT disabled
✔ TTS disabled

---

.: NLU :.

✔ NLP model loaded

---

.: SOCKET :.

➡ webapp emitted: hi leon?

---

.: NLU :.

➡ Processing...

---

.: NLU :.

✔ Query found

---

.: NER :.

➡ Searching for entities...
➡ No entity found

---

.: LEON PACKAGE :.

➡ 

---

.: LEON :.

➡ Talking...
✖ Failed to delete query object file: Error: ENOENT: no such file or directory, unlink '/leon-develop/server/dist/core/../tmp/1638106838542-1j9o.json'

---

.: LEON :.

       `

How do i solve this issue

**Comment by yeetus-maximus** [comment]
im quite new so i dont think this was supposed to happen

**Comment by louistiti** [comment]
Hi @yeetus-maximus :wave:,

Thanks for reporting this.

To build the project, you should execute `npm run build`. You are currently doing `npm build` which is wrong.

Regarding the "Failed to delete query object file" error, that isn't a blocking issue. It just means the temporary file containing the query cannot be deleted due to the asynchronous aspect of Leon. I'll check to fix this or replace it with a warning in the next versions.

**Comment by louistiti** [comment]
Closing this issue as the answer has been provided.
