### ISSUE TITLE
"Modules" to "skills" new structure

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#335]
### Expected Behavior

Complete new modules structure and transition from "modules" to "skills".

### Actual Behavior

The current modules structure depends on modules developers and the whole structure isn't scalable enough.

### Proposal

As Leon plans to grow, I believe that having a specific folders/files structure is essential.
Mainly the following reasons make me think like this:

- At the moment, Leon skills are developed in Python only. Soon, the JavaScript bridge will come so it'll be possible to develop skills using JavaScript too. So having a hierarchy between bridges will help to be consistent between every module.
- Some skills are small, some will be bigger. Some skills will require more business logic than others, so it is crucial to define a well organized and scalable structure.

Also, when we get to know about Leon, "modules" can means everything, it is too abstract. I think "skills" is more appropriate as it really means something and we may be more familiar with this word.

Leon NLP will be improved so we can build more powerful skills. Hence, a transition needs to be made from "packages" to "domains". These domains need to be defined, so skills developers don't need to create one, but just put their skills in the corresponding domain. Doing so will allow a better NLU accuracy.

- More details can be found in [this roadmap card](https://trello.com/c/SQl06isp/415-%F0%9F%94%A7-100-beta7-new-modules-to-skills-structure).
- The development can be followed via [this branch](https://github.com/leon-ai/leon/tree/from-modules-to-skills).

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.6] New packages/modules structure](https://trello.com/c/h32JPfO9/302-%F0%9F%94%A7-100-beta6-new-packages-modules-structure)

**Comment by louistiti** [comment]
> It would be interesting to design, in parallel of this new structure, a collaborative platform where everyone could create and share their modules and download other modules, to involve the community and quickly grow Leon’s capabilities.
> 
> Is this the future ambition of the project ?

That is interesting. At the moment upcoming modules can be seen on the roadmap. But the roadmap contains a lot of things, so yes I think something can be done there to centralize that. I will think about it.

But firstly, the official version (1.0.0) needs to be out so we can make sure we can finally start to grow Leon capabilities in terms of modules.

**Comment by SquareInnov** [comment]
> > It would be interesting to design, in parallel of this new structure, a collaborative platform where everyone could create and share their modules and download other modules, to involve the community and quickly grow Leon’s capabilities.
> > Is this the future ambition of the project ?
> 
> That is interesting. At the moment upcoming modules can be seen on the roadmap. But the roadmap contains a lot of things, so yes I think something can be done there to centralize that. I will think about it.
> 
> But firstly, the official version (1.0.0) needs to be out so we can make sure we can finally start to grow Leon capabilities in terms of modules.

Other projects do similar things like MyCroft or Olivia. In this kind of platform, you can retrieve 3 types of "modules", the officials (developped by the Leon Team), the trusted (created by the community but approved by the Leon Team ) and the 'unofficial' others...

I love your project, and I use a "custom" version of Leon in my house, I created my own modules for my own usages (house automation, cooking recipes integration with "Marmiton" etc...). But, I think it’s a big lack of not having the ability to "easily" share this modules with others. 

I hope to see that soon.

**Comment by louistiti** [comment]
> > > It would be interesting to design, in parallel of this new structure, a collaborative platform where everyone could create and share their modules and download other modules, to involve the community and quickly grow Leon’s capabilities.
> > > Is this the future ambition of the project ?
> > 
> > 
> > That is interesting. At the moment upcoming modules can be seen on the roadmap. But the roadmap contains a lot of things, so yes I think something can be done there to centralize that. I will think about it.
> > But firstly, the official version (1.0.0) needs to be out so we can make sure we can finally start to grow Leon capabilities in terms of modules.
> 
> Other projects do similar things like MyCroft or Olivia. In this kind of platform, you can retrieve 3 types of "modules", the officials (developped by the Leon Team), the trusted (created by the community but approved by the Leon Team ) and the 'unofficial' others...
> 
> I love your project, and I use a "custom" version of Leon in my house, I created my own modules for my own usages (house automation, cooking recipes integration with "Marmiton" etc...). But, I think it’s a big lack of not having the ability to "easily" share this modules with others.
> 
> I hope to see that soon.

Glad to see that you love Leon! A big revamp is coming up and many positive changes are going to happen in the way Leon is built and how we build modules.

I need to make sure that everything is well designed in a way modules are built, then such platform will happen.

Stay tuned 😉

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.7] New "modules" to "skills" structure](https://trello.com/c/SQl06isp/415-%F0%9F%94%A7-100-beta7-new-modules-to-skills-structure)

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.7] New "modules" to "skills" structure](https://trello.com/c/SQl06isp/415-%F0%9F%94%A7-100-beta7-new-modules-to-skills-structure)

**Comment by ihantoh** [comment]
Hi Leon-Ai/Leon, my name  is Iorah and my wife username is Iantoh...
I can only answer than i am very interested of course, I can teach to
Leon-Ai-Leon without problem, and support to develop of this module or any
other.
Only there is one problem i think, I like to talk of this aventure on the,
face to face oki??? Our movil number is 0034605564274, we are activated
24hh/7d 365ddyy oki.... To good worker must always be paid well, this was
told mesaid me my grampa when I started to working.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by louistiti** [comment]
It has been released. Everything is explained in [this blog post](https://blog.getleon.ai/a-much-better-nlp-and-future-1-0-0-beta-7/).
