### ISSUE TITLE
Could not fetch metadata for snowboy@git+ssh://git@github.com/leon-ai/snowboy.git#d393fbff3ea319131071b90fb587884572facd5c Error: git dep preparation failed

### ISSUE THREAD

**Issue by NXture** [leon-ai/leon#337]
Hey Louis, welcome back

I was trying to install hotword and I came across this error. 
I think it is some access issue. Can you please help me with that.

### Actual Behavior
```
Could not fetch metadata for snowboy@git+ssh://git@github.com/leon-ai/snowboy.git#d393fbff3ea319131071b90fb587884572facd5c Error: git dep preparation failed
```

**Comment by johannbarbie** [comment]
`npm run setup:offline` also fails with reference to snowboy

**Comment by johannbarbie** [comment]
when running `npm install` in hotword, snowboy is a transitive dependency, and bindings are fetched from`https://leon-ai-snowboy.s3-us-west-2.amazonaws.com`. the endpoint is only returns 403 for me.

**Comment by NXture** [comment]
thanks for your interest @johannbarbie . May I know the node version you are using?

> when running `npm install` in hotword, snowboy is a transitive dependency, and bindings are fetched from`https://leon-ai-snowboy.s3-us-west-2.amazonaws.com`. the endpoint is only returns 403 for me.

**Comment by johannbarbie** [comment]
i'm running v16.13.2 on mac

**Comment by NXture** [comment]
were you able to run hotword using v16? i believe snowboy only supports older node like v10 n below.

**Comment by johannbarbie** [comment]
leon requires node v16, so I assumed all components do as well. I had to manually build the bindings in snowboy using this command: 
`CXXFLAGS="--std=c++17" node-pre-gyp/bin/node-pre-gyp clean configure build`

i've tried to automate the step in [this PR](https://github.com/leon-ai/leon/pull/342)

**Comment by NXture** [comment]
yeah, i got it. it does connects to the server and starts waiting for the hotword. but it couldn't catch any phrase. was it same for you?

**Comment by johannbarbie** [comment]
after building the binding I was able to issue the hotword and give of a command:
1. "Leon" -> mic turns blue
2. "Give me a random number"
3. Leon returns random number and reads it out

**Comment by NXture** [comment]
it works @johannbarbie , earlier i was using WSL2 and it didn't have access to the microphone. I just switched to Ubuntu system and it catches the hotword now. Thanks for your support.
