### ISSUE TITLE
Bug fixed

### ISSUE THREAD

**Issue by Cearl03** [leon-ai/leon#343]
### Specs

- Leon version:
- OS (or browser) version:
- Node.js version:
- Complete "leon check" (or "npm run check") output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Extra (like a sample repo to reproduce the issue, etc.)

**Comment by louistiti** [comment]
Hi, the content of the issue is empty. Maybe a missclick? Please reopen one if necessary.
