### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by ghostslayer989** [leon-ai/leon#35]
### Specs

- Leon version: Commit d0ca87d
- OS (or browser) version: Linux Mint 19.1 Cinnamon.
- Node.js version: 8.10.9
- Complete "npm run check" output: https://pastebin.com/UyZjGtnu
- (optional) Leon package version:

### Expected Behavior
Leon is buildable and runs.

### Actual Behavior
Leon is unbuildable and unable to run.

### How Do We Reproduce?
Use steps on ReadME with fresh packages from original Mint Install.

### Extra (like a sample repo to reproduce the issue, etc.)
Using Bash-It for my linux terminal.

**Comment by Shrubhog** [comment]
It seems you have to update node and npm. Node can be updated with nvm or npm, and npm can be used to update itself.

**Comment by ghostslayer989** [comment]
I just updated Node and NPM. Still the same.

**Comment by Shrubhog** [comment]
What other errors are produced during build?

**Comment by ghostslayer989** [comment]
All the text in PasteBin is all I got.

**Comment by louistiti** [comment]
Hello @ghostslayer989,

Thanks for opening this issue. However, according to your [last pastebin](https://pastebin.com/4Qs7UhQN), you are using Node.js `8.10.0` and npm `3.5.2`. Please take a look at the [prerequisites](https://docs.getleon.ai/#prerequisites).

**Comment by louistiti** [comment]
I consider this issue as fixed. Feel free to reopen it if it wasn't.
