### ISSUE TITLE
Skill types

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#351]
### Feature Use Case

```		
intent: leon.color
"What is your favorite color?"
My favorite color is ...
"Do you like the @color color?"
I like the @color color, but my favorite one is ...
```

### Feature Proposal

A skill type layer needs to be added to differentiate skills that need to execute business logic (code) and the ones who only need dialog to function (utterance samples, answers, entities, etc.).

Here are the two types:
- `dialog`: small talks or questions/answers without any code, only use files to configure.
- `logic`: execute actions.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.7] Skill types](https://trello.com/c/R5f9mwpQ/420-%E2%9C%A8-100-beta7-skill-types)

**Comment by Sarthakischauhan** [comment]
Hey 
Where do i add this skill ? 
In the packages folder or somewhere else ?

**Comment by louistiti** [comment]
> Hey Where do i add this skill ? In the packages folder or somewhere else ?

Hi, this isn't a skill but a new feature. I'm revamping the whole core of Leon at the moment so many changes are coming. I advise to not create new skills at the moment until the revamp is done.

**Comment by louistiti** [comment]
It has been released. Everything is explained in [this blog post](https://blog.getleon.ai/a-much-better-nlp-and-future-1-0-0-beta-7/).
