### ISSUE TITLE
Add a providers layer to skills

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#352]
### Feature Use Case

```
Leon, play some musics
> Gotcha, I'll play it on Spotify

Leon, I'd prefer to listen the music on @provider today
> Sure, let's enjoy @provider then!
```

### Feature Proposal

To make sure we don't overuse intents, we should add a provider level to skills. This will improve the NLP model accuracy.
In this way, a skill `music` can be created with nearly the same intents but for different providers such as Spotify, Pandora, Deezer, etc. The same goes for a weather skill for example.

- The provider can be defined on the fly using slot filling/entity annotation on the utterance sample.
- A provider is set by default in the config of the skill.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.7] Add providers level to skills](https://trello.com/c/eusHhDXj/419-%E2%9C%A8-100-beta7-add-providers-level-to-skills)

**Comment by ihantoh** [comment]
Ok!! The mensaje has been understood correctly!!
The Job that you encomiending me is one of part most important of my work
and one passion, Now is a new era of Sentimental Cuantic Cuantification and
to be consciente of their existente, Me and my WiFi we hace very clear.
TOMORRO THE WORKS STARTS, THANKIU LOUIS... Talk, tomorrow...

**Comment by louistiti** [comment]
This will be added before to release the official version. Closing this issue now.
