### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by shacarstuff** [leon-ai/leon#366]
i am almost finished with the install of leon but i get this error when running the command: leon create birth

SyntaxError: Unexpected reserved word
at loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
at async link  (internal/modules/esm/module_job.js:42:21)

my system is a CentOS 7 machine if anyone was wondering

**Comment by Divlo** [comment]
Hey! @shacarstuff :wave:
Thanks for your report!
For all installation-related problems with Leon, please next time creates an issue on https://github.com/leon-ai/leon-cli.

Concerning your error, there is not enough information to help you debug what is going on, please verify that you have the right Node.js version (>= 16.0.0) as stated in the [documentation](https://docs.getleon.ai/) and README.
Please when creating an issue, provide as much as possible information about the issue, example of information that could be given:
- What command exactly has been used? `leon create birth` has many options...
- If you didn't use the `--yes` option and you don't have already Python installed, did you answer yes or no to this kind of question `Would you like to install Python? If you don't, Leon may not work properly.`
- As this error is more like an issue with Node.js it seems like, not necessarily related to `leon create birth` command, but it could be more general. Do `leon help` command work or it yields the same error?

Most of these questions would be answered if you did a screenshot of the whole screen of your terminal.

Not related to this error but unfortunately, CentOS is not currently supported in the core of Leon.
Leon Core only supports GNU/Linux distribution that uses `apt`/`apt-get` package manager.
Fortunately, it is on the roadmap to support more Linux distribution and setup in general.
Ref: [🔧 [1.0.0] Compatibility with ARM architectures and GNU/Linux distributions](https://trello.com/c/CxRNbLHQ/256-%F0%9F%94%A7-100-compatibility-with-arm-architectures-and-gnu-linux-distributions)
