### ISSUE TITLE
leon Can't handle LC_ALL=c

### ISSUE THREAD

**Issue by Zauberfisch** [leon-ai/leon#38]
### Specs

- Leon version: 1.0.0-beta.0
- OS (or browser) version: archlinux
- Node.js version: v11.10.0
- Complete "npm run check" output: [leon-check.txt](https://github.com/leon-ai/leon/files/2896341/leon-check.txt)

### Expected Behavior
```
# in Leon Interface
> Hello
< Hi! Please, you should sleep to be in shape for your day.
```
### Actual Behavior
```
# in Leon Interface
> Hello
< Sorry, it seems I have a problem with the Greeting module of my Leon package!
< Sorry, it seems I have a problem with the Greeting module of my Leon package!
< Hi! Please, you should sleep to be in shape for your day.
```

Error message from the process:
```
✖ /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8) in greeting module
```

### How Do We Reproduce?
LC_ALL=c

(c is a valid locale, see https://linux.die.net/man/3/setlocale)

### Extra

`$ LC_ALL=en_US.UTF8 npm start` works

**Comment by louistiti** [comment]
Hello @Zauberfisch,

Thanks for opening this issue. I replied to a similar one [here](https://github.com/leon-ai/leon/issues/18).

In the `.env.sample` file (which is duplicated to generate the `.env`) I'll see if it worth to replace:
```
LC_ALL=C.UTF-8
LANG=C.UTF-8
```
to:
```
LC_ALL=en_US.UTF8
LANG=en_US.UTF8
```

**Comment by louistiti** [comment]
I added a comment in the dotfiles regarding the topic.

- https://github.com/leon-ai/leon/commit/31658140367db27cc56058280e02e77eab169801
- https://github.com/leon-ai/leon/commit/1d559070e269250497d3ce187ce853b472551b50

**Comment by OzTK** [comment]
Thanks for adding this comment, it helped me finding a valid locale and fix this problem :) Still took me a bit of digging into the repo issues to find out about it. Would it be worth adding a step in the docs to configure the locale? I can open a PR if it helps.
This error showed up when I ran `npm install` the first time

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [📝 FAQ in docs](https://trello.com/c/NwWLpufW/240-%F0%9F%93%9D-faq-in-docs)

**Comment by louistiti** [comment]
Hello @OzTK,

Thanks for suggesting and I'm happy that helped. I added a card to the roadmap about creating an FAQ section in the docs. That will be added to it.

**Comment by OzTK** [comment]
Nice! Sounds like the perfect place for this kind of problems.
Also, awesome job on Leon 👏👏 I hope I can contribute soon 🙂

**Comment by louistiti** [comment]
Thanks for supporting!

Looking forward to your contribution then 👍
