### ISSUE TITLE
hi properly install leon but it says leon greeting module broken and voice modules also not working

### ISSUE THREAD

**Issue by srivickybe** [leon-ai/leon#388]
<!--node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn bin/flite/flite ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn bin/flite/flite',
  path: 'bin/flite/flite',
  spawnargs: [
    'Sorry, the "Greeting" skill from the "Leon" domain is broken!',
    '--setf',
    'int_f0_target_mean=115',
    '--setf',
    'f0_shift=1',
    '--setf',
    'duration_stretch=1',
    '--setf',
    'int_f0_target_stddev=15',
    '-o',
    'D:\\venv\\audio\\leon-develop\\leon-develop\\server\\dist\\tts\\flite/../../tmp/1657002979138-jc0k.wav'
  ]
}

if i edit .env file STT and TTS set it true after if i given any text its automatically out from the server and show the below error

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn bin/flite/flite ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn bin/flite/flite',
  path: 'bin/flite/flite',
  spawnargs: [
    'Sorry, the "Greeting" skill from the "Leon" domain is broken!',
    '--setf',
    'int_f0_target_mean=115',
    '--setf',
    'f0_shift=1',
    '--setf',
    'duration_stretch=1',
    '--setf',
    'int_f0_target_stddev=15',
    '-o',
    'D:\\venv\\audio\\leon-develop\\leon-develop\\server\\dist\\tts\\flite/../../tmp/1657004169967-8wkh.wav'
  ]
}

**OS: Windows 
node = v16.15.1
pipenv =  version 2022.5.2
Python 3.9.7**

✅ Found and valid

ℹ️  Amazon Polly TTS
⚠️  Amazon Polly TTS is not yet configured

ℹ️  Google Cloud TTS/STT
⚠️  Google Cloud TTS/STT is not yet configured

ℹ️  Watson TTS
⚠️  Watson TTS is not yet configured

ℹ️  Offline TTS
✅ Found Flite at bin/flite/flite

ℹ️  Watson STT
⚠️  Watson STT is not yet configured

ℹ️  Offline STT
✅ Found Coqui language model at bin/coqui/huge-vocabulary.scorer

.: REPORT :.
ℹ️  Here is the diagnosis about your current setup
✅ Run
✅ Run modules
✅ Reply you by texting
⚠️  Amazon Polly text-to-speech
⚠️  Google Cloud text-to-speech
⚠️  Watson text-to-speech
✅ Offline text-to-speech
⚠️  Google Cloud speech-to-text
⚠️  Watson speech-to-text
✅ Offline speech-to-text

✅ Hooray! Leon can run correctly

**Comment by louistiti** [comment]
Can you correctly answer the questions?

**Comment by srivickybe** [comment]
i was trying to install but i could not .. 1. error was greeting module error and if STT & TTS error its showing , for TTS installation shows windows os not compatible one

**Comment by louistiti** [comment]
> i was trying to install but i could not .. 1. error was greeting module error and if STT & TTS error its showing , for TTS installation shows windows os not compatible one

You aren't replying to the questions correctly, hence I will close this issue. You can join us on [the Discord](https://discord.gg/MNQqqKg) for further investigation. This issue will be updated if any new result appears.
