### ISSUE TITLE
Broken links for documentation etc.

### ISSUE THREAD

**Issue by hearsid** [leon-ai/leon#390]
### Specs

- Leon version:
- OS (or browser) version:
- Node.js version:
- Complete "leon check" (or "npm run check") output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### Expected Behavior
Links in homepage should work.

### Actual Behavior
The website the links are redirecting to is not loading.

### How Do We Reproduce?
Click on links on  readme page, 
![image](https://user-images.githubusercontent.com/3892451/178922109-cf4a3288-0d16-48e4-bef5-7f6a6546fd19.png)

**Comment by louistiti** [comment]
Hi @hearsid :wave:,

It seems that the links work correctly. Maybe you should try again.

**Comment by louistiti** [comment]
> This is weird, they are not working for me. ![image](https://user-images.githubusercontent.com/3892451/179005722-41af56ef-9554-4461-b0f1-3732f641dfa9.png)

Can you try the following please?

- Run the following command: `ping getleon.ai` and copy the result.
- Run the following command: `ping docs.getleon.ai` and copy the result.
- Open this website https://vercel.com/ and share how it went.

**Comment by hearsid** [comment]
![image](https://user-images.githubusercontent.com/3892451/179047457-707a212a-ac1e-4b3a-a035-59210ef78b4c.png)
![image](https://user-images.githubusercontent.com/3892451/179047496-88341258-5712-4264-86dc-85e22c37ad94.png)

**Comment by hearsid** [comment]
@louistiti Any idea what the can be the issue?

**Comment by louistiti** [comment]
> @louistiti Any idea what the can be the issue?

Have you tried by using a VPN?
