### ISSUE TITLE
Broken Leon Package

### ISSUE THREAD

**Issue by menporulporiayalan** [leon-ai/leon#41]
### Specs

- Leon version: 1.0.0.beta -1
- OS (or browser) version: Ubuntu 18.10 
- Node.js version: 11.10.0
- Complete "npm run check" output:
```

> leon@1.0.0-beta.1 check /home/emperoreby/sideprojects/leon
> babel-node scripts/run-check.js

sh: 1: babel-node: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! leon@1.0.0-beta.1 check: `babel-node scripts/run-check.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.1 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emperoreby/.npm/_logs/2019-02-24T12_39_09_469Z-debug.log
```

### Expected Behavior:
Leon should give a proper reply when we ask questions.

### Actual Behavior
It is throwing an error like "Sorry, I have an issue with the Greeting module of my Leon package!"

### Extra (like a sample repo to reproduce the issue, etc.)
I have updated the .env.sample file as per [this.  ](https://github.com/leon-ai/leon/issues/38)

I got this below error when docker 7th step.
```

Step 7/10 : RUN npm install
 ---> Running in 145bed53e9ab
npm WARN lifecycle leon@1.0.0-beta.1~preinstall: cannot run in wd leon@1.0.0-beta.1 node scripts/setup/preinstall.js (wd=/app)
```
But installed successfully with some warnings.  

Please let me know if you need any extra info.
![issue](https://user-images.githubusercontent.com/14214520/53299540-9daf3800-3861-11e9-9b70-3924ac1b5f98.gif)

 
I have attached the Gif regarding the issue. Feel free to take a look.

**Comment by louistiti** [comment]
Hello @menporulporiayalan,

Thanks for opening this issue. Could you please paste the result of your `locale -a`?

**Comment by menporulporiayalan** [comment]
Here it is

```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

```

**Comment by louistiti** [comment]
Somehow, some systems have `en_US.UTF8`, some have `en_US.UTF-8`, please note the different between those two.

According to the output of your `locale -a`, it seems yours should be `en_US.UTF8`. Also, be careful with your whitespace for your `LC_ALL`.

Once you finished to edit your `.env.sample`, then build again with your Docker as the `.env.sample` is duplicated to create the `.env` file, and that is the one that Leon will read.

Let me know if it works or not.

**Comment by menporulporiayalan** [comment]
Thanks, it works! But it is not receiving my voice!

**Comment by louistiti** [comment]
Regarding the voice topic it is another topic. I invite you to take a look at the [documentation](https://docs.getleon.ai/configuration.html#voice).

Feel free to open another issue if you think you need help.

**Comment by menporulporiayalan** [comment]
@louistiti Thanks! :+1:
