### ISSUE TITLE
TypeScript Rewrite

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#412]
Leon’s codebase keeps growing and it’s not going to stop anytime soon. When I started to build Leon at the first place (late 2017), I was afraid to use TypeScript because I thought it would prevent some people to contribute to the core as TypeScript wasn’t as well adopted as it is today. Now is the time!

That's the focus for the `1.0.0-beta.8` version.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.8] TypeScript rewrite / IoC thinking](https://trello.com/c/EfqL6Vb8/442-%E2%9C%A8-100-beta8-typescript-rewrite-ioc-thinking)

**Comment by Akul2010** [comment]
Since typescript is a superscript of Javascript, can't you technically start by renaming all the .js files to .ts? I'm not experienced in JS/TS that much, though, so please correct me if I'm wrong.

**Comment by louistiti** [comment]
> Since typescript is a superscript of Javascript, can't you technically start by renaming all the .js files to .ts? I'm not experienced in JS/TS that much, though, so please correct me if I'm wrong.

Can, but there is no purpose of doing so as we'd not benefit from TypeScript.
I'm secretly working on it locally and I haven't pushed any change yet. Also, I'm taking some time as I need to handle a few things in my personal life at the moment.

**Comment by louistiti** [comment]
So glad that the TypeScript came to an end! :partying_face:
