### ISSUE TITLE
Error After npm install

### ISSUE THREAD

**Issue by DylanORK** [leon-ai/leon#420]
Hello everyone!

I have a new install of ubuntu server, and I wanted to install leon on it. 

Node and npm are installed.
But whatever the command, it does give me the same error, below :

leon create birth OR leon check
file:///usr/local/lib/node_modules/@leon-ai/cli/build/index.js:13
await cli.runExit(arguments_, Cli.defaultContext);
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

Have you ever encountered anything like that ?

Please tell me if you need any other information

OS: Ubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-47-generic
Shell: bash 5.1.16

**Comment by NukeLouis** [comment]
I had the same issue.
I had to update npm and node to the latest version, and install leon again, after I did that it worked.

**Comment by louistiti** [comment]
Hi @DylanORK, you need a Node.js version of at least `16` as mentioned in [the prerequisites](https://github.com/leon-ai/leon#prerequisites).

Feel free to reopen this issue if it is not solved.
