### ISSUE TITLE
dead link in the readme

### ISSUE THREAD

**Issue by JLuc** [leon-ai/leon#421]
The first important link in the readme, where after a long introduction i was supposed to learn "What is Leon able to do", is dead : https://github.com/leon-ai/leon/tree/develop/packages.

**Comment by amirziveh** [comment]
https://github.com/leon-ai/leon/tree/develop/skills

**Comment by ezzcodeezzlife** [comment]
just found the same problem 🚀

**Comment by louistiti** [comment]
Thanks, it has been fixed via https://github.com/leon-ai/leon/commit/54336cdd019a3b205183e6ac6736575f0ca6dd9b.
