### ISSUE TITLE
Packages link broken

### ISSUE THREAD

**Issue by rupeshs** [leon-ai/leon#423]
### Documentation Is:
https://github.com/leon-ai/leon/tree/develop/packages

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Explanation
Packages link broken (404 error)
### Proposal
Could you please update it.

**Comment by louistiti** [comment]
Thanks, it has been fixed via https://github.com/leon-ai/leon/commit/54336cdd019a3b205183e6ac6736575f0ca6dd9b.
