### ISSUE TITLE
/packages/ folder missing as linked by the docs

### ISSUE THREAD

**Issue by jondlove** [leon-ai/leon#424]
### Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [X] Not Sure?

### Explanation

I can't find the /packages/ folder in the source repo - i.e. https://github.com/leon-ai/leon/tree/develop/packages as linked from `README.md`, or https://github.com/leon-ai/leon/tree/master/packages as linked by https://docs.getleon.ai/packages-modules

I note that a bunch of files in that folder were deleted on the latest merge from develop (https://github.com/leon-ai/leon/commit/cb2db411ce4bd61042a37fc46708b395c0d3329c), so I'm not sure if the issue is outdated doc links, or an accidentally removed folder

**Comment by louistiti** [comment]
Hi @jondlove, thanks for saying. You can refer to [this link](https://github.com/leon-ai/leon/tree/develop/skills). Docs are not going to be updated until the official release as many things are coming up.
