### ISSUE TITLE
instaler leon

### ISSUE THREAD

**Issue by AstroAtom** [leon-ai/leon#434]
Bonjour, comment fait on pour installer leon avec un terminal zsh npm install --global @leon-ai/cli ne fonctionne pas chez moi (sous mac os). Merci d'avance

**Comment by louistiti** [comment]
Hi @AstroAtom, please use English.

Also provide more details. What error do you have when you run the `npm install --global @leon-ai/cli` command?
If you have an error at this stage, then I suggest you to read the Node.js/npm docs.

**Comment by louistiti** [comment]
Closing this as no answer has been provided and this issue isn't related to Leon.
