### ISSUE TITLE
the "Introduction" skill from the "Leon" domain is broken!

### ISSUE THREAD

**Issue by Twitfbiats** [leon-ai/leon#444]
i started leon , went to http://localhost:1337/ and talked but the voice input didn't seem to work so i typed some words instead and got these:

![image](https://user-images.githubusercontent.com/113786433/200118280-ed1a0749-6c19-4921-9d94-e5e93c803577.png)

![image](https://user-images.githubusercontent.com/113786433/200118374-d8651e1b-b858-421a-8628-3d986de0a0c1.png)

i checked the path, and it was correct, no files were missing.

**Comment by louistiti** [comment]
Hi @Twitfbiats, please:

1. Share the output of the `leon check` command.
2. Try the following: https://github.com/leon-ai/leon/issues/437#issuecomment-1295741481.
3. And share the report link here.

**Comment by Twitfbiats** [comment]
i first created a virtual environment for python3.9.10 and then ran leon check and this is the result:

![image](https://user-images.githubusercontent.com/113786433/200129771-5c57ce8c-678e-4093-8730-2ea0f90cc4d4.png)
![image](https://user-images.githubusercontent.com/113786433/200129822-3e60b556-a00c-40a3-9685-48e1bb38dbd6.png)

**Comment by Twitfbiats** [comment]
the report link for 2nd method: https://report.getleon.ai/raw/omesakiwix

**Comment by Twitfbiats** [comment]
leon check result of 2nd method: 

![image](https://user-images.githubusercontent.com/113786433/200131981-1835f77a-918d-4c27-bd7e-b2b60e702a37.png)
![image](https://user-images.githubusercontent.com/113786433/200132005-fe92d5db-369c-45c2-b689-c76bbbf24901.png)

**Comment by Twitfbiats** [comment]
i still got errors but i think the path of my pc that contains space is what caused the problem:

![image](https://user-images.githubusercontent.com/113786433/200132134-7caac14a-1441-42a9-882a-a384c9b16bdd.png)

**Comment by louistiti** [comment]
Hi @Twitfbiats, thanks for pointing this out. I have fixed the issue. You can retry by updating your Leon instance via the following command:

```bash
leon update --develop
```

**Comment by Twitfbiats** [comment]
it works now tks bro
