### ISSUE TITLE
TCP Won't Connect

### ISSUE THREAD

**Issue by JerryBerry12** [leon-ai/leon#447]
### Specs

- Leon version: 1.0.0-beta.7
- OS (or browser) version: Windows 11 x64
- Node.js version: 16.17.1
- Complete "leon check" (or "npm run check") output:
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### Expected Behavior
Works on server
### Actual Behavior
I get a flashing dot in browser and command line says trying to connect to tcp server

**Comment by louistiti** [comment]
Hi @JerryBerry12, please try the following and let us know how it goes:

```bash
npm install --global @leon-ai/cli@beta
leon create birth --develop
leon check
leon start
```

If it says that a Leon instance already exists after you've ran the create birth command, then do a `leon delete` and confirm the deletion.

**Comment by JerryBerry12** [comment]
hi @louistiti, sorry for the late response. i am getting this error
```
C:\Users\ *username*  \.leon\node_modules\@ffmpeg-installer\ffmpeg\index.js:42
    throw 'Could not find ffmpeg executable, tried "' + npm3Binary + '", "' + npm2Binary + '" and "' + topLevelBinary + '"';
    ^
Could not find ffmpeg executable, tried "C:\Users\BlueBinkSter\.leon\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe", "C:\Users\BlueBinkSter\.leon\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe" and "C:\Users\BlueBinkSter\.leon\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe"
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Error: Command failed with exit code 1: npm start
```
when i run the code `leon start`

**Comment by louistiti** [comment]
Interesting, can you delete the `node_modules` folder and the `package-lock.json` file and retry?

**Comment by JerryBerry12** [comment]
ok its deleting. Do you mean the whole process like 
```
npm install --global @leon-ai/cli@beta
leon create birth --develop
leon check
leon start
```
or just `leon start` ?

**Comment by JerryBerry12** [comment]
ok the folders are deleted. i ran leon create birth --develop and it is throwing out this
```
Error: C:\Users\  *username*  \.leon already exists, please provide another path.
```
when i run `leon info` it says that no leon instances are found.
Any suggestions?

**Comment by JerryBerry12** [comment]
OK it's Fixed! Let me tell you what I did.
1. I deleted .leon
2. I reran `leon create birth --develop`
When I run leon start, it takes 20-30 seconds to find the tcp server but it eventually does.
Thanks for your help!
p.s. I'm trying to set up stt and tts now...
-JerryBerry12

**Comment by ChuckNorrison** [comment]
> Interesting, can you delete the `node_modules` folder and the `package-lock.json` file and retry?

Delete of the node_modules folder broke my entire nodejs and npm. Cant even uninstall and reinstall it with apt. Do never ever delete this folder!
