### ISSUE TITLE
weather

### ISSUE THREAD

**Issue by JerryBerry12** [leon-ai/leon#448]
### Feature Use Case
what is the weather right now?
What will the weather be like tomorrow
show me hourly weather
weather
### Feature Proposal
show the weather from an open source API like openweathermap.org

**Comment by JerryBerry12** [comment]
Hello?
Is there anybody there?

**Comment by Divlo** [comment]
Hello! @JerryBerry12 
Sorry for the late reply.
It is already planned, and there is already an issue about weather: https://github.com/leon-ai/leon/issues/43.
Closing as it a duplicate issue.
