### ISSUE TITLE
Where does leon installed to

### ISSUE THREAD

**Issue by beew** [leon-ai/leon#461]
Hi, I would like to try out leon but I would like to know where the files are installed to and how to remove it if desired.

Also can I install it in my $HOME instead of system wide. I have sudo right though I try not to install experimental stuffs system wide if possible.

OS is Ubuntu 22.04.

Thanks.

**Comment by louistiti** [comment]
Hi, you can [read this](https://docs.getleon.ai/cli).

Basically, use `leon info` to see where your Leon instance is installed. And you can use `leon create birth --path YOUR_PATH` to create your instance at a specific location.

**Comment by beew** [comment]
Hi.

It seems that it is trying to install system wide.

When I ran (without sudo)

```
npm install --global @leon-ai/cli
```
It failed with this
```
ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

```

**Comment by 6b6279** [comment]
If you want to install leon only for the current user, use the `--prefix` flag, i.e. `npm --global install @leon-ai/cli --prefix ~/.local`
