### ISSUE TITLE
Won't understand basic prompts

### ISSUE THREAD

**Issue by ghsanti** [leon-ai/leon#464]
## Issue

Click on the Gitpod and ask "What is the Weather?", "How is the Weather?" etc. It wont understand it.

It seems either a bug or maybe there could be a list of prompts so that we can get started and see how it works? 

Also wouldn't understand basic questions like "Give me a random 4 digit number" or "Tell me 2 jokes" so I am not sure what to expect.

**Comment by cOborski** [comment]
This is not a bug. Leon does not currently give access to large language models; though, I believe that's on the roadmap. You'll have to create a skill to use before it will do anything.
