### ISSUE TITLE
HTTP Error 426

### ISSUE THREAD

**Issue by RealSourceOfficial** [leon-ai/leon#479]
### Specs

- Leon version: 1.0.0-beta.8+dev
- OS: 
  - System: Windows 10, build 10.0.19045
  - Browser: Firefox 112.0.1 (64-bit)
- Node.js version: 20.0.0
- Leon Check: https://gist.github.com/RealSourceOfficial/4bc49c8c5ae9ea685361e6bee652d693

### Expected Behavior
Leon accessible through Firefox

### Actual Behavior
Inaccessible with HTTP error 426

### Steps to reproduce
```js
npm install @leon-ai/cli@beta node-gyp-build
leon create birth --develop
leon start
```
Open localhost:1337 in browser

### What I've Tried
- Using CMD as administrator 
- Using NodeJS version 18.16.0 32bit & 18.16.0 64bit
- Using `npm start dev:server` & `npm start dev:app` in the `%appdata%\.leon` directory
- Using both leon base and leon beta
- Using Opera GX - LVL4 (core: 91.0.4516.106)

**Comment by louistiti** [comment]
Hi @RealSourceOfficial, thanks for the report. Let's follow up using this issue https://github.com/leon-ai/leon/issues/407.
