### ISSUE TITLE
Bridges

### ISSUE THREAD

**Issue by TheFehr** [leon-ai/leon#48]
Just a quick question how did you imagine Leon to decide which Bridge to call?

I have been tinkering on a go bridge, saddly that one only will work on mac OS and Llnux until golang fixes their plugin package to work with windows.

**Comment by louistiti** [comment]
Hello @TheFehr,

Thanks for opening this issue. I was thinking about an environment variable in the `.env` with something like `LEON_BRIDGE_TYPE` and according to the value of this env variable, Leon's brain executes the module dedicated to that specific language.

But that will be for later because I still need to work on the Leon's packages setup to make them work standalone without having to install all the Leon's packages belonging to other bridges (languages).

**Comment by TheFehr** [comment]
@louistiti but that would mean if there is an amazing weather package in python and a powerfull math package in golang I uld need to choose if I either want to be able to ask Leon about the weather or my math problems? (just naming random packages here)
Can't we give the users of leon the possibility to have multiple bridges at the same time? I know it will be way more complicated, but I for one would appreaciate the possibillty to mix packages from different bridges (languages) because for some usecases there are amazing libraries. But only in one language.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ New bridges](https://trello.com/c/z9lNNYKY/241-%E2%9C%A8-new-bridges)

**Comment by louistiti** [comment]
Indeed, and this is of course doable.

During his initialization, Leon can check if a bridge is correctly configured and ready to execute modules. According to that, he'll execute or not the requested module.
I'll see how to deal with priorities, two bridges might have the same module just rewritten in their respective language. But I suppose I'll add a "priority" property setting here that we could update as much as we want, such as: `LEON_FAVORITE_BRIDGES=python,go,javascript`, and according to the order of this value, Leon will know which bridge he needs to choose if the requested module has been found in several bridges.

**Comment by TheFehr** [comment]
Yeah I was thinking in the same direction, do you think you'll need to do more breaking changes on the code for the NLU improvement or could I give this a try and test it with my golang bridge?

**Comment by louistiti** [comment]
I would still prefer to wait for a while before doing that.

**Comment by TheFehr** [comment]
Okay, then I will just keep my golang bridge similar to your example python bridge, so when the time is right I can test it.

**Comment by louistiti** [comment]
Alright, do not hesitate if you have any questions.

**Comment by TheFehr** [comment]
For your information: on my fork of leon in the golang-bridge branch is a functional golang bridge including a golang version of the isitdown module.
To try it out you need this: https://gist.github.com/TheFehr/58dc8e204d2e5e8c5123b48757643fe4

Thanks for your amazing work

**Comment by louistiti** [comment]
It seems good. Thanks for sharing!

The roadmap card is already created to ensure that will be taken in consideration once we'll discuss about this topic later on.
