### ISSUE TITLE
Node.js Bridge

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#482]
The Node.js bridge will allow us to build new skills using JavaScript. The runtime entry point and pre-release process is already done. I've done it the same way as binaries made with Python so it is generic enough to not get into too much thinking when releasing a new version of the Node.js bridge.

The bridge should clearly be distinguished from the SDK at the file structure level.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.9] Node.js bridge](https://trello.com/c/z9lNNYKY/241-%E2%9C%A8-100-beta9-nodejs-bridge)

**Comment by nhusgf** [comment]
hello

**Comment by louistiti** [comment]
The Node.js SDK has been built. And the Node.js bridge has been developed too. It is now possible to develop skills using JavaScript! :tada:
