### ISSUE TITLE
Python Skill SDK

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#484]
Having an SDK will drastically improve the developer experience when building new skills with Python. It should be fully agnostic with the Node.js SDK.

The SDK should clearly be distinguished from the bridge at the file structure level.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.9] Leon Python Skill SDK](https://trello.com/c/Isk70luX/421-%E2%9C%A8-100-beta9-leon-python-skill-sdk)

**Comment by NiaSchim** [comment]
Good job. I believe in you!!

**Comment by TheAnalist** [comment]
I don't know much about leon, but maybe a mojo version of leon can be interesting

**Comment by louistiti** [comment]
> I don't know much about leon, but maybe a mojo version of leon can be interesting

Let's focus on Node.js and Python first. Then let's see for the superset later :smile:

**Comment by louistiti** [comment]
The Python SDK has been built. And the new version of the Python bridge has been compiled! :tada:
