### ISSUE TITLE
compatible with Mark II?

### ISSUE THREAD

**Issue by PackElend** [leon-ai/leon#486]
### Will Leon be compatible with Mark II / Neon AI
https://neon.ai/MycroftMarkII

**Comment by louistiti** [comment]
I don't know these two, so I can't say. All I can say is that Leon is supported on Linux AArch64, Linux x86_64, macOS ARM64, macOS x86_64, and Windows AMD64. It requires 4 GB of RAM and a few GB of disk space.

**Comment by PackElend** [comment]
thx for the quick feedback, so lets see how they compare (as soon as I have my Mark II)
