### ISSUE TITLE
Docker URL

### ISSUE THREAD

**Issue by gruessung** [leon-ai/leon#49]
### Question

If i use docker to deploy Leon it try to connect to localhost:1337.

Is it possible to give leon the correct URL and port?

**Comment by louistiti** [comment]
Hello @gruessung,

Thanks for opening this issue. During the installation process, Leon will duplicate the `.env.sample` file to a `.env` file.
As you can see in those files, you have several environment variables already setup such as:

```
# Server
LEON_SERVER_HOST=localhost
LEON_SERVER_PORT=1337

# Web app
LEON_WEBAPP_HOST=localhost
LEON_WEBAPP_PORT=4242
```

Try to edit the:
- `.env.sample` file
- `docker:run` script in the `package.json` file by replacing `1337:1337` to your new `LEON_SERVER_PORT`

Then execute `docker:build` and `docker:run`.

Let me know if that worked or not.

**Comment by louistiti** [comment]
I close this issue as the answer has been provided.
