### ISSUE TITLE
Adding transmission resuming at breaking point when downloading big file like TCP_Server 

### ISSUE THREAD

**Issue by xuguoliang1964** [leon-ai/leon#490]
### Expected Behavior
Download the big file smoothly

### Actual Behavior
When do "leon create birth", the process often stops at unfinished downloading TCP_SERVER.

### Proposal
If adding transmission resuming at breaking point when downloading big file like TCP_Server or giving user the option of download the big file separatley will help

![image](https://github.com/leon-ai/leon/assets/5945565/0a5bf35f-8b3f-4686-83c3-084f4d7d6e4c)

**Comment by louistiti** [comment]
Hi, thanks for your suggestion. The problem is due to the following: https://github.com/leon-ai/leon/issues/480#issuecomment-1537249268.

For the time being, we are not going to support resuming for this specific case.
