### ISSUE TITLE
Can't start leon after a successful check

### ISSUE THREAD

**Issue by xuguoliang1964** [leon-ai/leon#494]
### Specs

- Leon version:1.0.0-beta.9+dev
- OS (or browser) version:ubantu 20.0.4
- Node.js version:v18.16.0
- Complete "leon check" (or "npm run check") output:
- xu@xu-ThinkPad-Edge-E431:/home/leon-ai/leon$ sudo leon check

> leon@1.0.0-beta.9+dev check
> ts-node scripts/check.js

.: CHECKING :.
ℹ️  Leon version
✅ 1.0.0-beta.9+dev

ℹ️  Environment
✅ Free RAM: 11.98 | Total RAM: 15.44 GB
✅ {"type":"Linux","platform":"linux","arch":"x64","cpus":8,"release":"5.19.0-41-generic","osName":"Linux 5.19","distro":{"os":"linux","dist":"Ubuntu","codename":"jammy","release":"22.04"}}

ℹ️  node --version
✅ v18.16.0

ℹ️  npm --version
✅ 9.5.1

✅ Node.js bridge version: 0.0.1-alpha.0
ℹ️  Executing a skill...
ℹ️  /home/leon-ai/leon/node_modules/ts-node/dist/bin.js --swc bridges/nodejs/dist/bin/leon-nodejs-bridge.js "/home/leon-ai/leon/scripts/assets/nodejs-bridge-intent-object.json"
✅ [WIP] Node.js bridge 0.0.1-alpha.0
ℹ️  Skill execution time: 379ms

✅ Python bridge version: 1.0.1
ℹ️  Executing a skill...
ℹ️  bridges/python/dist/linux-x86_64/leon-python-bridge "/home/leon-ai/leon/scripts/assets/python-bridge-intent-object.json"
✅ {"domain": "leon", "skill": "random_number", "action": "run", "lang": "en", "utterance": "Give me a random number", "entities": [], "slots": {}, "output": {"type": "end", "codes": ["93"], "speech": "93", "core": {}, "options": {}}}
ℹ️  Skill execution time: 306ms

✅ TCP server version: 1.0.0
ℹ️  Starting the TCP server...
ℹ️  tcp_server/dist/linux-x86_64/leon-tcp-server en
✅ The TCP server can successfully start
ℹ️  TCP server startup time: 10218ms

ℹ️  Global resolvers NLP model state
✅ Found and valid

ℹ️  Skills resolvers NLP model state
✅ Found and valid

ℹ️  Main NLP model state
✅ Found and valid

ℹ️  Amazon Polly TTS
⚠️  Amazon Polly TTS is not yet configured

ℹ️  Google Cloud TTS/STT
⚠️  Google Cloud TTS/STT is not yet configured

ℹ️  Watson TTS
⚠️  Watson TTS is not yet configured

ℹ️  Offline TTS
✅ Found Flite at bin/flite/flite

ℹ️  Watson STT
⚠️  Watson STT is not yet configured

ℹ️  Offline STT
✅ Found Coqui language model at bin/coqui/huge-vocabulary.scorer

.: REPORT :.
ℹ️  Here is the diagnosis about your current setup
✅ Run
✅ Run skills
✅ Reply you by texting
✅ Start the TCP server
⚠️  Amazon Polly text-to-speech
⚠️  Google Cloud text-to-speech
⚠️  Watson text-to-speech
✅ Offline text-to-speech
⚠️  Google Cloud speech-to-text
⚠️  Watson speech-to-text
✅ Offline speech-to-text

✅ Hooray! Leon can run correctly
ℹ️  If you have some yellow warnings, it is all good. It means some entities are not yet configured

.: REPORT URL :.
ℹ️  Sending report...
✅ Report URL: https://report.getleon.ai/raw/hurufusolu

- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### Expected Behavior
run "leon start" successfully

### Actual Behavior
Bring up the message "Error: Command failed with exit code 1: npm start" and stopped

The whole message is as following:

xu@xu-ThinkPad-Edge-E431:/home/leon-ai/leon$ sudo leon start

> leon@1.0.0-beta.9+dev start
> cross-env LEON_NODE_ENV=production node server/dist/pre-check.js && node server/dist/index.js

.: PRE-CHECKING :.
ℹ️  Checking system requirements...
✅ Minimum required RAM: 4 GB | Free RAM: 12 | Total RAM: 15 GB
ℹ️  Checking voice configuration schemas...
✅ Voice configuration schemas checked
ℹ️  Checking global data schemas...
✅ Global data schemas checked
ℹ️  Checking skills data schemas...
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module 'skills/business_finance/domain.json'
Require stack:
- /home/leon-ai/leon/server/dist/helpers/skill-domain-helper.js
- /home/leon-ai/leon/server/dist/pre-check.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /home/leon-ai/leon/server/dist/helpers/skill-domain-helper.js:43:150
    at async /home/leon-ai/leon/server/dist/helpers/skill-domain-helper.js:43:47
    at async Promise.all (index 0)
    at async SkillDomainHelper.getSkillDomains (/home/leon-ai/leon/server/dist/helpers/skill-domain-helper.js:39:9)
    at async /home/leon-ai/leon/server/dist/pre-check.js:119:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/leon-ai/leon/server/dist/helpers/skill-domain-helper.js',
    '/home/leon-ai/leon/server/dist/pre-check.js'
  ]
}

Node.js v18.16.0
Error: Command failed with exit code 1: npm start

**Comment by louistiti** [comment]
Hi, can you please try to `git pull` to make sure all changes are up-to-date? Because I have fixed it a few days ago. Cf. https://github.com/leon-ai/leon/issues/492.

**Comment by xuguoliang1964** [comment]
Thank you, @louistiti . 

Leon start to work well after I do as you suggest: do 'git pull',  do 'leon create birth' to make a new instance of leon.  Then it works.

**Comment by louistiti** [comment]
Awesome, closing this issue.
