### ISSUE TITLE
Docker Install - no modules seems working v2019-03-04

### ISSUE THREAD

**Issue by rioukkevin** [leon-ai/leon#50]
Hello, 

I create this issue but the problem can be on my side ;), 
I install Leon on my ArchLinux with docker, The build and installation looks good, leon start on Leet's port ;) so when I want to speak with leon It looks like no modules work as we see on the screen capture :)
I think the problem can be on my side, I have archLinux with deepin and docker don't have the reputaton to work good on it :P, I create this issue because if an other person have the same problem as me He can add it to this issue ;) 
Don't see it as a big priority, I have a lot of time to see what you do ;) 
My english is not perfect as you can see, I speak better french than English but I work on ;)

![image](https://user-images.githubusercontent.com/45003887/53907096-bdf2aa00-404c-11e9-8144-2d35b8c93c21.png)

Have a Nice day and be happy !!!!

**Comment by pegeroad** [comment]
Hi, I have the same issue on Windows with Docker. Although in the log I can see, the preinstall and the other scripts can be ran since they are not found.

**Comment by rioukkevin** [comment]
I restart the installation tommorow, I can't see the logs today, I confirm if I have the same with preinstall scripts and the other ;)

**Comment by pegeroad** [comment]
I investigated further, the problem was that the user had no permissions to run the scripts inside the container..

**Comment by louistiti** [comment]
Hello @rioukkevin,

Thanks for opening this issue. To understand what is happening, could you please do the following:

1. Run: `npm run docker:build`
2. Run: `npm run docker:run`
3. Run: `docker logs -f <YOUR_CONTAINER>`
4. Send one message to Leon
5. Paste the full output of your terminal in a [Pastebin](https://pastebin.com/)
6. Share this Pastebin here

**Comment by bjadel** [comment]
Hi,

same problem here. I get the following error with docker logs -f ...

`
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/app/bridges/python/utils.py", line 11, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'
`

**Comment by rioukkevin** [comment]
Sorry, I don't find time yesterday :( Normally this evening I can reinstall Leon ;) and give you logs

**Comment by rioukkevin** [comment]
I restart from Scratch, here is the docker:build logs https://pastebin.com/5Te3MVA7 and now here the docker:run log https://pastebin.com/VyMHLfwB I make multiple request because the response don't look logic, With reinstall today and git update, no problem ;)

**Comment by louistiti** [comment]
Hello @bjadel,

Thanks for reporting. Could you please do [the following](https://github.com/leon-ai/leon/issues/50#issuecomment-470325702)?

@rioukkevin, alright, it looks good then. Some answers don't seem logic now simply because Leon needs new skills, but once he gets it, it'll be logic. Don't hesitate to suggest and contribute.

**Comment by rioukkevin** [comment]
Okay, perfect, I don't know python today, I'm going tout study it tout understand how module work ;) 
Have a nice day

**Comment by louistiti** [comment]
Alright, I spotted the issue and made a fix for that: https://github.com/leon-ai/leon/commit/c8a68ab02eec9ddaf803b6e36cd7e91a4989cdea.

While installing with Docker, if the `.env` file was already existing when Leon was processing to the `postinstall` script, then at the moment where it was asking to overwrite the `.env` file, Leon was directly quitting the process and was not continuing the installation. So Leon was not fully installed and was resulting to a broken one.
Leon was saying that he had errors with some of his modules when we were trying to talk to him, and there was the following error in the logs:
```
"File "bridges/python/main.py", line 4, in <module> import utils File "/app/bridges/python/utils.py", line 11, in <module> from tinydb import TinyDB, Query, operations ModuleNotFoundError: No module named 'tinydb'"
```

So for the folks who have this behavior when you run Leon inside Docker:
1. Git clone Leon from the latest develop commit
2. `npm run docker:build`
3. `npm run docker:run`
4. You should be ready to go

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.2] Leon is not fully installed if a .env file is already existing while building with Docker](https://trello.com/c/jeRpLC6A/244-%F0%9F%90%9E-100-beta2-leon-is-not-fully-installed-if-a-env-file-is-already-existing-while-building-with-docker)

**Comment by bjadel** [comment]
With beta2 release the problem is gone. Thanks
