### ISSUE TITLE
ToDoList package

### ISSUE THREAD

**Issue by ahmadrezash** [leon-ai/leon#52]
hi!
Thanks for your interest in Leon! ❤️
Leon can manage or task with a todo list.
It is can contain 3 list: ToDo/Doing/Done
And we tell him for example I should send email to my mother and tell him I sent email too my mom.
We can set lable for any task for importancy or set a deadline for them
And all task can depend on time.
Hey Leon I should read that article tomorrow
and additinal feature.
it's be great if anyone can implement
I start it in my fork project and merge it  

tnx for this project:)

**Comment by louistiti** [comment]
Hello @ahmadrezash,

Thanks for this suggestion. However, that is already in pending via [this issue](https://github.com/leon-ai/leon/issues/42), feel free to follow up there 😉
