### ISSUE TITLE
Cannot uninstall Leon

### ISSUE THREAD

**Issue by Korabel47** [leon-ai/leon#525]
Hey all.

I'm not able to uninstall leon-ai after its successful installation.
So far, I have tried the commands:
  - npm uninstall -g leon-ai
  - npm uninstall -g @leon-ai/cli@1.5.0
  - npm uninstall -g cli
Nothing worked. 

I would appreciate help with this issue.

### Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Explanation
I believe this information is needed, especially for those (like me) who aren't experienced in using **npm** package manager

### Proposal
Add the instructions to uninstall Leon AI to the documentation pages

**Comment by louistiti** [comment]
Hi, you can run the following commands:

```bash
# Delete Leon instance
leon delete --yes
# Uninstall Leon CLI
npm uninstall -g @leon-ai/cli
```

**Comment by Korabel47** [comment]
> Hi, you can run the following commands:
> 
> ```shell
> # Delete Leon instance
> leon delete --yes
> # Uninstall Leon CLI
> npm uninstall -g @leon-ai/cli
> ```

Thanks! It helped.

Should I still keep the issue open? This issue was created primarily regarding the documentation.

**Comment by louistiti** [comment]
The documentation will be rewritten for the official release :smiley:
