### ISSUE TITLE
NodeJS 22 install error

### ISSUE THREAD

**Issue by ghost** [leon-ai/leon#539]
The .nvmrc file specifies that the version to be used is `lts/*.
`, but since October 29, 2024, version 22 has been upgraded to LTS.

This leads to a problem when executing the `npm install` command, which is as follows:

```
import { LogHelper } from '@/helpers/log-helper
         ^^^^^^^^^
SyntaxError: The requested module '@/helpers/log-helper' does not provide an export named 'LogHelper'.
```

With some quick research I could see that some other projects had similar issues, but I couldn't identify a solution :/.

I think a change is needed in the future so that new contributors are not discouraged.

In any case, I'd like to thank you Louis for this project, which I discovered a few years ago. I'll try to help out in my spare time, as the PDA is the last barrier for those who want to do without proprietary solutions ^^.

**Comment by gagipro** [comment]
yes encountered same issue for the moment. need to wait a bit I suppose.

**Comment by ghost** [comment]
> yes encountered same issue for the moment. need to wait a bit I suppose.

You can downgrade to v20 of NodeJS. It works with this version.

**Comment by gagipro** [comment]
Ok will try

**Comment by gagipro** [comment]
> > yes encountered same issue for the moment. need to wait a bit I suppose.
> 
> You can downgrade to v20 of NodeJS. It works with this version.

I confirm it works with node v20.
Thanks a lot.

**Comment by ghost** [comment]
You're welcome ^^.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⬆️ [1.0.0-beta.10] Node.js 22](https://trello.com/c/KbTZhL2j/525-%E2%AC%86%EF%B8%8F-100-beta10-nodejs-22)

**Comment by louistiti** [comment]
Hi @Arthur-GYT @gagipro, thanks for the report.

I'm coming back to work on Leon, I [pushed a fix](https://github.com/leon-ai/leon/commit/0eeb9bb14141e746104df6eee7fbbc2d6e1f5dcc) on the `develop` branch to support Node.js 22. Can you please help try again?

**Comment by gagipro** [comment]
> Hi @Arthur-GYT @gagipro, thanks for the report.
> 
> I'm coming back to work on Leon, I [pushed a fix](https://github.com/leon-ai/leon/commit/0eeb9bb14141e746104df6eee7fbbc2d6e1f5dcc) on the `develop` branch to support Node.js 22. Can you please help try again?

Hello Louis, yes I will try as soon as I have finished my other preparation on other project.

Thanks a lot

**Comment by ghost** [comment]
It's good for me @louistiti. Thanks for your fix
