### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by ghost** [leon-ai/leon#540]
Hey ! With recent changes, when I upgrade to NodeJS 22, I have this error.

![screenshot-2024-11-18-12-45-09](https://github.com/user-attachments/assets/17392b4e-c127-4fa6-b1ad-131e3067b27f)

**Comment by ghost** [comment]
@louistiti I think it's related to ESM/CommonJS with recent changes on NodeJS 20+

**Comment by louistiti** [comment]
@Arthur-GYT hi, thanks for reporting. [I committed a fix,](https://github.com/leon-ai/leon/commit/ea8ba0f1fd3bd648f8d03724954257e875195cd5) can you please help to check?

**Comment by Arthur-GYT** [comment]
@louistiti I try to remove node_modules folder, reinstall nodejs version with nvm and I have the same error...

**Comment by Arthur-GYT** [comment]
My bad, I have this error when I remove server/dist directory

![screenshot-2024-11-20-15-18-37](https://github.com/user-attachments/assets/0b32cddd-5905-42d8-a673-0d819e2adb14)

**Comment by ghost** [comment]
It work fine now, Thanks louis ^^
