### ISSUE TITLE
snowboy

### ISSUE THREAD

**Issue by Ursus-Bear** [leon-ai/leon#57]

**Comment by Ursus-Bear** [comment]
Hi,

I'm trying to install the leon on offline mode via 'npm run setup:offline'. But I always get the error 'Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v67-linux-x64.tar.gz', and I tried to access the S3 by the url, i found it is true i haven't the permission. 
So could you help me to fix this error or should i install the snowboy by myself?Thanks!

**Comment by louistiti** [comment]
Hello @Ursus-Bear,

Thanks for opening this issue. Could you please tell me which Node.js version you are using?

You must use Node.js 8 to install and run the hotword detection as mentioned in [the docs](https://docs.getleon.ai/offline.html#hotword).

Let me know if that works.

**Comment by Ursus-Bear** [comment]
Hello @louistiti,

Thanks for your reply!
Yes, it works. But I also met another problem: when I visit the http://localhost:1337, I just saw the black background without anything. It seems something covers the client box.Looks like below.
![无标题](https://user-images.githubusercontent.com/7314727/54083367-49c24a00-435d-11e9-90c4-d3625ccee9de.png)

I don't know what's the root cause.

**Comment by louistiti** [comment]
Ensure that you use Node.js 10 when you launch Leon and Node.js 8 when you launch the hotword detection.

**Comment by louistiti** [comment]
I'll close that issue.

Feel free to reopen if it's still not fixed.
