### ISSUE TITLE
Python 3.7 failing in `npm run check`

### ISSUE THREAD

**Issue by OvermindDL1** [leon-ai/leon#6]
### Specs

- Leon version: Master 360d1020c4bd8bf1df3764645c635c64e0364702
- OS (or browser) version: Linux 4.4.0-140-generic
- Node.js version:  `node --version -> v11.1.0`
- Complete "npm run check" output:
```zsh
╰─➤  npm run check

> leon@1.0.0-beta.0 check /mnt/storage0/overminddl1/leon/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.1.0

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

✖ Error: Command failed: /bin/sh -c pipenv run python --version
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```
And yet running that command manually:
```zsh
╰─➤  /bin/sh -c 'pipenv run python --version'
Loading .env environment variables…
Python 3.7.2
```

### Expected Behavior

Python 3.7 should work.  Downgrading the system version is... not safe.

### Actual Behavior

`npm run check` is failing the python check.

### How Do We Reproduce?

Use the updated version of python.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⬆️ Upgrade to the latest Python version](https://trello.com/c/ezmGfIkL/216-%E2%AC%86%EF%B8%8F-upgrade-to-the-latest-python-version)

**Comment by louistiti** [comment]
Hello @OvermindDL1,

Thanks for your issue. Today Leon must have Python 3.6 to work. For a future Leon's version, Python will anyway be upgraded to the latest Python version on that moment.

I added it to this [roadmap card](https://trello.com/c/ezmGfIkL/216-%E2%AC%86%EF%B8%8F-upgrade-to-the-latest-python-version).

**Comment by OvermindDL1** [comment]
All good, it ended up running well in Docker.  :-)

It might be good to add a Dockerfile to the project with everything auto-acquired and so forth so someone can just `git clone ... && cd ... && docker build ...` and get a fully operational setup ready to go.  :-)

**Comment by louistiti** [comment]
As you already noticed there is a PR for Docker file #9.

Alright, I will close this issue then.

**Comment by Imperator26** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [⬆️ Upgrade to the latest Python version](https://trello.com/c/ezmGfIkL/216-%E2%AC%86%EF%B8%8F-upgrade-to-the-latest-python-version)

What do we need to do to support 3.7 as well?

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.3] Support for Python version >= 3](https://trello.com/c/Bg7Zl9Zf/288-%F0%9F%94%A7-100-beta3-support-for-python-version-3)

**Comment by louistiti** [comment]
The reason why I preferred to have one dedicated Python version was due to Leon modules writing and backward compatibility.

But finally by adding the `pipenv --three` command in the Leon setup process, Pipenv will ensure to take the latest Python 3 version available on the machine. Today, I believe OSes have quite recent Python versions and people usually setup the latest Python version when it is not already installed.

So, now Leon allow any Python 3 versions.

Does it make sense?

**Comment by Imperator26** [comment]
> The reason why I preferred to have one dedicated Python version was due to Leon modules writing and backward compatibility.
> 
> But finally by adding the `pipenv --three` command in the Leon setup process, Pipenv will ensure to take the latest Python 3 version available on the machine. Today, I believe OSes have quite recent Python versions and people usually setup the latest Python version when it is not already installed.
> 
> So, now Leon allow any Python 3 versions.
> 
> Does it make sense?

Makes sense to me

**Comment by louistiti** [comment]
Alright, I'm gonna close this issue then.

Feel free to reopen it or create a new one if necessary.
