### ISSUE TITLE
Add examples of possible queries to readme

### ISSUE THREAD

**Issue by pirate** [leon-ai/leon#65]
After browsing this project's README and Docs for 5 minutes, I still have no idea what Leon is actually used for.

Please provide some examples of things Leon can do in the README, so that readers landing on the project can quickly understand what types of problems it can help solve.

e.g. 

 - `Leon, set a timer for 25 minutes` -> `Ok, I'll message you in 25min`
 - `Leon, read me my last 3 messages from Brian` -> `Ok, here are your last 3 messages from Brian: ...`
 - `Leon, when is Juliana's birthday?` -> `Juliana's birthday is 1991 November 1st`

Even if Leon does not include these modules by default, please provide examples of queries one could build using Leon, with links to example usage and implementations.  Without these, new users have no context to understand how Leon can help solve problems in their life.

**Comment by louistiti** [comment]
Hello @pirate,

Thanks for opening that issue.

Today, the most interesting part is about his core and the way he can scale up. He is pretty young but can easily scale to have new features (packages/modules).
As mentioned in the docs, you can find what he is able to do by browsing the packages via [this link](https://github.com/leon-ai/leon/tree/develop/packages).

Also, I plan to implement some predefined templates and suggestions as you can see on [the roadmap](https://trello.com/c/zOYwgVnW/74-%E2%9C%A8-defined-templates-to-request).

There are a lot to do and I have lots of plan for Leon, don't hesitate to contribute if you want to.

**Comment by louistiti** [comment]
I'll close this issue as the answer has been provided.

**Comment by pirate** [comment]
Sure,  https://github.com/leon-ai/leon/tree/develop/packages actually perfectly answers my question.  My only suggestion is to link to that URL using the word "example" or "demo" or "usage" somewhere in the README so that newcomers can find it easily, as I never would have seen those examples had you not linked to it here.

**Comment by louistiti** [comment]
Indeed, it has been done via https://github.com/leon-ai/leon/commit/d558fc8b7c6494babf5dec799802227f77c33d8a.
