### ISSUE TITLE
Docker build failed.

### ISSUE THREAD

**Issue by 1-riverfish** [leon-ai/leon#67]
### Specs

- Leon version: master branch
- OS (or browser) version: linux
- Node.js version: 10.15.3
- Complete "npm run check" output:
- (optional) Leon package version:

Run in docker.
The command '/bin/sh -c npm install' returned a non-zero code: 137
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! leon@1.0.0-beta.1 docker:build: `docker build -t leonai/leon . --force-rm`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.1 docker:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-29T08_14_34_933Z-debug.log

**Comment by louistiti** [comment]
Hello @1-riverfish,

Thanks for this report.

The Docker `137` code seems to be related to an out of memory error. Try to attribute more RAM to your system before running it. [This post](https://samwize.com/2016/05/19/docker-error-returned-a-non-zero-code-137/) might help.

**Comment by 1-riverfish** [comment]
Thanks you @louistiti ,
I deployed leon on my banwagon server with only 512MB RAM.
Later i will try to deploy leon in my local host.

**Comment by louistiti** [comment]
Did you succeeded to make Leon worked on your Bandwagon server with 512MB RAM?

Feel free to close this issue if your issue is solved and don't hesitate to open a new one if you have any concerns.

**Comment by 1-riverfish** [comment]
Yes, I deployed it by following the post you give.
However,open http://39.105.38.48:1337 in browser,it seems wrong...
