### ISSUE TITLE
Seems not work

### ISSUE THREAD

**Issue by 1-riverfish** [leon-ai/leon#68]
### Question
I deployed it in docker and seems solved all problem. But open in the browser is as below
![](http://39.105.38.48/images/2019/03/30/leon-error.png)
And in the console, here is the error output
Failed to load resource: net::ERR_CONNECTION_REFUSED
main.js:367 Uncaught TypeError: Cannot read property 'error' of undefined
    at main.js:367
    at Request.callback (main.js:1716)
    at Request.crossDomainError (main.js:1733)
    at XMLHttpRequest.xhr.onreadystatechange (main.js:1808)

Thanks!

**Comment by louistiti** [comment]
Hello @1-riverfish,

Thanks for opening this issue. To understand what is happening, could you please do the following:

1. Run: `npm run docker:build`
2. Run: `npm run docker:run`
3. Run `docker container ls` and copy the ID of your container
4. Run: `docker logs -f <YOUR_CONTAINER_ID>`
5. Go http://localhost:1337 with your browser
6. Paste the full output of your terminal in a [Pastebin](https://pastebin.com/)
7. Share this Pastebin here

Somehow, it seems the client cannot connect to the server, so you should check further on your server side if Leon is correctly setup.

**Comment by 1-riverfish** [comment]
@louistiti 
I will try it later.
Thank you very much.

**Comment by louistiti** [comment]
I close this issue as an answer has been provided.
