### ISSUE TITLE
Have I Been Pwned Module

### ISSUE THREAD

**Issue by iifeoluwa** [leon-ai/leon#69]
### Feature Use Case
[ ✨ Checker Package - Have I Been Pwned module](https://trello.com/c/8zUohuMG/104-✨-checker-package-have-i-been-pwned-module)
### Feature Proposal
Have Leon check if an email address has been compromised using https://haveibeenpwned.com/API/v2.

**Comment by iifeoluwa** [comment]
Going to begin work on this once I get the go-ahead from @louistiti

**Comment by louistiti** [comment]
Hello @iifeoluwa,

Awesome! I'm looking forward to see the results.

Quick thing, it would be nice to let the user setup pre-defined email addresses in the `config.json`. In that way, when the user say: `Have I been pwned?`, then Leon will check the email addresses in the `config.json` and request the Have I Been Pwned API.
And if the user provides the email addresses in the query, like `Is my-email@tld.com has been pwned?` then Leon can extract the email addresse(s) (here `my-email@tld.com`) via the entities and pass them to the Have I Been Pwned API.

**Comment by iifeoluwa** [comment]
Hi @louistiti, thank you for the pointers.

 I'd like to clarify the email address in config part though. To the best of my knowledge, Leon doesn't ask for an email address at any part of the install process. Should the user be able to manually insert an email entry in the package's config file, or do we set it as another ENV variable that is read?

Setting as ENV variable might be much less appropriate though because, in cases where user wants to enter >1 email addresses, we'd have to start employing things like delimiting email addresses with special character which isn't all that great.

**Comment by louistiti** [comment]
Indeed Leon does not ask for any email address during setup. But if you take a look at [this part](https://docs.getleon.ai/packages-modules.html#configuration) of the docs, you can see that every package has their own configuration, in your case, the configuration is located in `packages/checker/config/config.json`. You will need to add a key `haveibeenpwned` in this file with a sub-key `emails` that contains the list of email addresses for example. So it should be something similar as that:

```json
{
  "isitdown": {
    "options": {}
  },
  "haveibeenpwned": {
    "emails": [
      "an-email@tld.com",
      "another@tld.com"
    ],
    "options": {}
  }
}
```

Leon should be able to find the email address in the query itself (e.g. `Is my-email@tld.com has been pwned?`). You can use the entities from your module file to extract the email addresses. You can take the Is It Down module as example as it extracts the domain names from the queries (cf. [here](https://github.com/leon-ai/leon/blob/develop/packages/checker/isitdown.py#L7)).

If the user does not provide any email addresses in the query, then Leon will request the Have I Been Pwned API with the email addresses he can find in the config file. You can easily grab a config property value via [utils.config()](https://docs.getleon.ai/packages-modules.html#config-key).

**Comment by iifeoluwa** [comment]
Hi @louistiti, I encountered some hiccup testing this module and was hoping you'd have some pointers.

Following the instructions in the docs, I tried running this;

`PIPENV_PIPFILE=bridges/python/Pipfile pipenv run python bridges/python/main.py en checker isitdown "Check github.com is up"`

But what I got was this error;

`Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/Users/ifeoluwa/Projects/forks/leon/bridges/python/utils.py", line 22, in <module>
    queryobjfile = open(queryobjectpath, 'r', encoding = 'utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'en'`

This is happening because `queryobjectpath` is set to `argv[1]` (which is `'en'`), and trying to open that as a directory, which it is not. Is there an error somewhere or am I missing something?

Thanks for your help!

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.2] Improve NLU for more detailed queries](https://trello.com/c/xrofGezn/150-%F0%9F%94%A7-100-beta2-improve-nlu-for-more-detailed-queries)

**Comment by louistiti** [comment]
I've recently updated the module execution from the Leon's brain. Leon now uses a file instead of using the args.

The standalone module execution works like this:

```bash
PIPENV_PIPFILE=bridges/python/Pipfile pipenv run python bridges/python/main.py server/src/query-object.sample.json
```

And the JSON file will depend of the module you are executing, so for the Is It Down module, it should looks like this:

```json
{
  "lang": "en",
  "package": "checker",
  "module": "isitdown",
  "query": "Check if github.com, mozilla.org and twitter.com are up",
  "entities": [
    {
      "sourceText": "github.com",
      "utteranceText": "github.com",
      "entity": "url",
      "resolution": {
        "value": "github.com"
      }
    },
    {
      "sourceText": "mozilla.org",
      "utteranceText": "mozilla.org",
      "entity": "url",
      "resolution": {
        "value": "mozilla.org"
      }
    },
    {
      "sourceText": "twitter.com",
      "utteranceText": "twitter.com",
      "entity": "url",
      "resolution": {
        "value": "twitter.com"
      }
    }
  ]
}
```

In your case, the entities that may be extracted from a query are email addresses. As Leon use NLP.js, the JSON entities array should look [like that](https://github.com/axa-group/nlp.js/blob/master/docs/builtin-entity-extraction.md#email-extraction).

I'll update the docs within one or two days.

**Comment by louistiti** [comment]
I've edited the docs, you can take a look [here](https://docs.getleon.ai/packages-modules.html#create-a-module) :smiley: 

Let me know if you have any questions.

**Comment by iifeoluwa** [comment]
Great, thanks!

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Checker Package - Have I Been Pwned Module](https://trello.com/c/8zUohuMG/104-%E2%9C%A8-checker-package-have-i-been-pwned-module)

**Comment by louistiti** [comment]
Done in https://github.com/leon-ai/leon/pull/80.
