### ISSUE TITLE
tinydb failure

### ISSUE THREAD

**Issue by OvermindDL1** [leon-ai/leon#7]
### Specs

- Leon version: * Master [360d102](https://github.com/leon-ai/leon/commit/360d1020c4bd8bf1df3764645c635c64e0364702)
- OS (or browser) version: Linux 4.4.0-140-generic
- Node.js version: `node --version -> v11.1.0`
- Complete "npm run check" output:
```zsh
╰─➤  npm run check     

> leon@1.0.0-beta.0 check /mnt/storage0/overminddl1/leon/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.1.0

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /mnt/storage0/overminddl1/leon/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.8

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
Traceback (most recent call last):                                                                                                    
  File "bridges/python/main.py", line 4, in <module>                                                                                  
    import utils                                                                                                                      
  File "/mnt/storage0/overminddl1/leon/leon/bridges/python/utils.py", line 11, in <module>                                            
    from tinydb import TinyDB, Query, operations                                                                                      
ModuleNotFoundError: No module named 'tinydb'                                                                                         
```

### Expected Behavior

Should not crash.

### Actual Behavior

See above in the check.  Relevant section:
```python
➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
Traceback (most recent call last):                                                                                                    
  File "bridges/python/main.py", line 4, in <module>                                                                                  
    import utils                                                                                                                      
  File "/mnt/storage0/overminddl1/leon/leon/bridges/python/utils.py", line 11, in <module>                                            
    from tinydb import TinyDB, Query, operations                                                                                      
ModuleNotFoundError: No module named 'tinydb'
```
Running the listed command manually has the same result

### How Do We Reproduce?

All I did was spool up a default python 3.6 + npm 11 docker image with a data directory of the git clone, ran `pip install pipenv`, ran `npm install`, ran `npm run check` and the above appeared.

**Comment by OvermindDL1** [comment]
Apparently the project doesn't like being first ran with python 3.7 then downgraded to 3.6, can't replicate it from a pure 3.6 setup.

**Comment by louistiti** [comment]
Hello @OvermindDL1,

Got it, thanks for your explanations BTW.

**Comment by goodwinfame** [comment]
same problem,
the original python3 on my os was 3.5.
I upgraded to 3.6 and then install leon,
when I run check, throws the same error.

**Comment by Shrubhog** [comment]
I am experiencing the same error, but the fix is not working. I have tried every method of installing tinydb, and my pipenv is at 3.6 before I even run `npm install`

**Comment by louistiti** [comment]
Hello @goodwinfame @Shrubhog,

Please paste the output of your `npm run check`.

**Comment by Shrubhog** [comment]
https://pastebin.com/QSQNJPF6
I have since switched to @Antoinebr's Docker image, and the problem did not occur. It was either a system problem or a PEBCAK.

**Comment by louistiti** [comment]
I guess this is because the Python modules were installed under another env. Once you have the correct prerequisites, maybe a `npm run postinstall` could help as it will install the Python modules.

**Comment by goodwinfame** [comment]
@louistiti thanks very much, `npm run postinstall` did work.

**Comment by mbwhite** [comment]
As a reference I had exactly the same issue - and I think it was triggered by dropping back to python3.6 from python3.7.

My solution was to clean out the the python venv and reinstall the python3-distutils

```
rm -rf bridges/python/.env
sudo apt-get install python3-distutils
```
