### ISSUE TITLE
Leon closing unexpectedly

### ISSUE THREAD

**Issue by sobrinho** [leon-ai/leon#70]
### Specs

- Leon version: 1.0.0-beta.1
- OS (or browser) version: Chrome (MacOS Mojave)
- Node.js version: v11.10.0
- Complete "npm run check" output: 

```
λ npm rum check

> leon@1.0.0-beta.1 check /Users/sobrinho/Developer/opensource/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.10.0

➡ /bin/sh -c npm --version
✔ 6.7.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /Users/sobrinho/Developer/opensource/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.5

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 61, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
✔ Configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
✔ Found DeepSpeech language model at bin/deepspeech/lm.binary

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
✔ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
```

- (optional) Leon package version:

### Expected Behavior

If something fail, Leon must recover itself.

### Actual Behavior

Something happened and Leon closed unexpectedly (nothing seemed to have failed in the interface).

### How Do We Reproduce?

I have no idea but probably we can do that by manually throwing the error in the same spot to figure out.

![Screen Shot 2019-04-01 at 09 22 32](https://user-images.githubusercontent.com/26460/55327322-3720c980-5460-11e9-9f4f-074c50ad6129.png)

### Extra (like a sample repo to reproduce the issue, etc.)

**Comment by louistiti** [comment]
Hello @sobrinho,

Thanks for reporting.

For such behaviors, I prefer to throw exceptions today (it might change in the future depending of the severity of the exception itself). Here it seems your AWS TTS is failing somehow. Are you sure you provided the right AWS settings? Maybe you can try it standalone on the AWS side.

**Comment by louistiti** [comment]
I close this issue as an answer has been provided.
