### ISSUE TITLE
npm run setup:offline is not working

### ISSUE THREAD

**Issue by sobrinho** [leon-ai/leon#71]
### Specs

- Leon version: 1.0.0-beta.1
- OS (or browser) version: MacOS Mojave
- Node.js version: v11.10.0
- Complete "npm run check" output:
- (optional) Leon package version:

### Expected Behavior

Setup offline packages.

### Actual Behavior

![Screen Shot 2019-04-01 at 09 42 00](https://user-images.githubusercontent.com/26460/55328342-87009000-5462-11e9-8f23-2e02b3c45446.png)

### How Do We Reproduce?

npm run setup:offline

**Comment by louistiti** [comment]
Hello @sobrinho,

Thanks for reporting. It seems you are using Node.js 11+, whereas you must use Node.js 8 only to setup and run the hotword node. You can find the docs [over here](https://docs.getleon.ai/offline.html#hotword).

**Comment by sobrinho** [comment]
Node 8 makes the hotword works but makes the Leon itself to not work.

This is the supposed way to go?

**Comment by louistiti** [comment]
No, you need to use Node.js 8 to install and execute the hotword process and Node.js 10+ to launch Leon. This is why in the link I shared in my previous post there is a tip recommending you to "Use [nvm](https://docs.getleon.ai/how-to/#how-to-install-node-js) to easily switch between your Node.js versions." 😉

**Comment by sobrinho** [comment]
Cool, it worked.

Any chance to make both works in the same node version? I'm using nvm but it is odd to use two versions for one project.

I'm not really a node developer and I haven't researched Leon's code yet so I'm not aware of all details but is this feasible or something that we shouldn't be looking at all?

**Comment by louistiti** [comment]
I'm happy it worked.

Unfortunately I've already tried to find a workaround and it seems to be the only way I know until now. 

However, it seems there is [a PR](https://github.com/Kitt-AI/snowboy/pull/537) for that on the Snowboy GitHub repository. Let's watch it and update it once they merged it. If it takes too long time, I'll consider doing a fork.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⬆️ Upgrade hotword node to support > Node.js 8](https://trello.com/c/esdXJR8m/254-%E2%AC%86%EF%B8%8F-upgrade-hotword-node-to-support-nodejs-8)

**Comment by louistiti** [comment]
A Snowboy version has been [released](https://github.com/Kitt-AI/snowboy/pull/537#issuecomment-497992487) to support Node.js 8+ :tada: 

So I've made the changes for Leon (cf. https://github.com/leon-ai/leon/commit/b2a897032f3f3e594c9be5c0d3b0667f701e2bfa; https://github.com/leon-ai/leon/commit/5a7d369122d4d069d67b949d9e814a7e85d72ca2; https://github.com/leon-ai/docs.getleon.ai/commit/9ae2e8b9cb2587c7098982b6eb8c09eae487587f; https://github.com/leon-ai/docs.getleon.ai/commit/c623ddcc79ab1d2449b55bab8d2ee3682d3840f7). We don't need to use Node.js 8 anymore for that hotword node.

Also, I've reintroduced the `setup:offline` npm script as we can now setup all of the offline nodes in a row.

Feel free to reopen this issue if you think it's necessary.

**Comment by opeth646** [comment]
I'm still getting the same error, tried different node versions

**Comment by madindehead** [comment]
I'm seeing the same error here. 

Just to add, the docs say to use npm, but I found that I had to use leon to configure the offline STT and TTS.
