### ISSUE TITLE
Python && python3

### ISSUE THREAD

**Issue by marrodeur** [leon-ai/leon#72]
Bonsoir, c'est difficile de mettre ce léon en place, mais je vais y arriver.
J'ai un petit problème avec ce python et python3, léon ne detecte pas mon python3 (lors du check) car sur la derniere version derbian la version 2 est toujours utilisé. (Je ne suis pas un pro de linux). Donc suivant les forums on deconseil de remplacer python2 par python3 par defaut. Pourquoi est-ce que léon ne va pas chercher lui meme sa version lorsque les deux sont installés sur la machine? (c'est un detail, voir au mieux une idee).
Bon je pense que je peux laisser python (python2) sur mon systeme et configurer léon pour qu'il utilise python3 a la place. Quel est le finchier de conf a modifier pour faire ca, si c'est possible

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.13.0

➡ /bin/sh -c npm --version
✔ 6.7.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/odroid/leon

➡ /bin/sh -c pipenv run python --version
✖ 
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/home/odroid/leon/bridges/python/utils.py", line 6, in <module>
    from pathlib import Path
ImportError: No module named pathlib

```
odroid@odroid:~$ python --version
Python 2.7.15rc1
odroid@odroid:~$ python3 --version
Python 3.6.7
```

Merci pour ton aide et ton projet que j'ai franchement hâte de tester.

**Comment by louistiti** [comment]
Hello @marrodeur,

*English translation*

Thanks for opening this issue.

Maybe you can take a look [here](https://docs.getleon.ai/how-to/#how-to-install-python) about how to install Python via pyenv.
Otherwise, you could create a Python alias such as `alias python=python3` and paste it in your `.bashrc` file (further info [over here](https://askubuntu.com/a/321000)).

Thanks for supporting!

--

*Traduction française*

Merci d'avoir ouvert cette issue.

Je te conseille de regarder du côté de [pyenv](https://docs.getleon.ai/fr-FR/how-to/#comment-installer-python) afin d'installer et de gérer tes installations Python.
Sinon tu peux créer un alias tel que `alias python=python3` et coller ceci dans ton fichier `.bashrc` (pour plus d'informations, je t'invite à regarder [ici](https://askubuntu.com/a/321000)).

Merci pour ton soutien !

**Comment by marrodeur** [comment]
Ok merci , j'ai essayé les deux méthodes, mais non. Marche pas. Il faut installer leon avec python3 ou l'on peux changer python et python3 apres l'installe. C'est pas explicite pour moi. J'ai essayer de faire un sudo nano pour modifier le bach avec la technique de l'alias mais apres redemarrage c'est revenu sur python2. c'est chiant.(Apres je suis pas né linuxien je viens plus du coté windows) je comprend pas tout.

**Comment by louistiti** [comment]
*English translation*

Please give me the output of:

```bash
cd bridges/python
pipenv run python --version
```

--

*Traduction française*

Merci de me donner le résultat de ceci :

```bash
cd bridges/python
pipenv run python --version
```

**Comment by marrodeur** [comment]
root@odroid:~# cd bridges/python
-bash: cd: bridges/python: No such file or directory
root@odroid:~# pipenv run python --version
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /root/Pipfile
Using /usr/bin/python (2.7.15rc1) to create virtualenv...
? Creating virtual environment...Already using interpreter /usr/bin/python
New python executable in /root/.local/share/virtualenvs/root-BuDEOXnJ/bin/python
Installing setuptools, pip, wheel...
done.

OK Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/root-BuDEOXnJ
Creating a Pipfile for this project...
Python 2.7.15rc1

**Comment by louistiti** [comment]
You need to go to the `bridges/python` directory from the Leon project root, then run `pipenv run python --version`.

**Comment by marrodeur** [comment]
Ok je comprend.

`root@odroid:/leon/bridges/python# pipenv run python --version
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /leon/bridges/python/Pipfile
Using /usr/bin/python3 (3.6.7) to create virtualenv...
? Creating virtual environment...Using base prefix '/usr'
New python executable in /leon/bridges/python/.venv/bin/python3
Also creating executable in /leon/bridges/python/.venv/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3

OK Successfully created virtual environment!
Virtualenv location: /leon/bridges/python/.venv
Python 3.6.7
root@odroid:/leon/bridges/python#`

**Comment by louistiti** [comment]
OK, then now, from the project root directory, do:

1. `npm install`
2. `npm run check`

And paste the result here.

**Comment by marrodeur** [comment]
Non pas bon 

```
---

.: CHECKING :.

? /bin/sh -c node --version
? v11.13.0

? /bin/sh -c npm --version
? 6.9.0

? /bin/sh -c pipenv --version
? pipenv, version 2018.11.26

? /bin/sh -c pipenv --where
? /leon

? /bin/sh -c pipenv run python --version
?
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads

? /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
? Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/leon/bridges/python/utils.py", line 6, in <module>
    from pathlib import Path
ImportError: No module named pathlib



? Classifier state
? Classifier not found or broken. Try to generate a new one: "npm run train expressions"

? Amazon Polly TTS
? Amazon Polly TTS is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/amazon.json'

? Google Cloud TTS/STT
? Google Cloud TTS/STT is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/google-cloud.json'

? Watson TTS
? Watson TTS is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/watson-tts.json'

? Offline TTS
? Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

? Watson STT
? Watson STT is not yet configured: Error: ENOENT: no such file or directory, open 'server/src/config/voice/watson-stt.json'
? Offline STT
? Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

? Here is the diagnosis about your current setup
? Run
? Run modules
? Reply you by texting
? Amazon Polly text-to-speech
? Google Cloud text-to-speech
? Watson text-to-speech
? Offline text-to-speech
? Google Cloud speech-to-text
? Watson speech-to-text
? Offline speech-to-text

? Please fix the errors above
root@odroid:/leon# python --version
Python 3.6.7
root@odroid:/leon#
```

**Comment by louistiti** [comment]
Please paste the result of: `npm run postinstall`

**Comment by marrodeur** [comment]
Si j'ai bien compris c'est que leon ne se lance pas ou ne fonctionne pas avec la bonne version de python? C'est python2 qui est solicité au lieu du 3?
On ne peux pas dire à leon d'utiliser python3 en modifiant le fichier de configuration?

**Comment by marrodeur** [comment]
```
root@odroid:/leon# npm run postinstall

> leon@1.0.0-beta.1 postinstall /leon
> babel-node scripts/setup/setup.js

? .env file creation...
? .env file created
? Configuring core...
? google-drive.json file created
? amazon.json file created
? google-cloud.json file created
? watson-stt.json file created
? watson-tts.json file created
? Setting-up packages configuration...
? "Checker" package configuration file created
? "Leon" package configuration file created
? "Videodownloader" package configuration file created
? Packages configured
? Checking Python env...
? bridges/python/Pipfile found
? Pipenv 2018.11.2 version found
? Installing Python packages from bridges/python/Pipfile.lock...
? Python packages installed
? Training "Checker" package modules expressions...
? "Isitdown" module expressions trained
? Training "Leon" package modules expressions...
? "Whoami" module expressions trained
? "Joke" module expressions trained
? "Greeting" module expressions trained
? "Welcome" module expressions trained
? "Meaningoflife" module expressions trained
? "Randomnumber" module expressions trained
? "Bye" module expressions trained
? "Partnerassistant" module expressions trained
? Training "Videodownloader" package modules expressions...
? "Youtube" module expressions trained
? Classifier saved in server/src/data/expressions/classifier.json

? Hooray! Leon is installed and ready to go!
root@odroid:/leon#
```

**Comment by marrodeur** [comment]
J'avance:

```
root@odroid:/leon# python --version
Python 3.6.7
root@odroid:/leon# npm run check

> leon@1.0.0-beta.1 check /leon
> babel-node scripts/run-check.js

?
---

.: CHECKING :.

? /bin/sh -c node --version
? v11.13.0

? /bin/sh -c npm --version
? 6.9.0

? /bin/sh -c pipenv --version
? pipenv, version 2018.11.26

? /bin/sh -c pipenv --where
? /leon/bridges/python

? /bin/sh -c pipenv run python --version
? Python 3.6.7

? /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
? {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 12, "options": {}}}

? Classifier state
? Found and valid

? Amazon Polly TTS
? Amazon Polly TTS is not yet configured

? Google Cloud TTS/STT
? Google Cloud TTS/STT is not yet configured

? Watson TTS
? Watson TTS is not yet configured

? Offline TTS
? Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

? Watson STT
? Watson STT is not yet configured

? Offline STT
? Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

? Here is the diagnosis about your current setup
? Run
? Run modules
? Reply you by texting
? Amazon Polly text-to-speech
? Google Cloud text-to-speech
? Watson text-to-speech
? Offline text-to-speech
? Google Cloud speech-to-text
? Watson speech-to-text
? Offline speech-to-text

? Hooray! Leon can run correctly
? If you have some yellow warnings, it is all good. It means some entities are not yet configured
root@odroid:/leon# npm run build

> leon@1.0.0-beta.1 build /leon
> npm run lint && npm run build:app && npm run build:server


> leon@1.0.0-beta.1 lint /leon
> babel-node scripts/lint.js

? Linting...
? Looks great

> leon@1.0.0-beta.1 build:app /leon
> babel-node scripts/app/run-build-app.js

? Web app built

> leon@1.0.0-beta.1 build:server /leon
> npm run delete-dist:server && npm run train expressions && babel ./server/src -d ./server/dist --copy-files && shx mkdir -p server/dist/tmp


> leon@1.0.0-beta.1 delete-dist:server /leon
> shx rm -rf ./server/dist


> leon@1.0.0-beta.1 train /leon
> babel-node scripts/run-train.js "expressions"

? Training "Checker" package modules expressions...
? "Isitdown" module expressions trained
? Training "Leon" package modules expressions...
? "Whoami" module expressions trained
? "Joke" module expressions trained
? "Greeting" module expressions trained
? "Welcome" module expressions trained
? "Meaningoflife" module expressions trained
? "Randomnumber" module expressions trained
? "Bye" module expressions trained
? "Partnerassistant" module expressions trained
? Training "Videodownloader" package modules expressions...
? "Youtube" module expressions trained
? Classifier saved in server/src/data/expressions/classifier.json
server/src/api/downloads/download.controller.js -> server/dist/api/downloads/download.controller.js
server/src/api/downloads/download.routes.js -> server/dist/api/downloads/download.routes.js
server/src/api/info/info.controller.js -> server/dist/api/info/info.controller.js
server/src/api/info/info.routes.js -> server/dist/api/info/info.routes.js
server/src/core/asr.js -> server/dist/core/asr.js
server/src/core/brain.js -> server/dist/core/brain.js
server/src/core/nlu.js -> server/dist/core/nlu.js
server/src/core/server.js -> server/dist/core/server.js
server/src/core/synchronizer.js -> server/dist/core/synchronizer.js
server/src/helpers/date.js -> server/dist/helpers/date.js
server/src/helpers/loader.js -> server/dist/helpers/loader.js
server/src/helpers/log.js -> server/dist/helpers/log.js
server/src/helpers/os.js -> server/dist/helpers/os.js
server/src/helpers/string.js -> server/dist/helpers/string.js
server/src/index.js -> server/dist/index.js
server/src/middleware/cors.js -> server/dist/middleware/cors.js
server/src/middleware/other.js -> server/dist/middleware/other.js
server/src/stt/deepspeech/parser.js -> server/dist/stt/deepspeech/parser.js
server/src/stt/google-cloud-stt/parser.js -> server/dist/stt/google-cloud-stt/parser.js
server/src/stt/stt.js -> server/dist/stt/stt.js
server/src/stt/watson-stt/parser.js -> server/dist/stt/watson-stt/parser.js
server/src/tts/amazon-polly/synthesizer.js -> server/dist/tts/amazon-polly/synthesizer.js
server/src/tts/flite/synthesizer.js -> server/dist/tts/flite/synthesizer.js
server/src/tts/google-cloud-tts/synthesizer.js -> server/dist/tts/google-cloud-tts/synthesizer.js
server/src/tts/tts.js -> server/dist/tts/tts.js
server/src/tts/watson-tts/synthesizer.js -> server/dist/tts/watson-tts/synthesizer.js
root@odroid:/leon# npm start

> leon@1.0.0-beta.1 start /leon
> cross-env LEON_NODE_ENV=production node ./server/dist/index.js


/leon/node_modules/@ffmpeg-installer/ffmpeg/index.js:14
    throw 'Unsupported platform/architecture: ' + platform;
    ^
Unsupported platform/architecture: linux-arm
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.1 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-04T13_36_25_944Z-debug.log
root@odroid:/leon#
```

**Comment by marrodeur** [comment]
_logs 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle leon@1.0.0-beta.1~prestart: leon@1.0.0-beta.1
6 info lifecycle leon@1.0.0-beta.1~start: leon@1.0.0-beta.1
7 verbose lifecycle leon@1.0.0-beta.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle leon@1.0.0-beta.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/l$
9 verbose lifecycle leon@1.0.0-beta.1~start: CWD: /leon
10 silly lifecycle leon@1.0.0-beta.1~start: Args: [ '-c',
10 silly lifecycle   'cross-env LEON_NODE_ENV=production node ./server/dist/index.js' ]
11 silly lifecycle leon@1.0.0-beta.1~start: Returned: code: 1  signal: null
12 info lifecycle leon@1.0.0-beta.1~start: Failed to exec start script
13 verbose stack Error: leon@1.0.0-beta.1 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:$
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid leon@1.0.0-beta.1
15 verbose cwd /leon
16 verbose Linux 4.14.107-157
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v11.13.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error leon@1.0.0-beta.1 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
22 error Exit status 1
23 error Failed at the leon@1.0.0-beta.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by louistiti** [comment]
Your Leon was not correctly installed, it seems the `npm run postinstall` helped to move forward.

Can you give me the specs of your OS?

**Comment by marrodeur** [comment]
https://wiki.odroid.com/odroid-xu4/odroid-xu4

**Comment by louistiti** [comment]
It seems the this FFMPEG Node.js binding does not support ARM architectures as we can see here https://github.com/kribblo/node-ffmpeg-installer/issues/22.

This is something I'll need to investigate later on to support such architectures.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 Compatibility with ARM architectures and test on Pis](https://trello.com/c/CxRNbLHQ/256-%F0%9F%94%A7-compatibility-with-arm-architectures-and-test-on-pis)

**Comment by louistiti** [comment]
I'm gonna close this issue as the original topic has been answered.

**Comment by marrodeur** [comment]
Ok je peux essayer sur un RPI1B?

**Comment by louistiti** [comment]
You can try, but not sure if it'll work.

Please open another issue related to the result you got. We'll need to work on it later.

Which kind of hardware similar as a Raspberry Pi do you have with you? I'll help to have feedback regarding that :smiley:

**Comment by marrodeur** [comment]
Juste ces deux machines la.
Merci je reviendrais faire un rapporta ce sujet. ;D

**Comment by louistiti** [comment]
It looks like Leon works on Raspberry Pi 3B+ as per [this comment](https://github.com/leon-ai/leon/issues/37#issuecomment-803709534).

**Comment by samarthsikotara** [comment]
> J'avance:
> 
> ```
> root@odroid:/leon# python --version
> Python 3.6.7
> root@odroid:/leon# npm run check
> 
> > leon@1.0.0-beta.1 check /leon
> > babel-node scripts/run-check.js
> 
> ?
> ---
> 
> .: CHECKING :.
> 
> ? /bin/sh -c node --version
> ? v11.13.0
> 
> ? /bin/sh -c npm --version
> ? 6.9.0
> 
> ? /bin/sh -c pipenv --version
> ? pipenv, version 2018.11.26
> 
> ? /bin/sh -c pipenv --where
> ? /leon/bridges/python
> 
> ? /bin/sh -c pipenv run python --version
> ? Python 3.6.7
> 
> ? /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
> ? {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 12, "options": {}}}
> 
> ? Classifier state
> ? Found and valid
> 
> ? Amazon Polly TTS
> ? Amazon Polly TTS is not yet configured
> 
> ? Google Cloud TTS/STT
> ? Google Cloud TTS/STT is not yet configured
> 
> ? Watson TTS
> ? Watson TTS is not yet configured
> 
> ? Offline TTS
> ? Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"
> 
> ? Watson STT
> ? Watson STT is not yet configured
> 
> ? Offline STT
> ? Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"
> 
> ---
> 
> .: REPORT :.
> 
> ? Here is the diagnosis about your current setup
> ? Run
> ? Run modules
> ? Reply you by texting
> ? Amazon Polly text-to-speech
> ? Google Cloud text-to-speech
> ? Watson text-to-speech
> ? Offline text-to-speech
> ? Google Cloud speech-to-text
> ? Watson speech-to-text
> ? Offline speech-to-text
> 
> ? Hooray! Leon can run correctly
> ? If you have some yellow warnings, it is all good. It means some entities are not yet configured
> root@odroid:/leon# npm run build
> 
> > leon@1.0.0-beta.1 build /leon
> > npm run lint && npm run build:app && npm run build:server
> 
> 
> > leon@1.0.0-beta.1 lint /leon
> > babel-node scripts/lint.js
> 
> ? Linting...
> ? Looks great
> 
> > leon@1.0.0-beta.1 build:app /leon
> > babel-node scripts/app/run-build-app.js
> 
> ? Web app built
> 
> > leon@1.0.0-beta.1 build:server /leon
> > npm run delete-dist:server && npm run train expressions && babel ./server/src -d ./server/dist --copy-files && shx mkdir -p server/dist/tmp
> 
> 
> > leon@1.0.0-beta.1 delete-dist:server /leon
> > shx rm -rf ./server/dist
> 
> 
> > leon@1.0.0-beta.1 train /leon
> > babel-node scripts/run-train.js "expressions"
> 
> ? Training "Checker" package modules expressions...
> ? "Isitdown" module expressions trained
> ? Training "Leon" package modules expressions...
> ? "Whoami" module expressions trained
> ? "Joke" module expressions trained
> ? "Greeting" module expressions trained
> ? "Welcome" module expressions trained
> ? "Meaningoflife" module expressions trained
> ? "Randomnumber" module expressions trained
> ? "Bye" module expressions trained
> ? "Partnerassistant" module expressions trained
> ? Training "Videodownloader" package modules expressions...
> ? "Youtube" module expressions trained
> ? Classifier saved in server/src/data/expressions/classifier.json
> server/src/api/downloads/download.controller.js -> server/dist/api/downloads/download.controller.js
> server/src/api/downloads/download.routes.js -> server/dist/api/downloads/download.routes.js
> server/src/api/info/info.controller.js -> server/dist/api/info/info.controller.js
> server/src/api/info/info.routes.js -> server/dist/api/info/info.routes.js
> server/src/core/asr.js -> server/dist/core/asr.js
> server/src/core/brain.js -> server/dist/core/brain.js
> server/src/core/nlu.js -> server/dist/core/nlu.js
> server/src/core/server.js -> server/dist/core/server.js
> server/src/core/synchronizer.js -> server/dist/core/synchronizer.js
> server/src/helpers/date.js -> server/dist/helpers/date.js
> server/src/helpers/loader.js -> server/dist/helpers/loader.js
> server/src/helpers/log.js -> server/dist/helpers/log.js
> server/src/helpers/os.js -> server/dist/helpers/os.js
> server/src/helpers/string.js -> server/dist/helpers/string.js
> server/src/index.js -> server/dist/index.js
> server/src/middleware/cors.js -> server/dist/middleware/cors.js
> server/src/middleware/other.js -> server/dist/middleware/other.js
> server/src/stt/deepspeech/parser.js -> server/dist/stt/deepspeech/parser.js
> server/src/stt/google-cloud-stt/parser.js -> server/dist/stt/google-cloud-stt/parser.js
> server/src/stt/stt.js -> server/dist/stt/stt.js
> server/src/stt/watson-stt/parser.js -> server/dist/stt/watson-stt/parser.js
> server/src/tts/amazon-polly/synthesizer.js -> server/dist/tts/amazon-polly/synthesizer.js
> server/src/tts/flite/synthesizer.js -> server/dist/tts/flite/synthesizer.js
> server/src/tts/google-cloud-tts/synthesizer.js -> server/dist/tts/google-cloud-tts/synthesizer.js
> server/src/tts/tts.js -> server/dist/tts/tts.js
> server/src/tts/watson-tts/synthesizer.js -> server/dist/tts/watson-tts/synthesizer.js
> root@odroid:/leon# npm start
> 
> > leon@1.0.0-beta.1 start /leon
> > cross-env LEON_NODE_ENV=production node ./server/dist/index.js
> 
> 
> /leon/node_modules/@ffmpeg-installer/ffmpeg/index.js:14
>     throw 'Unsupported platform/architecture: ' + platform;
>     ^
> Unsupported platform/architecture: linux-arm
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! leon@1.0.0-beta.1 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the leon@1.0.0-beta.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-04-04T13_36_25_944Z-debug.log
> root@odroid:/leon#
> ```

For me npm install --save @ffmpeg-installer/ffmpeg works!

**Comment by louistiti** [comment]
Hi, this month we have been working on compiling all Python stuff related upfront. Meaning, Leon does not need Python at runtime anymore.

Please try the three following commands and let's see how it goes and paste the report URL:

```bash
# Install the beta version of the Leon CLI
npm install --global @leon-ai/cli@beta

# Create a Leon instance based on the develop GitHub branch
leon create birth --develop

# Create a report
leon check
```
