### ISSUE TITLE
german language support

### ISSUE THREAD

**Issue by rlech** [leon-ai/leon#8]
Awesome project!

Are there any plans to add german language support?

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Languages support](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support)

**Comment by louistiti** [comment]
Hello @rlech,

Thanks for your issue and your support. Yes there is actually plan for any languages which has:

- A "Porter" stemmer [here](https://github.com/NaturalNode/natural/tree/master/lib/natural/stemmers). It seems German has [one](https://github.com/NaturalNode/natural/blob/master/lib/natural/stemmers/porter_stemmer_nl.js).
- At least one speech-to-text that supports this language with a male voice.
- At least one text-to-speech that supports this language with a male voice.
- A [hotword](https://docs.getleon.ai/offline.html#hotword) model trained via the [Snowboy](https://snowboy.kitt.ai/) platform (as you can find in the `hotword/models` folder).

But please note that today I would prefer not to include further languages and scale later on.

However, I created a [Trello card](https://trello.com/c/PqiIElyx/217-%E2%9C%A8-languages-support) to list the potential languages support that people would like to have and contribute to.

Regarding the German language, would you like to contribute to the translation once we scale for further languages?

**Comment by louistiti** [comment]
Oh my! I thought it was kind of similar.

Regarding the TTS and STT parts, I was talking about [providers](https://docs.getleon.ai/configuration.html#voice) such as "AWS, GCP, IBM Watson" or even offline. To support a language Leon must has at least one male voice of that language (TTS) and be able to understand human voice in that language (STT).

Awesome for the translation part 👍

**Comment by louistiti** [comment]
I will close this issue as the answer has been provided.
