### ISSUE TITLE
Please add information about text-to-speech

### ISSUE THREAD

**Issue by vitaly-zdanevich** [leon-ai/leon#82]
What engine are use using?

**Comment by louistiti** [comment]
Hello @vitaly-zdanevich,

Thanks for opening this issue. Everything is already mentioned in [the docs](https://docs.getleon.ai/configuration.html#voice). And more should come later as you can see on [the roadmap](https://trello.com/c/lEZG0VYS/259-%E2%9C%A8-take-a-look-to-implement-a-new-offline-tts).

Does it reply your question?

**Comment by vitaly-zdanevich** [comment]
Oh, sorry, just did not found it in README.md.
