### ISSUE TITLE
can support Chinese? Can training to identify local languages?

### ISSUE THREAD

**Issue by deepdream88** [leon-ai/leon#84]
First of all, thank you for your contribution to open source. I would like to ask if the project can support Chinese? Can training to identify local languages?

**Comment by louistiti** [comment]
Hello @deepdream88,

Thanks for opening that issue and for your support.

Today Leon support English and French languages but I plan to also let him support other languages such as Chinese in the future. So stay tuned 😉 

Does it reply to your question?

**Comment by deepdream88** [comment]
> 你好@ deepdream88，
> 
> 感谢您打开该问题并获得您的支持。
> 
> 今天Leon支持英语和法语，但我计划将来也支持其他语言，如中文。所以请继续关注
> 
> 它回复了你的问题吗？

oh,thank you for your reply

**Comment by louistiti** [comment]
You are very welcome. I'm going to close this issue as the answer has been provided.

Do not hesitate to reopen it or open a new one if necessary.
