### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by FEAR6** [leon-ai/leon#86]
### Question
Does anyone know how to solve this problem?
I have installed python 3.6.7 on my server(Linux version 4.18.0-10-generic (buildd@lgw01-amd64-060) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)))
But I cannot pass the "npm run check"

The error information is showed on the picture.
![Selection_012](https://user-images.githubusercontent.com/46835808/56864810-8b847e00-69f9-11e9-9ebf-75bdb40b27f1.png)

**Comment by Shrubhog** [comment]
Are you starting the pipenv with the Python3 executable?

**Comment by louistiti** [comment]
Hello @FEAR6,

Thanks for opening that issue. As the screenshot mentioned, Leon supports Python `3.6`, so you need to install this version of Python instead of the `3.7`. It is mentioned in [the prerequisites](https://docs.getleon.ai/#prerequisites) also.

Does it help?

**Comment by louistiti** [comment]
I close that one as the answer has been provided.

**Comment by FEAR6** [comment]
> Hello @FEAR6,
> 
> Thanks for opening that issue. As the screenshot mentioned, Leon supports Python `3.6`, so you need to install this version of Python instead of the `3.7`. It is mentioned in [the prerequisites](https://docs.getleon.ai/#prerequisites) also.
> 
> Does it help?

I'm Very sorry for delayed response.

I do install python 3.6, not python 3.7.
And in the whole process, I only use python, not python 3

**Comment by FEAR6** [comment]
> Are you starting the pipenv with the Python3 executable?

Sorry about my delayed reply.  I used python, not python3

**Comment by FEAR6** [comment]
I think I found the question. Python version in "pipenv run python" is different from that in "python"
![Selection_014](https://user-images.githubusercontent.com/46835808/57770005-e6c8a700-7741-11e9-837e-83629069f0d6.png)
![Selection_015](https://user-images.githubusercontent.com/46835808/57770007-e7613d80-7741-11e9-870b-65af7b9249be.png)


I need to change the python version in "pipenv run python"
