### ISSUE TITLE
npm run docker:run fails on Windows Docker hosts - no /etc/timezone

### ISSUE THREAD

**Issue by zmpetro** [leon-ai/leon#87]
### Specs

- Leon version: Any / latest
- OS (or browser) version: Windows 10
- Node.js version: 10
- Complete "npm run check" output:
- (optional) Leon package version:

### Expected Behavior
```npm run docker:run``` runs Leon on Windows Docker hosts.

### Actual Behavior
```npm``` returns an ```ELIFECYCLE``` error. This is because the ```docker:run``` script in ```package.json``` sets the timezone using ```/etc/timezone``` which does not exist in Windows Docker hosts. Docker fails to run.

### How Do We Reproduce?
Attempt to run Leon using ```npm run docker:run``` on Windows hosts.

**Comment by louistiti** [comment]
Hello @zmpetro,

Thanks for opening this issue.

Could you please which of those following way work?
1. By using [Cygwin](https://www.cygwin.com/).
2. By setting up manually your timezone in the `package.json` file as follow:
    ```
    "docker:run": "docker run -e TZ=YOUR/TIME_ZONE -d -p 1337:1337 -it leonai/leon"
    ```
3. By replacing the run command in the `package.json` file, like so:
    ```
    "docker:run": "docker run -d -p 1337:1337 -it leonai/leon"
    ```
    and adding that at the line 12 of the `Dockerfile`:
    ```
    ENV TZ YOUR/TIME_ZONE
    ```

**Comment by zmpetro** [comment]
Hello @louistiti,

I did not try the first method, but methods 2 and 3 both work. I would have submitted a pull request but I thought I would let you guys handle it.

Let me know if you need any help.

Regards,
zmpetro

**Comment by louistiti** [comment]
Got it, thanks for saying!

Could you please try to run with the following command?

```bash
docker run -e TZ=UTC -d -p 1337:1337 -it leonai/leon
```

**Comment by zmpetro** [comment]
Hello @louistiti,

Running the following command:

```docker run -e TZ=UTC -d -p 1337:1337 -it leonai/leon```

works as intended and sets the time in the container to UTC. If I shell into the container and run ```date```, it outputs the time and date in UTC.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [📝 [1.0.0-beta.3] Docker run on Windows](https://trello.com/c/ow9zGDa8/271-%F0%9F%93%9D-100-beta3-docker-run-on-windows)

**Comment by louistiti** [comment]
Alright, thanks for your help!

I've updated the docs https://github.com/leon-ai/docs.getleon.ai/commit/840e775d18d89f1e2ad8077ca199a83a9a1a0ae8; https://github.com/leon-ai/leon/commit/f05d155f1b82dd2fd29c5b8fcca16868e8d30e40.

Do not hesitate to report if necessary.
