### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by kominoshja** [leon-ai/leon#90]
This issue is very similar to https://github.com/leon-ai/leon/issues/32

Are there plans to support a native experience on the Android &/ iOS? 
By doing things such as holding the home button and have Leon respond?

**Comment by louistiti** [comment]
Hello @kominoshja,

Thanks for opening this issue. There is for sure plans for a mobile app as you can see on the [roadmap](https://trello.com/c/I4covM3r/45-%F0%9F%93%9D-github), but regarding the home button researches will need to be made 😄

**Comment by kominoshja** [comment]
Great! I'm closing this issue then until we start working on the mobile app :)
