### ISSUE TITLE
How can we change the language ?

### ISSUE THREAD

**Issue by gnouf1** [leon-ai/leon#93]
Hi !
I'm french and when i see Leon can read and understand french, so how can I change his language ?

thanks,

**Comment by louistiti** [comment]
Hello @gnouf1,

Thanks for opening this issue. You can

**Comment by louistiti** [comment]
Hello @gnouf1,

Thanks for opening this issue. To do so, you need to change the `LEON_LANG` environment variable, you can find this variable in your `.env` file located at the project root directory. You can see more in [the docs](https://docs.getleon.ai/configuration.html#environment-variables).

I've updated the docs to make it more explicit https://github.com/leon-ai/docs.getleon.ai/commit/bc0d1349b100d009283ab24cc5045f1eac764aa8.

Does it reply your question?

**Comment by louistiti** [comment]
I close this issue as an answer has been provided.
