### ISSUE TITLE
Docker container produces js error

### ISSUE THREAD

**Issue by SuperSandro2000** [leon-ai/leon#96]
### Specs

- Leon version: 1.0.0-beta.3
- OS (or browser) version: Ubuntu 18.10 Docker
- Node.js version: 10-alpine
- Complete "npm run check" output:

````
docker run --rm -it -p 1337:1337 leon npm run check

> leon@1.0.0-beta.3 check /app
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.3

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /app/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.8

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 87, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
````

### Expected Behavior

Load something

### Actual Behavior

JS error

### How Do We Reproduce?

1. ``docker build -t leon .``
2. ``docker run -p 1337:1337 leon``
3. Navigate to the host ip of the machine and port 1337. eg: ``10.0.0.1:1337``

### Extra (like a sample repo to reproduce the issue, etc.)

Chrome 74.0.3729.131 error log
````
Navigated to http://XXX.XXX.XXX.XX:1337/
main.js:367 Uncaught TypeError: Cannot read property 'error' of undefined
    at main.js:367
    at Request.callback (main.js:1716)
    at Request.crossDomainError (main.js:1733)
    at XMLHttpRequest.xhr.onreadystatechange (main.js:1808)
(anonymous) @ main.js:367
Request.callback @ main.js:1716
Request.crossDomainError @ main.js:1733
xhr.onreadystatechange @ main.js:1808
XMLHttpRequest.send (async)
Request._end @ main.js:1877
Request.end @ main.js:1781
(anonymous) @ main.js:365
main.js:1877 GET http://localhost:1337/v1/info net::ERR_CONNECTION_REFUSED
Request._end @ main.js:1877
Request.end @ main.js:1781
(anonymous) @ main.js:365
````

Tested in incognito without any addons.

**Comment by louistiti** [comment]
Hello @SuperSandro2000,

Thanks for opening this issue. Could you please tell me which Dockerfile are you using? Is that the one from your PR or the existing one?

I don't think that will make a big difference, but I just want to ensure we use the same things to reproduce that case.

**Comment by louistiti** [comment]
I believe it is a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue.

1. Change the the environment variables `LEON_SERVER_HOST` and `LEON_WEBAPP_HOST` located in your `.env.sample` file (that file will duplicate a `.env` file) by replacing the value by the host IP of your machine.
2. Then build and run again.

I've just tried, and as you can see on the screenshot, I was able to access it via my phone browser:
![369848753](https://user-images.githubusercontent.com/1731544/57576392-6f6cec00-7491-11e9-812b-2bd2df5cddd3.jpg)
.

Does it help?

**Comment by SuperSandro2000** [comment]
I used the one from my PR but they should be the same and if not I need to fix mine.

Changing the env file fixed it. Maybe this should be clarified in the docs.

**Comment by louistiti** [comment]
Perfect.

I've updated the docs by adding a tip in the [web app client section](https://docs.getleon.ai/clients.html#web-app) and by specifying it at the [environment variables section](https://docs.getleon.ai/configuration.html#environment-variables) of the configuration page.

I'm gonna close this issue as it is all good now.
