### ISSUE TITLE
MediaDevices.getUserMedia() is not supported on your browser

### ISSUE THREAD

**Issue by SuperSandro2000** [leon-ai/leon#97]
### Specs

- Leon version: 97311aa1b4a51a82e2532ac91bfa6a3570b89dff
- OS (or browser) version: Ubuntu 18.10 Docker-CE
- Node.js version: 10-alpine
- Complete "npm run check" output: 
- (if using Docker) Complete "npm run docker:check" output:
````
docker run --rm -it -p 1337:1337 leon npm run check

> leon@1.0.0-beta.3 check /app
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.15.3

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /app/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.8

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 82, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
````
- (optional) Leon package version:

### Expected Behavior

Ask me for permission to access my mic

### Actual Behavior

main.js:469 MediaDevices.getUserMedia() is not supported on your browser.

### How Do We Reproduce?

Click the mic icon

### Extra (like a sample repo to reproduce the issue, etc.)

Using Chrome 74.0.3729.131

**Comment by louistiti** [comment]
Hello @SuperSandro2000,

Thanks for opening this issue. I've tried to reproduce the issue, the only moment I get an error is when I have already disallowed at first the access to my mic (which is normal). But once I click on the [camera icon](https://i.gyazo.com/4710ac95974e29d94582124448826dd4.png) then check `Always allow ... to access your microphone`, then refresh the page and the error is gone.

Also, did you make sure you have a mic input?

**Comment by SuperSandro2000** [comment]
I don't have such icon on the right of the address bar and on the top left in the drop down menu with permissions is nothing either.

I have a mic connected that works flawlessly with Discord.

**Comment by louistiti** [comment]
Alright, I think I've found the origin of the problem, it should be related to [this](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

Chrome disables features such as `getUserMedia` when it comes from an unsecured origin. `http://localhost` is considered as a secure origin by default, however if you use an origin that does not have an SSL/TLS certificate then Chrome will consider the origin as unsecured and disable `getUserMedia`.

What you can do is:

1. Setup an SSL/TLS certificate.
2. Or go to `chrome://flags`, search for the flag `unsafely-treat-insecure-origin-as-secure`, enter the origin you want to treat as secure such as `http://{YOUR HOST IP]:1337`, enable the feature and relaunch the browser.

Let me know if that works.

**Comment by SuperSandro2000** [comment]
I tried to get it running with Traefik like all other container I use and damn it was a hassle.

First of all your app does not play nice with reverse proxies. I needed to change the leons server port to ``80`` or it wouldn't grab ``https://leon.example.de:1337/v1/info``. My suggestion is to not grab it from the full URL but from a relative one.

Then I had some trouble with the ``.env`` file and that it always grabbed the ``.env.sample`` and redirect the calls to ``v1/info`` to ``localhost``.

Then it wanted to grab ``/v1/info`` over http.
````
Access to XMLHttpRequest at 'http://leon.example.de/v1/info' from origin 'https://leon.example.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
````

Traefik allows setting this Header only on 2.0 and I don't want to upgrade my reverse proxy to an alpha build. Could you change your code to better support reverse proxies?

**Comment by louistiti** [comment]
I've made a few changes under [that branch](https://github.com/leon-ai/leon/tree/reverse-proxy-improvement).

Please let me know your thoughts.

**Comment by SuperSandro2000** [comment]
* I still needed to change ``.env.sample`` and it did not pick up ``.env``.
* You need to add doc about the new protocol infront of the host
* It should not try to do this
````
GET https://leon.example.de:80/v1/info net::ERR_SSL_PROTOCOL_ERROR
````
I don't know what the smartest idea is cause I don't do web dev but the ``:80`` should probably go.
* and I still don't like that it needs the host where it runs. Can't it just take relative paths instead of absolute ones? Specifing the full host, protocol and port in a Dockerfile is just not great.

**Comment by louistiti** [comment]
Alright, I'll take a look at that.

Maybe you can help by contributing? I do not use Docker and Kubernetes that much today.

**Comment by SuperSandro2000** [comment]
``Hey! It seems you are going for a sleepless night, be careful.`` Got it working! pr ist here #99 

I am looking into the speech stuff hopefully the next days and send PRs or open issues if I encounter new problems.

Btw where does leon store its data? We would need to add a volume for that one.

**Comment by louistiti** [comment]
Awesome! And yeah as Leon said, be careful to not go for a sleepless night. I sent you an email to ask you a few questions regarding your use case.

Regarding the data topic, this part of the docs should answer your question.

I'm gonna close this issue as it has been solved, feel free to open a new ones.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0-beta.3] Reverse proxy improvement](https://trello.com/c/rDyVxPEK/280-%F0%9F%94%A7-100-beta3-reverse-proxy-improvement)
