### ISSUE TITLE
No module named 'tinydb'?

### ISSUE THREAD

**Issue by agrawalsmart7** [leon-ai/leon#98]
Hi,

I have successfully imported tinydb with pip but still facing the error.

The full error was:-

```
Error: Command failed: C:\Windows\system32\cmd.exe /q /s /c "pipenv run python bridges/python/main.py scripts/assets/query-object.json"
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Traceback (most recent call last):
  File "bridges/python/main.py", line 3, in <module>
    import tinydb
ModuleNotFoundError: No module named 'tinydb

```
For debugging, I tried to execute that command separately.

` C:\Windows\system32\cmd.exe /q /s /c "pipenv run python bridges/python/main.py scripts/assets/query-object.json"`

And successfully got the results. But It is not working with `npm run check`

Thanks

**Comment by louistiti** [comment]
Hello @agrawalsmart7,

Thanks for opening that issue. Please follow the issue template by explaining how you setup Leon and tell me what you are trying to do.

**Comment by agrawalsmart7** [comment]
Like as follows

1. npm install (worked)
2. npm run check (Causes that error.)

**Comment by agrawalsmart7** [comment]
Ohkay, I come to know why I am getting this. Its an error from Virtual environment. 

See this:- `Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.`

**Comment by louistiti** [comment]
You do not need to do anything, it should do it during the setup already. Try by running `npm run postinstall`, it will setup Leon for you.

Also, I just pulled and setup Leon on a Windows machine, and it is working well. I'm wondering how you setup Leon.

Please provide the result of these commands:
```
node --version
npm --version
python --version
pipenv --version
```

**Comment by agrawalsmart7** [comment]
Hi Louis, 

I can successfully run this. You can close this.
Thanks

**Comment by louistiti** [comment]
Alright, do not hesitate to open another issue if you need to 😉
